### ISSUE TITLE
change log4j.properties location

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#10]
Currently in web.xml, the log4j config file points to file://${PORTAL_HOME}/log4j.properties. We should change this to internal file in war. May need to modify WIKI page accordingly.

**Comment by serverhorror** [comment]
-1

Please don't! Having tomcat applications that aren't configurable without messing with the WAR file are an operational nightmare. Rather fall back to a somewhat sane behaviour if there is no `log4j.properties`

**Comment by ecerami** [comment]
my two cents:  I would down-vote this too.

Primarily because when setting up a new server, you may want to tweak logging to understand specific errors.  And, you don't want to have to recreate a WAR file each time you tweak log4j.properties.

(I am also dealing with this today, in fact, which made be think of this issue)....

**Comment by ecerami** [comment]
is is actually possible that this change was already applied?

I have a war file that I have created locally.  I then deploy to test server.  This server is not picking up log4j.properties on the server, but within the war file.

thoughts?

**Comment by jjgao** [comment]
@ecerami: No change has been made. Is your server picking up the log4j.properties under  $PORTAL_HOME now?
