### ISSUE TITLE
study view slower than before

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1002]
For less powerful machine, study view seems slower then before

**Comment by pieterlukasse** [comment]
could be because we reduced the delays between some of the functions in the code (i.e. `setTimeout` function) to make it more snappy. I can imagine this causes a long "synchronous" looking freeze in the UI on slower machines. Maybe set it back to the previous timeout intervals and see if perception is improved?

**Comment by jjgao** [comment]
@zhx828: are we retrieving mutation data for all genes or cancer genes? If all genes, that may be the problem. Could you prioritize bringing reactjs to replace the mutation and cna tables - ideally by the end of this week?

**Comment by zhx828** [comment]
@jjgao we are only loading cbioportal gene list which is 1018 genes. I will prioritize this issue.
