### ISSUE TITLE
Bug when selecting generic assay stable IDs in the Oncoprint

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#10078]
The filtering on Generic Assay Stable IDs per Generic Assay is broken in the Oncoprint.

To describe the bug, I've created two generic assays with the type `Generic_Assay_Patient_Test`. One has two stable IDs starting with `id_1_` and the other two stable IDs starting with `id_2_`, as you can see in the study view:
![Screenshot from 2023-03-13 09-24-40](https://user-images.githubusercontent.com/20278013/224648123-a77f815f-47fa-49db-9751-eeef4a15b805.png)
![Screenshot from 2023-03-13 09-24-56](https://user-images.githubusercontent.com/20278013/224648127-aa549fbf-b470-47f0-87b2-601653609b1c.png)

However, when I try to do the same in the Oncoprint, the separation on the assays is lost, and all entities are displayed under the same dropdown:
![Screenshot from 2023-03-13 09-25-39](https://user-images.githubusercontent.com/20278013/224648271-5efd53d1-a6f5-4bb3-8f54-6ba02cf187f0.png)

**Comment by dippindots** [comment]
@oplantalech Thanks for filing this ticket, I also noticed this issue.

The issue is if you have two profiles `profile_1 and profile_2`, and both of them have generic assay type: `ASSAY_TYPE_1`.
- In the study view page, generic assay entities are fetched based on each type of profile (`profile_1` or `profile_2`)
- In oncoprint, generic assay entities are fetched based on each generic assay type, then it will be `profile_1 and profile_2`
