### ISSUE TITLE
civic link broken

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10151]
![image](https://user-images.githubusercontent.com/1334004/235936959-581032e1-0144-4ba5-9c69-60c2f49fc2dd.png)

Button at the bottom here is broken. Should be:

https://civicdb.org/genes/14/summary

Instead of /events/...

https://genie.cbioportal.org/patient?studyId=nsclc_public_genie_bpc&caseId=GENIE-DFCI-004022

Related: https://github.com/cBioPortal/cbioportal/issues/10139

**Comment by onursumer** [comment]
Variant link is also broken.

![image](https://user-images.githubusercontent.com/3604198/236048158-46144ab6-f91a-4ad9-978e-c64a5b2951b8.png)

Should be https://civicdb.org/variants/2871/summary instead of /events/genes/7/summary/variants/2871/summary

Ideally, we should be following the [permalink documentation](https://civic.readthedocs.io/en/latest/api/v2/linking.html) for a proper fix. I think we can address this when fixing #10139.

**Comment by alisman** [comment]
@inodb, @onursumer has a quick fix using legacy api (and data).  Should we prioritize updating to graphql api so as to get the latest data?

**Comment by inodb** [comment]
@alisman @onursumer yes please - would be great if we can show the latest data! Thanks!

Also, hopefully it is pretty straightforward to port the same implementation to the Genome Nexus Variant Page after
