### ISSUE TITLE
localdb tests inconsistency between frontend and backend

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#10325]
It seems like our frontend and backend are running different local db test sets, see:
[current frontend localdb tests](https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/11610/workflows/70bca5f5-137a-4a1c-aa15-4a2e64be4de4/jobs/148087) and [current backend localdb tests
](https://app.circleci.com/pipelines/github/cBioPortal/cbioportal/5774/workflows/151b61c4-1803-44ec-ab8e-30062d2bd766/jobs/18228)

We should figure out why frontend and backend localdb tests are inconsistent and fix it.

CC: @alisman @JREastonMarks @inodb

**Comment by inodb** [comment]
@dippindots It make sense that they would run different ones. I believe it's like this:

- cbioportal/cbioportal run its own backend + frontend defined in pom
- cbioportal/cbioportal-frontend runs its own frontend + latest master backend of cbioportal/cbioportal

Does that explain the difference in test failures? I.e. would it be fixed by updating the frontend in the pom?

**Comment by alisman** [comment]
@inodb @dippindots i checked and it does indeed checkout the frontend branch/hash/version specified in pom.xml.   

i'm gonna look into adding the localdb test report to junit tool so we can kinda track this better.
