### ISSUE TITLE
Update Documentation on Deploy without Docker

### ISSUE THREAD

**Issue by JREastonMarks** [cBioPortal/cbioportal#10623]
With the rollout of 6.0.0 we have a different methodology for deploying cBioPortal without Docker. The documentation for this is currently incomplete.

Some things that are know to be needed to address
- Java Version
- Execution after building
- Importing Example Datasets

**Comment by barykada90** [comment]
Hi Jeremy - do we have ETA for this? Is it only documentation or also the files (pom, jsp etc)?

**Comment by JREastonMarks** [comment]
Working on the update right now.
It will probably come in two parts.
The first being the building of cBioPortal and deploying it.
The second being the data loading.

@barykada90 Would you be available to test those steps?

**Comment by barykada90** [comment]
Sure thing, happy to test!

**Comment by JREastonMarks** [comment]
@barykada90 Can you test these out when you have a chance:

[Step 1 - Software Requirements](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Software-Requirements.md)

[Step 2 - Prebuild Steps](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Pre-Build-Steps.md)

[Step 3 - Building from Source](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Build-from-Source.md)

[Step 4 - Importing the Seed Database](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Import-the-Seed-Database.md)

[Step 5 - Deploying the Web Application](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Deploying.md)

**Comment by barykada90** [comment]
@JREastonMarks - testing on both Win11 and Ubuntu:

Step 2 instructs copying application.properties to root but then maven is unable to find it when compiling as it's looking at src/main/resources path (because of the pom.xml entry)
(FYI application.properties file already has a predefined session.service.url value)
Step 3 - no information about environmental variable
Step 4 - typo "command"
Step 5 - entire paragraph about starting session is removed

**Win11** - error and fail when trying to start the application (no authentication):
16:52:58.763 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'portalProperties': Could not bind properties to 'PortalProperties' : prefix=, ignoreInvalidFields=false, ignoreUnknownFields=true

I'll test Ubuntu next

**Comment by JREastonMarks** [comment]
Hi @barykada90,
Thank you for testing and the feedback.
Step 2 - I updated the command.
Step 3 - No environmental variables should be needed to build cBioPortal
Step 4 - Fixed that Typo
Step 5 - Sessions are no longer required for 6.X

Win11 Error - That looks almost like it couldn't find the application.properties file.

**Comment by barykada90** [comment]
Thank you @JREastonMarks - amazing
I've tested on Ubuntu as it has the same error and had to fall back to Windows with some debugging.
The error was around the MySQL connection (I'm using 8.0.36 on ubuntu), so 2 things:
1. the username and password in application.properties don't match with the instructions so that needs to be unified ([STEP 2](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Pre-Build-Steps.md))
2. MYSQL was crying for public key retrieval so pom.xml must be updated with an additional query string allowPublicKeyRetrieval=true (which has some security concerns):
jdbc:mysql://localhost:3306/cbioportal?allowPublicKeyRetrieval=true&useSSL=false

I can confirm the session service is no longer needed to be spin out separately, however, the connection string must be still there, i.e.: session.service.url=http://localhost:8091/session_service/api/sessions/public_portal/ otherwise there's an error
<img width="428" alt="Screenshot 2024-02-20 163115" src="https://github.com/cBioPortal/cbioportal/assets/54397062/d731a5ee-db35-4994-bea2-58ad904ed688">

[Step 1](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Software-Requirements.md) - Java 21 is now a must, I've tried running on 19 and hit a brick wall

FYI, I didn't test STEP 4 as I'm running my own set of data

[STEP 5](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Deploying.md#run-the-cbioportal-backend) - typo command

Thank you!

**Comment by JREastonMarks** [comment]
Hi @barykada90 
Step 2 - Updated the documentation
Step 3 - I updated the docs to say Java 21 must be used
Step 4 - No worries, it will probably go through a couple of iterations
Step 5 - Typo Fixed

In application.properties.example session.service.url has a default value
Thank you again for all your help

**Comment by JREastonMarks** [comment]
Thank you again for reviewing this @barykada90 .

I'm not sure what typo on step 5 you are talking about. Can you expand?

**Comment by barykada90** [comment]
Hey - just whilst making more progress, I'm trying to upload some data and the error is thrown
`Expected to find 1 scripts-*.jar, but found 0`

So I read multiple docs and found on [STEP 4](https://github.com/cBioPortal/cbioportal/blob/issue-10623---Update-Documentation-on-Deploy-without-Docker/docs/deployment/deploy-without-docker/Import-the-Seed-Database.md) reference in core of the below which doesn't exist - is that still correct?
`scripts/target/scripts-*.jar`

Essentially I'm unable to load any data :)

**Comment by barykada90** [comment]
> Sess

Hi @JREastonMarks - it appears that when using SAML authentication, session service is still required (context: https://groups.google.com/g/cbioportal/c/lPk-_NxaggU)
