### ISSUE TITLE
Strange 501 error on clinical-data-bin-counts in normalization PR

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#11041]
http://localhost:8082/study/summary?id=esca_tcga_pan_can_atlas_2018%2Cnsclc_public_genie_bpc

Introduced with https://github.com/cBioPortal/cbioportal/pull/11037

**Comment by onursumer** [comment]
The newly introduced [normalizeDataCounts](https://github.com/cBioPortal/cbioportal/pull/11037/files#diff-4689c3a19361d9ee6a863aeceec6fbe3270f3e3df7764d7b6e089688829cded5R193) method was returning an immutable list which was causing the `add` method to produce `UnsupportedOperationException` in a later stage.

Fixed by [returning an ArrayList](https://github.com/cBioPortal/cbioportal/pull/11037/files#diff-4689c3a19361d9ee6a863aeceec6fbe3270f3e3df7764d7b6e089688829cded5R232) instead.

**Comment by onursumer** [comment]
@alisman @fuzhaoyuan we shouldn't be having this issue anymore since we merged the fixed version of #11037
