### ISSUE TITLE
Clinical-data-violin-plot discrepancy

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#11082]
NOTE: this is genie database, not public
```
curl 'http://localhost:8082/api/column-store/clinical-data-violin-plots/fetch?categoricalAttributeId=DEAD&numericalAttributeId=MUTATION_COUNT&logScale=false&sigmaMultiplier=4'           -H 'accept: application/json, text/plain, */*'           -H 'accept-language: en-US,en;q=0.9'           -H 'cache-control: no-cache'           -H 'content-type: application/json'           -H 'cookie: _ga_ET18FDC3P1=GS1.1.1727902893.87.0.1727902893.0.0.0; _gid=GA1.2.1570078648.1728481898; _ga_CKJ2CEEFD8=GS1.1.1728589307.172.1.1728589613.0.0.0; _ga_5260NDGD6Z=GS1.1.1728612388.318.1.1728612389.0.0.0; _gat_gtag_UA_17134933_2=1; _ga=GA1.1.1260093286.1710808634; _ga_334HHWHCPJ=GS1.1.1728647421.32.1.1728647514.0.0.0'           -H 'pragma: no-cache'           -H 'priority: u=1, i'            -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"'           -H 'sec-ch-ua-mobile: ?0'           -H 'sec-ch-ua-platform: "macOS"'           -H 'sec-fetch-dest: empty'           -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'           --data-raw '{"studyIds":["genie_public"],"alterationFilter":{"copyNumberAlterationEventTypes":{"AMP":true,"HOMDEL":true},"mutationEventTypes":{"any":true},"includeDriver":true,"includeSomatic":true,"includeUnknownTier":true,"includeGermline":true,"includeUnknownStatus":true,"includeUnknownOncogenicity":true,"includeVUS":true}}';
```

**Comment by onursumer** [comment]
There are two issues with this endpoint.

First issue is that the legacy `getClinicalViolinPlotData` method, which we still use in the clickhouse implementation, expects samples to have internal ids to calculate the number of unique samples. However, the filtered samples SQL (clickhouse) never returns internal ids, they're always null.

https://github.com/cBioPortal/cbioportal/blob/2e02f21f1a70eb8f3e0024afa20fa68beb553dc4/src/main/java/org/cbioportal/service/impl/ViolinPlotServiceImpl.java#L34-L38

Second and more critical issue is that `DEAD` is a patient attribute, not a sample attribute. So for this violin plot query we only get `MUTATION_COUNT` clinical data (which is a sample attribute) and we are missing all the `DEAD` clinical data.

We are only fetching the sample clinical data in clickhouse implementation. That's why we don't have the required patient clinical data to be able to generate the violin plot.

https://github.com/cBioPortal/cbioportal/blob/0ac1039105b1938f788958e4c2372d17cb6b1a88/src/main/java/org/cbioportal/web/columnar/StudyViewColumnStoreController.java#L353

Fixing the issue with internal ids shouldn't be too difficult. The issue with patient clinical data might require some additional SQL work.

Somehow, patient clinical data in legacy also have a `sampleId`

![image](https://github.com/user-attachments/assets/cece0c35-8b97-4d96-a03c-9c050997f690)

We don't have sample ids for patient clinical data in clickhouse.

![image](https://github.com/user-attachments/assets/2644e2fa-8a15-4b84-b460-776ffffdccad)

We might be adding some dummy sample ids in legacy code to make the violin plot logic work for patient clinical data.

**Comment by onursumer** [comment]
https://github.com/cBioPortal/cbioportal/blob/2e02f21f1a70eb8f3e0024afa20fa68beb553dc4/src/main/java/org/cbioportal/service/impl/ViolinPlotServiceImpl.java#L209-L218

This function seems working because, for the clickhouse implementation, internal id is always null for both `Sample` and `ClinicalData`, so the `filter()` never filters anything.
