### ISSUE TITLE
on study view clinical data tab's download is broken 

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#11142]
The download button [here](https://www.cbioportal.org/study/clinicalData?id=msk_impact_2017):

![image](https://github.com/user-attachments/assets/b737fa56-99ca-4f46-b297-abda4840dcd9)

Gives JSON output rather than a TSV:

<img width="635" alt="image" src="https://github.com/user-attachments/assets/d26819bd-00f6-42ba-8063-88d495b198e5">

Interestingly it does work when you click on this button:

![image](https://github.com/user-attachments/assets/2bcbc641-1c69-4bb7-afd4-f1f172b6c5fb)

Shouldn't these have the same behavior?

**Comment by Amrithesh-Kakkoth** [comment]
where di you find the upper image download button?

**Comment by Srayash** [comment]
hey @inodb this issue occurs as the serializeTableData uses `,` instead of `/t` as a delimiter.
https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/components/tableHeaderControls/TableHeaderControls.tsx
<img width="596" alt="Screenshot 2024-11-07 at 12 13 55 AM" src="https://github.com/user-attachments/assets/abeada42-03d3-4166-8337-648f9c33a60f">

can I work on this if this is open?

**Comment by Scorpion5127** [comment]
I downloaded the tsv file and do not see the same issue. I'm guessing someone fixed it?

**Comment by arishta-dev** [comment]
hi @inodb 
I have put a fix for the issue - please review https://github.com/cBioPortal/cbioportal-frontend/pull/5058
Thanks!
