### ISSUE TITLE
Enrichment / RPPA: Important proteins are missing from the graph or misplaced

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1135]
http://bit.ly/1rkWGSc

cannot find ESR1 and GATA3 in this graph, but they are at the top of the chart. EEF2K is misplaced - it's among three most overexpressed proteins in the graph  but in the chart it is downregulated.

![image](https://cloud.githubusercontent.com/assets/840895/14892024/17f34042-0d37-11e6-99e2-ff77d3ba832c.png)

**Comment by aderidder** [comment]
Hi @jjgao 

For mRNA and protein, the provided data should be in log-space; if it isn't, it is converted to log-space first. The problem in the issue above is that in the database the datatype is CONTINUOUS and not LOG-VALUE (looking at the new file formats this should now actually be LOG2-VALUE). Hence, the code tries to convert this data to log space first, which prevents the data from being properly displayed in the plot.
I think the best way to fix it would be to change the datatype to LOG2-VALUE and updating the code to work with LOG2-VALUE instead of LOG-VALUE. 

What are your thoughts?

**Comment by jjgao** [comment]
@aderidder I'll fix our data / database. But may be it also make sense to process non LOG2-VALUE profiles with negative data. At least some message should be displayed. Maybe, if negative data is detected, we can treat them as if they are log values?

**Comment by aderidder** [comment]
I've discussed it with @pieterlukasse and we would like to suggest:
* adding a check to the validator
* adding a message in the front-end to notify the user that there is a problem with his data

We would like to limit it to this; this is hopefully sufficient to help users/administrators to understand what they should do to fix their data.

**Comment by pieterlukasse** [comment]
@fedde-s : please add a link to your PR here

**Comment by aderidder** [comment]
Hi @jjgao 
Are we actually sure that the data is log data? Or could it also be z-score?
Also, we just found out that the validator (and documentation) don't allow for expression data with datatype LOG2-VALUE and LOG-VALUE. Perhaps that should be supported as well?

**Comment by pieterlukasse** [comment]
@aderidder : as just discussed with @jjgao, please use the following rule:
- if a negative value is found in set, just let the x values be the subtraction of the values and label this axis as such
- if no negative value is found, let the x values be the log ratio and label the x axis accordingly

@jjgao : please confirm and add any extra comments, if any.

**Comment by jjgao** [comment]
@pieterlukasse @aderidder that would be perfect!

**Comment by aderidder** [comment]
https://github.com/cBioPortal/cbioportal/pull/1199
