### ISSUE TITLE
Biogene service bug in SBGN network view

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#1186]
- Using the alpha deployment, open up the example query for "TP53 and MDM2/4 alterations in GBM".
- Go to Network tab
- Open up SBGN view for interaction between MDM2 and UBE2L3
- Select one of the macromolecules in Cytosol named "Protein target"
- See attached error from BioGene

This is probably a BioGene error that we should report to @armish

![biogene-error](https://cloud.githubusercontent.com/assets/3874988/15037189/75674e34-12a1-11e6-8a32-7252feaef54e.png)

**Comment by istemi-bahceci** [comment]
Fixed. Was due to not encoding gene names when constructing biogene query URL. Special characters in gene names like spaces etc. should be encoded when constructing biogene query URL. 

erroneous URL: http://cbio.mskcc.org/biogene/retrieve.do?query=p16-INK4a/p14-ARF mRNA&org=human&format=json

valid query: http://cbio.mskcc.org/biogene/retrieve.do?query=p16-INK4a/p14-ARF+mRNA&org=human&format=json

We should fix this also in SBGNViz.
