### ISSUE TITLE
Duplicated JavaScript code for OncoPrint

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/cbioportal#1306]
When attempting to change something in the OncoPrint in the `rc` branch, I seemed to find copies of the code I intended to change in three separate places:
- in `portal/src/main/webapp/js/src/oncoprint/webgl/setup.js`, under `window.CreateCBioPortalOncoprintWithToolbar`;
- in `portal/src/main/webapp/js/src/oncoprint/webgl/setup.js`, under `window.CreateOncoprinterWithToolbar`; and
- in `portal/src/main/webapp/js/src/oncoprint/setup-oncoprint-improved.js`

I could find no documentation in the code on why three versions were present in separate places in the same branch, and this makes working on it complicated. Can this be clarified in some way?

**Comment by pieterlukasse** [comment]
Hi @adamabeshouse, @jjgao : is this something that could still be improved in the new release? 

btw: I also see a folder called `portal/src/main/webapp/js/src/oncoprint/new/` with what I assume is the current oncoprint and a number of files just in the parent folder `portal/src/main/webapp/js/src/oncoprint` which is I assume the old(?) oncoprint. Maybe these could be cleaned-up to contain just the current files?

**Comment by adamabeshouse** [comment]
Hi @pieterlukasse and @fedde-s , good catch, these files definitely need to be cleaned up. You can ignore ```setup-oncoprint-improved.js``` - that's legacy code. 

Some work needs to be done with abstracting the duplicated code in the two oncoprint setup modes. Since the two modes work just slightly differently, I didn't see any obvious, elegant ways to abstract and DRY it up - please go ahead and do so if you figure out a good way to do it.

**Comment by pieterlukasse** [comment]
Thanks @adamabeshouse . I would propose the clean-up step first, i.e. removing all legacy code. And then we could focus on the remaining code later.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/2072
