### ISSUE TITLE
Don't append "&show_samples=false&" if there is no ? after index.do

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1547]
when query a custom case list, the data are posted. The url returned will be appended with "&show_samples=false&". 

http://www.cbioportal.org/index.do&show_samples=false&

**Comment by adamabeshouse** [comment]
The quickest non-hack fix which fixes this behavior to be somewhat more sensible is to make it become
`index.do?show_samples=false`
But that's a bit nonsensical in a way since that URL won't actually send you anywhere. So a bit more thinking would have to be done about how to decide when a session is URL-linkable and when it's not when deciding whether to modify the URL. What do you think?

**Comment by jjgao** [comment]
@mandawilson if you add the session id in the url, will that solve the problem?

**Comment by mandawilson** [comment]
Yes I solved it locally by making it: index.do?show_samples=false (I also left of the last & since it isn't needed).  There are two JavaScript methods called changeURLParam that have this issue.  In the versions that use the session service for bookmarking the URL will work.  I think the versions that do not use the session service for bookmarking should still switch to index.do?show_samples=false -- the URL may not work but at least it is correct structurally.

**Comment by jjgao** [comment]
Thanks, @mandawilson.

**Comment by adamabeshouse** [comment]
@mandawilson Just a friendly making-sure that the solution isn't hacky? :) i.e. that you modified changeURLParam to check if there's a `?` and insert one if not?

**Comment by mandawilson** [comment]
@adamabeshouse Yes I completely agree.
