### ISSUE TITLE
Relaxed processing of files by validator

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#1563]
Validator currently fails if the clinical files don't have meta data in them. 

The pipeline does that for us, so we are not manually adding them to our clinical files. On running the validator it always fails after the sample clinical file. Is there a way to make this a warning and allow it to finish the validation of all files.
![screen shot 2016-08-01 at 3 35 31 pm](https://cloud.githubusercontent.com/assets/12007862/17306510/65180044-57fe-11e6-8fb2-b672d27adfd1.png)

**Comment by fedde-s** [comment]
The internal pipeline at MSKCC may do that, but to my knowledge the data loading pipeline included in cBioPortal itself does not, and files without this header are incomplete according to the [documention](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data) on the file formats accepted by these data loading scripts.

The metadata in these headers are vital if the staging files are going to be shared with groups outside of MSKCC, so by default the validator should require them. I would understand if you want to add an option (either in the corresponding metadata file or on the command line of the validator) to allow it for internal datasets though, as these headers are a rather inconvenient place to express these metadata. Do note that in that case, loading an attribute not previously defined in the portal via another route (i.e. the part where it says `self.newly_defined_attributes.add(col_name)` around line 1499) must output an error.

**Comment by fedde-s** [comment]
None of our clients has currently expressed interest in spending money on this feature. @zheins, would you have time to implement it?

**Comment by fedde-s** [comment]
Or does the MSKCC pipeline eventually generate files that have these headers after all? In that case, the solution might be to simply validate those.

**Comment by n1zea144** [comment]
Hi @fedde-s As I understand it, the issue is that the validator should not "fast fail" during validation.  It's very tedious to run a dataset through the validator and have to address the issues one at a time.  I think it would be more efficient if the validator continued on validating other data files even if a previous file has failed a test.  Then the dataset curator can address the issues in batch mode.  Does that make sense?

**Comment by fedde-s** [comment]
@n1zea144: Yes, very much—in most cases it already does this. This one fast-fail (if none of the lines of the sample attribute file can be parsed because the header makes no sense), I originally built in because nearly *all* other files would be reported as using undefined samples otherwise. That led to a lot of confusion, as it made it unclear what the real issue was.

**Comment by n1zea144** [comment]
Would it be hard to update the code so that it no longer fast-fails or at least becomes an option?  I can have @angelicaochoa work on this if you are too busy.

**Comment by angelicaochoa** [comment]
@n1zea144 @fedde-s I can probably get this done today
