### ISSUE TITLE
DelIns events should be shown as indels in the oncoprint

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#1985]
currently shown as frameshift

http://bit.ly/2hmnpd5

![image](https://cloud.githubusercontent.com/assets/11892704/21109058/61d7627e-c065-11e6-87e1-af4cce6afa22.png)

**Comment by ckandoth** [comment]
Per VEP, [this event](http://grch37.rest.ensembl.org/vep/human/hgvs/3:g178928219G%3EGATA?content-type=application/json) has two possible consequences: `protein_altering_variant` and `splice_region_variant`, where `protein_altering_variant` is considered [more severe](http://useast.ensembl.org/info/genome/variation/predicted_data.html#consequences), and [this issue](https://github.com/mskcc/vcf2maf/issues/33) in vcf2maf (requested by @jjgao) will handle it as an `In_Frame_Ins`, which the portal should handle correctly.

However, when `protein_altering_variant` was first introduced in VEP v79 ([April 2015](https://github.com/mskcc/vcf2maf/commit/70be74bcafc1a3137ae3db0fa2a179781d6d548b)), I gave it a lower priority than `splice_region_variant` in vcf2maf. And this has since been unchanged. If I use the VEP priorities of severity, then this variant should correctly show up as `In_Frame_Ins`. I'll make this fix [in here](https://github.com/mskcc/vcf2maf/issues/103), but can't guarantee that this won't break other niche cases we've discussed over the years.

**Comment by jjgao** [comment]
@schultzn so it's both a indel and a splice_region. Do you mean we should pick indel over splice_region?

**Comment by ckandoth** [comment]
It's an in-frame insertion ([3:g178928219G>GATA](http://grch37.rest.ensembl.org/vep/human/hgvs/3:g178928219G%3EGATA?content-type=application/json&hgvs=1)) within a splice region, and vcf2maf is currently set to report it as `Splice_Region` under `Variant_Classification`, that cBioPortal parses. @schultzn would prefer it to be reported as `In_Frame_Ins` instead. I agree with this change, and just now [implemented it](https://github.com/mskcc/vcf2maf/issues/103) in the `develop` branch of vcf2maf. But there's a few more issues to handle and tests to run, before I can push out a stable `v1.6.13`. Genome Nexus annotation might do the right thing already, because the `most_severe_consequence` is reported as `protein_altering_variant` rather than `splice_region_variant`.
