### ISSUE TITLE
Error inserting mutation data in the database

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#2059]
Error:
ABORTED! java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: DB Error: only 89 of the 90 records were inserted in `mutation_event`. More error/warning details: Duplicate entry 'NA-0-0-NA-4595-Q335R-Missense_mutation' for key 'CHR'

Using the Python importer. I checked my data file and there was no duplication. Data imports fine when there are no other studies in the database.

**Comment by serval2412** [comment]
There's no duplicate inside your file since you don't reproduce the problem when there are no other studies in the database.
There's a duplicate between a record of your file and a record already present in your DB.

To find it, you can do this:
1) export your data (or just MUTATION_EVENT_ID + CHR) in Calc/Excel file from your DB containing all the other studies
2) check the CHR values from your datafile with the export (eg: with VLOOKUP function)
