### ISSUE TITLE
Error when clicking a 'slice' of a pie chart in study view

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#2096]
As @fedde-s pointed out, this error appears if you click a slice before the mouseover menu of the chart has rendered.
![captura de pantalla 2017-01-25 a les 11 47 19](https://cloud.githubusercontent.com/assets/20278013/22287711/1ac00c2c-e2f4-11e6-828b-e45bbaf569a0.png)

**Comment by fedde-s** [comment]
On which branch is this? Plain v1.4.1?

**Comment by oplantalech** [comment]
Yeap, in www.cbioportal.org

**Comment by fedde-s** [comment]
I might be wrong, but it seems to occur when clicking a slice before the mouseover menu for that chart has rendered.

**Comment by oplantalech** [comment]
The error happens, for example, in this study: http://www.cbioportal.org/study?id=acc_tcga#summary

**Comment by Sjoerd-van-Hagen** [comment]
@zhx828 Perhaps you could have a look at it?

The issue is not just visible in the console but also to the user, because the pie charts are not all correctly updated to reflect the change in filtering.

For instance, if I quickly click on gender:male on the URL that @oplantalech posted, thie pie chart itself is not updated but some of the others also still display all 92 patients.

![screenie](https://cloud.githubusercontent.com/assets/9987381/22291184/3d28c78e-e305-11e6-897c-222ebae8d43b.png)
