### ISSUE TITLE
Mutation Allele Freq not displaying

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2132]
cancer_study_id=egc_msk_janjigy_2017&case_id=P-0004680#nav_case_ids=P-0004680

Is it because the first sample has no mutations?

**Comment by jjgao** [comment]
@onursumer please make sure this is fixed in the new patient view.

**Comment by onursumer** [comment]
@jjgao seems like it is because of the first sample: https://github.com/cBioPortal/cbioportal/blob/94273890828889b775ef0b7d698ab617c72edf0a/core/src/main/java/org/mskcc/cbio/portal/servlet/PatientView.java#L309

For the new patient view page we always show the allele frequency column. There is no conditional hiding for that column.
