### ISSUE TITLE
Small issues in previous migration script

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2173]
The genetic entity `migration.sql` script has 2 minor issues which should be solved.
1- genetic_entity_id field is added to the `gene` table in a different order than found in `cgds.sql`. This can lead to problems when dumping a migrated DB and trying to load it again in another fresh DB schema based just on `cgds.sql`
2- The foreign key added to the `gene` table is named `fk_gene_1` while in `cgds.sql` this foreign key constraint is not named. Would be nice to align this (although it does not really lead to issues now). Another difference is that this same FK is CASCADE on delete in `cgds.sql`, while in `migration.sql` it is not. It is important to align this one to CASCADE. 

The fix will involve a new migration step, something like this (except not all DBs have `fk_gene_1`, so this step needs to be conditional):
```
-- update gene table to use genetic_element (after HUGO_GENE_SYMBOL, reflecting same order as in cgds.sql...this is important for exporting/importing DBs later on):
ALTER TABLE `gene` 
CHANGE COLUMN `GENETIC_ENTITY_ID` `GENETIC_ENTITY_ID` INT(11) NOT NULL AFTER `HUGO_GENE_SYMBOL`;

ALTER TABLE `gene` 
DROP FOREIGN KEY `fk_gene_1`;

ALTER TABLE `gene` 
ADD FOREIGN KEY (`GENETIC_ENTITY_ID`)
  REFERENCES `genetic_entity` (`ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;
```

Notify: @sandertan

**Comment by sheridancbio** [comment]
On issue 1, my concept would be to use cgds.sql always as the definition of the schema. If the migration script does not properly construct a matching schema when being applied to an earlier database schema then that should be considered a bug in migration.sql and can be directly fixed without creating a new db_schema_version. I noticed this difference too, and I had intended to add the "AFTER `HUGO_GENE_SYMBOL`" clause you indicated above in a new PR. (I also wanted to adjust couple of other small inconsistencies).

I also saw the discrepancy for cascade action in the gene table, and agree that this also should be made consistent. If a gene is to be deleted (I'm not sure when this actually happens), my guess is that it would be most natural to delete it from the gene table ... but the cascade on this foreign key would not remove the corresponding gene entry in the genetic_entity table --- it is the other way around, yes? So for the foreign key cascade to actually work, it would happen when someone deleted a record from the genetic_entity table ... then the corresponding gene records would also be deleted through this cascade. I think what we really want would be that if either a gene, or the corresponding genetic_entity record were deleted that the other would be automatically deleted too. But we cannot have constraints in the other direction because every genetic_entity is not a gene. So I guess we just need to make sure that a delete gene action occurs, we delete the corresponding genetic_entity record as well (in any delete_gene() function). Regarding the propagation of updates .. this is the case where someone had altered the genetic_entity_id for a record in the genetic_entity table ... and I think maybe we should just assume that this will never be done and not worry about whether the database engine will automatically update the matching gene record. If such an automatic update was done, we would need to carry it into profile records, and every other place where a genetic_entity field occurs. Maybe we could make this kind of propagation work properly, but I don't think we have a use case for it, and it would take some testing effort now, probably some tweaking, and then future maintenance. (or maybe I misunderstand the direction of the update cascades). Looking at cgds.sql, it just specifies ON DELETE CASCADE, and I think that is probably what we want (my opinion) .. so maybe this also can be directly fixed in migration.sql without needing a new db_schema_version

**Comment by sheridancbio** [comment]
Regarding the naming of foreign keys there is documentation here: https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html that makes it sound like the naming of foreign keys can be complicated, and that sometimes a name you specify may be ignored and auto generated under some conditions. Maybe in a previous msyql version it was always auto generated (I believed this at some point). If there is a way for us to give names to the foreign key constraints, that might be helpful … deleting a foreign key (if we want to adjust them in the future) cannot be done unless the name is known for instance. But if I were trying to apply custom names to all the FK's correctly, I would need to read more docs and experiment. It would be a bit of a project I think.

**Comment by pieterlukasse** [comment]
@sheridancbio thanks for the comments. If I understand you correctly, nr 1 is already solved in another PR (could you add the link?) and we can do nr 2 directly in migration.sql as indicated in my first comment, right?

**Comment by sheridancbio** [comment]
@pieterlukasse I did not yet create a PR for these issues, but I can. I will make a PR into hotfix with nr 1 and nr 2 above. (changing to ON DELETE CASCADE for the gene table)

**Comment by pieterlukasse** [comment]
Thanks @sheridancbio. I reviewed the pr. Closing the ticket here. :thumbsup:
