### ISSUE TITLE
Incorrect annotation of splice site mutation

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#2236]
This EGFR splice region mutation should be annotated as L210_splice, instead of L210L

http://www.cbioportal.org/case.do?cancer_study_id=nsclc_tcga_broad_2016&case_id=TCGA-50-5066

**Comment by jjgao** [comment]
@zheins could you please look into this and see if the current pipeline has fixed it?

**Comment by inodb** [comment]
So for this variant it's both splice and synonymous http://genomenexus.org/annotation/summary/7:g.55220240G%3ET and only the hgvs change of L210L is given.

```
{
"transcriptId": "ENST00000275493",
"codonChange": "ctG/ctT",
"entrezGeneId": "1956",
"consequenceTerms": "splice_region_variant,synonymous_variant",
"hugoGeneSymbol": "EGFR",
"hgvspShort": "L210=",
"hgvsp": "p.Leu210=",
"hgvsc": "ENST00000275493.2:c.630G>T",
"proteinPosition": {
"start": 210,
"end": 210
},
"refSeq": "NM_005228.3",
"variantClassification": "Splice_Region"
},
```
We should maybe have some rule that when variantClassification is `Splice_Region` it should set hgvspShort with the `_splice` variant instead, since that effect's priority is higher than the synonymous variant
