### ISSUE TITLE
Beta: new patient view clinical data falls off screen

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#2273]
When the clinical data tool tip is too long, the bottom attributes are not visible. See screenshot.

![image](https://cloud.githubusercontent.com/assets/2900303/24605529/78fa1896-1869-11e7-889f-976f04622e4c.png)

One solution to alleviate this a little bit could be to make the tooltip UI wider. This will allow for more attributes in the same vertical space. A scroll bar in the tooltip would look a bit odd...but is perhaps the only solution for when there are a lot of attributes.

**Comment by ecerami** [comment]
Assigning to @alisman who can choose to fix or delegate.

**Comment by khzhu** [comment]
Do we really need clinical tool tips there, since a viewer can click on "Clinical Data" table to find details? Also, it would be nice to have a "Patient" tab and a "Sample" tab instead of one "Clinical Data", a patient potentially could have more than one samples, then we will get a very long "Clinical Data" page too.

**Comment by pieterlukasse** [comment]
What was the solution?
