### ISSUE TITLE
Tumors column is missing from CNA table

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#2356]
In current production website, we have `Tumors` for both MutatedGene/CNA tables. But in beta, we only have it for MutatedGene table.

Production:
http://www.cbioportal.org/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-BF-AAP0

Beta:
http://www.cbioportal.org/beta/case.do?cancer_study_id=skcm_tcga&case_id=TCGA-BF-AAP0#/patient?caseId=TCGA-BF-AAP0&studyId=skcm_tcga

**Comment by onursumer** [comment]
Currently `TumorColumnFormatter` functions depend on `Mutation` data. We need to modify those functions in order to reuse for CNA table.

**Comment by onursumer** [comment]
Apparently we are showing multiple CNA values in a single row in the legacy implementation. In other words, we are **merging** multiple CNA rows into one. So, we need to implement a similar merge logic for CNA table as we did for mutation table.

@jjgao @alisman @adamabeshouse This basically means we need to process copy number data to create a merged version, and update **every** column definition to consume an array of `DiscreteCopyNumberData` instances, instead of a single `DiscreteCopyNumberData` instance.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/296
