### ISSUE TITLE
Validator: prad/tcga/pub/ has normals in data files which don't need to be defined in clinical file

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2466]
TCGA data has normals in almost all segment files and in expression file for prad/tcga/pub/ TCGA files might need to be 
![screen shot 2017-05-18 at 9 52 59 pm](https://cloud.githubusercontent.com/assets/12007862/26230090/60d6fb34-3c14-11e7-8d0d-3ce6dbf8a7bd.png)
an exception for this error.

**Comment by pieterlukasse** [comment]
I would suggest adding these samples to the sample clinical file. It is OK if we don't have the other clinical attributes for them now (as a first step - could find and add these later if available).

**Comment by fedde-s** [comment]
The main reason for the validator to require all samples to be listed in the sample attribute file, is because this is the only place that specifies which samples belong to the same person--the only explicit mapping between sample IDs and patient IDs. Including a sample in the sample attribute file does not mark it as diseased; the list of diseased/tumour samples is maintained in the case list with the `stable_id` set to `<study_id>_all`.

**Comment by ritikakundra** [comment]
@pieterlukasse @fedde-s I think we have decided to add normals to another file with its corresponding meta file and keep it till we decide to remove it in future
