### ISSUE TITLE
genetic profiles returns 500 error on mskcc portal (beta)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2527]
https://cbioportal.mskcc.org/beta/api/studies/acc_tcga/genetic-profiles

this returns 500

**Comment by jjgao** [comment]
As @inodb found out, the cause of the error was due to unsupported `DATATYPE` of genetic profiles:

![image](https://cloud.githubusercontent.com/assets/840895/26787420/eb2fee6e-49d7-11e7-9bfb-e41d91e9af75.png)

I did a database query of the public database and found the following profiles with unsupported data types:

![image](https://cloud.githubusercontent.com/assets/840895/26787469/165df0a4-49d8-11e7-8463-6e551ab99c67.png)

We should add this vocabulary to the validation code if not yet. @pieterlukasse could you help on that?

I have fixed the public database manually. @ritikakundra would you please fix the private database and meta files? 

Thanks!

**Comment by jjgao** [comment]
@ersinciftci will remove enum.
