### ISSUE TITLE
In IE11 the autosuggest widgets are too wide

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#2625]
Use browserstack, open up homepage in IE11.  For some reason the bootstrap-react-autosuggest for case and gene set are too wide.  or maybe their parent is too narrow.  please investigate.  this can be for 1.7.1

![image](https://user-images.githubusercontent.com/186521/27401837-aba1fcf2-5692-11e7-8b67-6548d1ee8af5.png)

**Comment by onursumer** [comment]
Actually, parents are narrow. Seems like it is mostly because of the overflow scroll bars. In chrome overflow scroll bars are properly padded. But in IE they partially overlap the content, which causes overall narrower component.

Also, auto suggest boxes are set to a fixed size. If somehow we can make them fit to the parent container, that would solve the problem.
