### ISSUE TITLE
some clean up of the mutations diagram

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2814]
- [x] Move the uniprot link into mouse over of domain and (no domain) diagram
- [x] Always show the menu bar
- [x] reduce the space between menu and diagram
- [ ] move 3D Structure into the menu bar

**Comment by onursumer** [comment]
Moving the `3D Structure` into the menu bar is kind of tricky/hacky at this point. The menu bar is currently implemented as a part of the lollipop diagram, and taking it out as a separate component requires some non-trivial work at this point.

So, for now the best non-hacky solution is to put the `3D Structure` button right next to the menu bar (see screenshot).

![3d-structure_button](https://user-images.githubusercontent.com/3604198/28548176-8b96b704-70a0-11e7-8bed-17d46fed6748.png)

**Comment by jjgao** [comment]
Next to the menu bar is OK. Can we put it right after the menu bar?

**Comment by onursumer** [comment]
Maybe with some CSS tricks/hacks. Otherwise the menu bar is currently the part of the diagram component, and I don't want to make the 3D structure button part of the same diagram component.

The best solution is to take out the menu bar as a separate component, but that requires some decoupling work for the diagram...

**Comment by jjgao** [comment]
In that case, can we still put the 3D Structure button to the old place, ie. next to the domain diagram. @onursumer
