### ISSUE TITLE
Add documentation to new Web API

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#2968]
We need to better document the endpoints in the new Web API.

**Comment by ecerami** [comment]
Ethan starting to write docs below:

Cancer Types:  Retrieve cancer type information, including full name, short name, stable identifier, and cancer type hierarchy.
Clinical Attributes:  Retrieve meta-data regarding clinical attributes associated with a specific study.  Meta-data includes display name, description, identifier and data type.

Please also use the endpoint docs below:

GET /clinical-attributes:  Get all clinical attributes.
GET /studies/{studyId}/clinical-attributes:  Get all clinical attributes in the specified study.
GET /studies/{studyId}/clinical-attributes/{clinicalAttributeId}: Get specified clinical attribute.

**Comment by ecerami** [comment]
@ersinciftci @jjgao:  above are my suggested API doc suggestions.  I have also suggested we change genetic to genomic.  Can you please review and make any edits?

**Comment by ersinciftci** [comment]
<img width="1253" alt="screen shot 2017-09-11 at 3 43 54 pm" src="https://user-images.githubusercontent.com/3595704/30293618-31a78546-9708-11e7-91c6-30f3d5bec875.png">

It looks like this after adding descriptions to controllers, so we decided with @ecerami to not do it because it doesn't look as pretty as the current page. I'll still make the changes in the sub-endpoints.

**Comment by ersinciftci** [comment]
@jjgao @ecerami There is a new Swagger 3 supported version of swagger-ui, http://petstore.swagger.io/, which would solve this problem as it shows descriptions in a smaller font, but we need to wait for Springfox library to update to Swagger 3 for this as well.

**Comment by ecerami** [comment]
@ersinciftci:  that looks way better, and I vote for that option!
