### ISSUE TITLE
OQL doesn't always detect invalid keywords

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3020]
Sometimes OQL correctly flags misspelled keywords:
![image](https://user-images.githubusercontent.com/10508276/29476301-61273a30-8431-11e7-9a22-cd2eae26d6aa.png)

But sometimes it doesn't:
![image](https://user-images.githubusercontent.com/10508276/29476315-716ee8fc-8431-11e7-9c0e-2aed6a16cf18.png)

![image](https://user-images.githubusercontent.com/10508276/29476320-79dc1e06-8431-11e7-8c82-87f188a78333.png)

![image](https://user-images.githubusercontent.com/10508276/29476339-8ec1558e-8431-11e7-9e4b-b3d46db7155c.png)

**Comment by adamabeshouse** [comment]
this is complicated.. the issue is that miscellaneous terms are parsed as mutation codes. So in the last example, theres no issue - it's looking for the IDH2 mutation with amino acid change code "HETLOOSS". I believe it's catching HOMDELL because it greedily parses HOMDEL and then encounters a syntax error with the L with no intermediate space.

**Comment by tmazor** [comment]
Thanks for the explanation @adamabeshouse. I'm still a bit confused though - I thought that OQL required an "=" to specify specific mutations - as in, if I wanted a specific IDH2 amino acid change, then don't I have to say "IDH2: MUT=R172" or "IDH2: MUT=MISSENSE"? Is the "=" not required?

**Comment by adamabeshouse** [comment]
`MUT=` is not required

**Comment by tmazor** [comment]
Thanks @adamabeshouse !
