### ISSUE TITLE
SAML/Keycloak: add back option to give study access via authorities table

### ISSUE THREAD

**Issue by messersc** [cBioPortal/cbioportal#3061]
Hi all,

I'm with @holtgrewe @bihealth.

Based on the discussion and particularly this comment by @pieterlukasse https://github.com/cBioPortal/cbioportal/pull/2525#discussion_r133393304, I would like to raise some concerns regarding this change in authorization.

### What does happen

If I read the discussion correctly, cbioportal will rely on authorities from the SAML token by Keycloak only for giving study access. The `authorities` table from the mysql database is not read in this case at all. Study access has to be granted using the Keycloak GUI as described in the documentation.

### What we would want

Ideally, we would like an option to do only the authentication via Keycloak, so that Keycloak has only to be set up once per cbioportal instance. Authorization would then still be possible over the `authorities` table, which can be done by the cbioportal admin as usual.

### Other possibilites

I just realized that Keycloak also offers fine grained admin permissions, so the portal admin could only have access to the cbioportal client and manage roles there.

Best,
Clemens

**Comment by pieterlukasse** [comment]
@messersc the intention is indeed to take all authorities from the SAML token. If you want to keep using the `authorities` table you could use the other SAML class `org.cbioportal.security.spring.authentication.saml.SAMLUserDetailsServiceImpl` (instead of `org.cbioportal.security.spring.authentication.keycloak.SAMLUserDetailsServiceImpl`). This is a generic implementation that should also work with Keycloak (although not tested specifically in this combination).  See this page for documentation of generic SAML integration, using SAML only for authentication: https://github.com/cBioPortal/cbioportal/blob/master/docs/Authenticating-Users-via-SAML.md

**Comment by messersc** [comment]
Hi,

switching to the generic saml class seems to have worked, authorization now relies on the mysql database like we want it to. Thanks for the hint, Pieter.

If anyone else would like to use a setup like this, just follow the guide on how to set up Keycloak correctly. But instead of assigning roles to users, you can use the "normal" way when configuring the generic saml class in your `portal.properties` (see above, should be the default).

Closing this.
