### ISSUE TITLE
Cancer Summary Plot Y-Axis Value Absolute Count Not Working

### ISSUE THREAD

**Issue by Tamba32** [cBioPortal/cbioportal#3236]
When you customize the bar configuration so that the y-axis displays absolute counts, a few things on the chart mess up
- The slider max value of the "Min. # Altered Cases" slider becomes incorrect
- The tooltip content for the bars switches/becomes incorrect, in general.

![image](https://user-images.githubusercontent.com/15708264/31295121-525d7f6e-aaab-11e7-94ff-ff87040fc5d8.png)

In the above picture, the max of the "Min. # Altered Cases" slider is 1 when, it looks like it should be around ~1250 (according the chart). Also, the numbers in the table for the "Breast Cancer" tooltip are incorrect.  Above the table, "Gene altered in 100% of 1 cases" is displayed; This sentence correlates to the other study in the chart, "Breast Sarcoma", so this is also incorrect.  The tooltip for 
 "Breast Sarcoma" (not shown in the picture) also displays incorrect information.

Query in the picture: 
- Study: Breast Cancer (METABRIC, Nature 2012 & Nat Commun 2016)
- Gene Set: Glioblastoma: TP53 Pathway (4 genes: CDKN2A MDM2 MDM4 TP53)

**Comment by alisman** [comment]
Problem is we're using totalAlterations.  Total alterations could include more than one alteration per sample.  That's why we can get above 100%.   Say there are 10 samples, eight of them have both mutation and fusion.  That means alterationTotal would be 16.  But in fact, only 80% of total samples are altered.  So we need to pass in a new value which is alteredSampleCount.
