### ISSUE TITLE
Cancer Studies histogram: No color when low number of studies

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#3240]
In the Cancer Studies histogram on the right side of the query page, the colors are missing when a low number of studies are displayed. It might be caused by the color gradient which goes from Dark (left) to Light/White (right). I tested this on `release-1.9.0`.

Example with low number of TCGA studies loaded:

<img width="1217" alt="screen shot 2017-10-10 at 14 14 47" src="https://user-images.githubusercontent.com/9624990/31385969-77c87a5c-adc5-11e7-86ab-92963ba17d68.png">

Example of cbioportal.org:

<img width="1190" alt="screen shot 2017-10-10 at 14 18 24" src="https://user-images.githubusercontent.com/9624990/31386083-e00dd1ca-adc5-11e7-89e0-d6180ed7d493.png">

**Comment by Tamba32** [comment]
Hi @sandertan. Unfortunately, this problem is hard to address because it is a case by case issue: The gradient color for each study is based on (1) the designated color of the cancer type (2) the number of studies at for that cancer type.  Each study’s color is calculated to be either a lighter or darker shade than the designated color for its cancer type.  The contacts used to calculate the lightness/darkness of each study were optimized for the number of public studies at the public site cbioportal.org.  That is why the colors for all the `Bladder` and `Head/Neck` studies show up properly on the public site but not the instance you are running - because you instance has less studies for each of these cancer types, their colors are not optimally calculated. It appears that they are lightened too much from their true yellow and maroon color and so they show up as white.

**Comment by sandertan** [comment]
Hi @Tamba32 thanks for the reply.

Would it be possible to set a "minimum lightness"? Some of the lighter colors (light blue, light yellow, ) on cbioportal.org are also difficult to see:
![screen shot 2017-10-16 at 12 06 45](https://user-images.githubusercontent.com/9624990/31606916-bf1f9bd4-b26a-11e7-990a-80a4652b41bf.png)

In addition to this, the white bars (lung, soft tissue, bone) are almost impossible to see. Is adding a dark border around them an option?

**Comment by Tamba32** [comment]
@sandertan It may be possible to set a minimum lightness, yes. I will address this issue for the next release.
