### ISSUE TITLE
structure mapping issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3259]
![image](https://user-images.githubusercontent.com/840895/31682817-3836a33a-b349-11e7-862f-35cd23e1aedd.png)

http://www.cbioportal.org/beta/index.do?session_id=595a3d29498e5df2e291f669#mutation_details

**Comment by onursumer** [comment]
Seems like there is no mapping available. API call returns an empty list for this chain (and for many other chains for this gene): https://g2s.genomenexus.org/api/alignments/uniprot/RASK_HUMAN/pdb/4epw_A/residueMapping

**Comment by jjgao** [comment]
Looks like it's G2S problem. This end point (https://g2s.genomenexus.org/api/alignments/uniprot/RASK_HUMAN/) has 4epw, but not this (https://g2s.genomenexus.org/api/alignments/uniprot/RASK_HUMAN/residueMapping).

**Comment by juexinwang** [comment]
I think it is caused by different iso of the protein. For simple, I set alignment part for checking all the results from all the iso, but residue mapping part is for the iso 1. I think for your usage, maybe I will change the residue mapping part to accept all the iso results. I may fix it tomorrow, no later than Friday

**Comment by jjgao** [comment]
@juexinwang we should not return all isoforms, but only the isoform that is being used. Otherwise it'll mess up with the mapping. In the case of UniProt, the canonical uniprot isoform (sequence) should be used.

**Comment by juexinwang** [comment]
@jjgao I think I have already fix it. Not only canonical uniprot isoform is used. Please check accordingly
