### ISSUE TITLE
How to securely update sessions in session service

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3325]
For the virtual studies feature, we now need to be able to update sessions, e.g. email addresses. Is the session-service update API safe? Can people hack it to wipe out our data.

I think if we only allow update requests with a session ID and if there is no way to get a list of session IDs, it should be fine. But we do need to get sessions based on an email address...

**Comment by kalletlak** [comment]
May be we could add basic auth

**Comment by jjgao** [comment]
Adding @inodb to this. We plan to add an API key before moving to Amazon.

**Comment by inodb** [comment]
@jjgao @kalletlak this adds basic auth such that we could host the session service publicly if we wanted to: https://github.com/cBioPortal/cbioportal/pull/4535

If we have one session service per portal, then we don't really need this since we can just only allow access from that one particular portal.

**Comment by inodb** [comment]
basic auth has been added and we are using this on AWS
