### ISSUE TITLE
Cancer Type Summary issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3368]
I tried to query for all studies in the portal and couldn't get Cancer Type Summary tab working:

http://www.cbioportal.org/beta/index.do?session_id=5a0b5c8d498e5df2e298382a

![image](https://user-images.githubusercontent.com/840895/32805533-badcb486-c957-11e7-9f08-ab019097c078.png)

**Comment by alisman** [comment]
this is happening because at line 91 of global_variables.jsp in portal project, the thca_tcga_pub study has no samples.  Ultimately, the frontend derives its list of studies from the list of samples (not sure if that's advisable). 
var studySampleObj = JSON.parse('{"thca_tcga_pub":[],"thca_tcga":["TCGA-BJ-A0Z3-01","TCGA-

**Comment by jjgao** [comment]
logged here: https://github.com/cBioPortal/cbioportal/issues/3376

@alisman do you have a list of studies with this problem? Which case list is the frontend looking for?
