### ISSUE TITLE
Heatmap not working

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3459]
Heatmap does not seem to be working. Steps to reproduce: go to http://www.cbioportal.org/index.do?session_id=5959f6ba498e5df2e291f327&show_samples=false&

Then click "add genes to heatmap" option in heatmap menu. Every time the button is clicked, only 1 of the genes is added with an **empty** heatmap track. See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/33208676-c4627b40-d112-11e7-806a-e3b22055e31e.png)

**Comment by jjgao** [comment]
@adamabeshouse could you look into this and see if you can fix it quickly?

![image](https://user-images.githubusercontent.com/840895/33328874-23dede7e-d429-11e7-9bea-e2c47622c524.png)

**Comment by adamabeshouse** [comment]
It seems the issue is the API call is returning data for a sample that's not in the given sample list: TCGA-A1-A0SO-01. We can probably ignore that issue since we have the new API, and just deal with handling that in the frontend - bug fix in this PR:

https://github.com/cBioPortal/cbioportal/pull/3469

I didn't write this code, so @pieterlukasse @fedde-s please confirm this bug fix would be appropriate.
