### ISSUE TITLE
Study view page error

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3518]
https://cbioportal.mskcc.org/study?id=prad_su2c#summary

![image](https://user-images.githubusercontent.com/840895/33625118-9638e82a-d9c4-11e7-8087-9c40ccee4168.png)

**Comment by zhx828** [comment]
@jjgao The issue is the clinical attribute ID in the clinical data does not match with the clinical metafile. In the metadata, the ID is `CLIN_M_STAGE`(the clincial_attribute_meta table) but in the clinical data is `CLIN_M_Stage` ( the 'clincial_patient' table).I can handle this issue, but since front-end does not convert any clinical attribute, the ideal output would be giving the user an error message saying the there is a data issue.

@ritikakundra @yichaoS could you do a quick fix on the data?

**Comment by sandertan** [comment]
The current validator only gives a warning when an attribute name is not completely in upper case:

https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/validateData.py#L1776

@jjgao @pieterlukasse Do you think this should be an error?

**Comment by pieterlukasse** [comment]
@sandertan I think that a better solution would be to let the importer set all to uppercase upon importing into DB. In this way the warning could also be removed. I would vote for a system that is not case sensitive for this part. Until then, we should perhaps change the current warning to an error (this is a quick fix).

**Comment by zhx828** [comment]
@sandertan @pieterlukasse for now, we will make sure all clinical attribute IDs coming from back-end be uppercases. Once the data validator supports the rule, we can think to remove the additional converter in front-end.
