### ISSUE TITLE
On study view, patients with 0 mutations are counted having no mutation data

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3561]
http://www.cbioportal.org/study?id=acc_tcga#summary

There are two patients in this study who show up in summary pie chart as "without mutation data".  In fact they have mutation data but zero mutations

**Comment by zhx828** [comment]
These two patients are not sequenced.

The confusion was caused when we try to visualize these two patients, one of the endpoints(http://www.cbioportal.org/api/molecular-profiles/acc_tcga_mutations/mutations/fetch?projection=DETAILED) used in patient view for fetching mutation data is returning an empty array which causes patient view thinks this patient is sequenced but without mutation data. Ideally, the endpoint should return 404 because the sample is not sequenced, but this is a POST method, it accepts multiple sample ids. It does not make sense to return 404 if one of the samples is not sequenced. 

TODO: patient view should add additional check to see whether sample is sequenced.
