### ISSUE TITLE
Problem with mutation table download on patient page

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3563]
https://cbioportal.mskcc.org/case.do#/patient?studyId=mixed_cbe_paradal_LP_brpdx&caseId=p_C_006081

VM109:390 Uncaught Error: Not all the arrays returned from the download functions are from the same length.

**Comment by onursumer** [comment]
@pieterlukasse @oplantalech seems like this bug is related to the `function getAsList<T>(data: Array<string|string[]>, maxColLength: number): string[][]`.

I think this functionality was added to be able to generate multiple rows from a single mutation row.

Could you guys take a look into this one?

**Comment by Toothstar** [comment]
I'm the user of this project, CMO LP_brpdx [07618]. Most shortcuts for downloading mutation CSV files don't work. I just tried the link https://cbioportal.mskcc.org/case.do#/patient?studyId=mixed_cbe_paradal_LP_brpdx&caseId=p_C_006081. It still doesn't work.
Thanks
