### ISSUE TITLE
study summary can be loaded from results page for unlimited number of studies

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3610]
From the query page, we limit accessing the study summary to 20 studies or fewer. However, if I run a query in all studies, the "Combined Study" link at the top of the page is a valid link and goes to the study summary for all 169 studies.
![image](https://user-images.githubusercontent.com/10508276/34083519-0cc7284c-e340-11e7-98ee-76fa08182614.png)

Should this link also be blocked when more than 20 studies are selected?

**Comment by jjgao** [comment]
Good catch. I am not sure if this link is so useful even for a query with less than 20 studies because it will combine all samples in the selected studies instead of the selected samples, which is the same "View Summary" in Modify Query.

@alisman for this release (1.11), can we remove this link for "Combined Studies"? Later we can properly solve it.
