### ISSUE TITLE
Plots tab and Co-expression tab shown inconsistent behavior

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#3635]
The Plots tab and Co-expression tab have dynamically generated mRNA profile lists. The lists will be generated based on the data available in the query results, instead of being generated based on the profiles of the study. This leads to confusing UIs that show varying behavior that can for example depend on which genes are queried together. This has been discussed here: https://groups.google.com/d/msgid/cbioportal/8E95CB621EE71146BFC0B9D614B2084AB9D269%40DCPWPEXMBX07.mdanderson.edu

Desired solution:
- The plots tab should always list **all profiles** available in the study
- The co-expression tab should always list **all expression profiles** available in the study

**Comment by pieterlukasse** [comment]
@jjgao are these plots being refactored already?

**Comment by jjgao** [comment]
@pieterlukasse not yet. We will do Plots tab next. Good idea to simplify the logic.

**Comment by jjgao** [comment]
@inodb who's going to work on this?

**Comment by alisman** [comment]
@inodb i believe this is a frontend issue, can you confirm?

**Comment by adamabeshouse** [comment]
bump @inodb

**Comment by jjgao** [comment]
@adamabeshouse the problem is that Plots tab and Co-expression tab are not listing all available mRNA profiles. 

http://bit.ly/2ncxRva

Co-expression only lists one RNA seq profile but not microarray:
![image](https://user-images.githubusercontent.com/840895/65921319-edce1a00-e3af-11e9-887c-d3d09bcf7284.png)

Plot tab only lists RNA seq and its zscore but not microarray:
![image](https://user-images.githubusercontent.com/840895/65921398-1a823180-e3b0-11e9-8614-08edd253740f.png)

We should:

- [ ] list all mRNA profiles (including z-scores and non-zscores) in Plots tab
- [ ] list all mRNA profiles (only non-zscores) in Co-expression tab (This is similar to enrichments tab)
- [ ] list all protein profiles (only non-zscores) in Co-expression tab as well
