### ISSUE TITLE
Error when mapping gene symbol to uniprot

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3644]
e.g. for `C3Orf70`

http://www.cbioportal.org/index.do?session_id=5a43c03b498eb8b3d562c025&show_samples=false&

Can we find out what other genes are missing this mapping?

Ideally found out a solution. At least, we should capture this error and still display the table.

**Comment by onursumer** [comment]
Seems like we have a valid entry for `C3Orf70` in the genome nexus mapping file: https://raw.githubusercontent.com/genome-nexus/genome-nexus/13262d83e8394382c73776f4584f269a4fb8c4cb/web/src/main/resources/ensembl_biomart_canonical_transcripts_per_hgnc.txt

This might be failing because of case sensitivity. I'll take a deeper look into the code.

So, I think any gene that doesn't have an entry or a valid mapping in this file can be considered as missing.

**Comment by onursumer** [comment]
Just confirmed that the problem here is case sensitivity. This one works as expected: http:/v1.genomenexus.org/ensembl/canonical-transcript/hgnc/C3orf70?isoformOverrideSource=uniprot

But this one fails: 
http:/v1.genomenexus.org/ensembl/canonical-transcript/hgnc/C3ORF70?isoformOverrideSource=uniprot

But, we still have gene symbols with no valid mapping in the file, so those genes will fail no matter what...

**Comment by jjgao** [comment]
Thanks, @onursumer. Please fix the case sensitivity issue -- maybe always use upper case in database? Please also get a list of genes in the portal that do not have mapping.

**Comment by onursumer** [comment]
@jjgao: Here is the quickest fix without modifying any file or database entry: https://github.com/genome-nexus/genome-nexus/pull/122

I'll try to make a missing gene list soon

**Comment by jjgao** [comment]
@onursumer I have some more thought about this. I think we should use either ensembl ID or entrez ID instead of hugo symbol for mapping. The problem is that hugo symbol changes too much over time.
