### ISSUE TITLE
Discuss issue with generated types and projections

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#3651]
This came up again because of new studies endpoint which required DETAILED projection when older single study endpoint did not require projection to get CancerStudy meta data.  Frontend code made assumption it would be there.

There needs to be some solution for this kind of thing. (Manual type extension?)

**Comment by ersinciftci** [comment]
Sorry it slipped my mind, I have should have mentioned that this change would be needed. It's because we use `projection` as a way to optimize calls that return a possibly long list of objects, so it's a bit redundant for endpoints that return only one resource, and also in order to make them look like real resource identifiers, like `/api/studies/acc_tcga` without any query parameters, we don't use `projection` parameter for them, so we return all the fields of that resource, which corresponds to `DETAILED` projection in other endpoints.
