### ISSUE TITLE
cancer types summary - x-axis labels cut-off and hard to read

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3695]
In a large multi-study query (e.g. all TCGA provisional), when I change the x-axis to Cancer Type Detailed, the labels are so tightly packed (perhaps even overlapping) that they are hard to read, and some are so long that they get cut-off

http://www.cbioportal.org/beta/index.do?session_id=5a54ccff498eb8b3d5636180

![image](https://user-images.githubusercontent.com/10508276/34788748-8ad09044-f609-11e7-8603-80ff23a7b022.png)

![image](https://user-images.githubusercontent.com/10508276/34788842-da004826-f609-11e7-8b99-9ce5372a35e1.png)

The text being cut-off is an even bigger problem if the y-axis is set to Absolute Counts:
![image](https://user-images.githubusercontent.com/10508276/34789190-4d5a1a30-f60b-11e7-929b-48dbec539537.png)

**Comment by jjgao** [comment]
@alisman let's handle this when you re-refactor the tab with victory.

**Comment by alisman** [comment]
This is fixed with victory implementation.  Chart now scrolls.  Still room for improvement:
1) Calculating label length (and thus bottom padding) is in exact science and so we end up with too much space sometimes.   
2) It's not clear that horizontal scrolling is available because scrollbar is on bottom.  Not sure how to handle this.  @jjgao what priority do you think this is?

**Comment by jjgao** [comment]
@alisman it's not very critical -- I hope we could use whole screen soon :) Could you log it?
