### ISSUE TITLE
patient view - misplaced comma

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3886]
The comma at the beginning of the second line (", DiseaseFree") needs to be at the end of the first line ("LIVING (10 months),")

![image](https://user-images.githubusercontent.com/10508276/36262366-357effc0-1235-11e8-836d-8d184f7c5a44.png)
http://www.cbioportal.org/case.do#/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC

**Comment by tmazor** [comment]
This is still an issue

**Comment by inodb** [comment]
Just to add some context: I haven't figured out an easy way to do this, because of the current implementation. The comma is placed using CSS and the hiding/showing/order of clinical attributes happens through CSS as well. With JS it would be easier to detect a line break but Im not sure if there's a CSS solution for this. Maybe @alisman has a good idea

**Comment by inodb** [comment]
@alisman in the example you shared it doesn't correctly add the comma between LIVING and DiseaseFree, right? Happy to discuss further

**Comment by alisman** [comment]
Made a new issue to #7631 for refactor of this using javascript instead of css
