### ISSUE TITLE
Lolipop plot not showing for MUC2

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3922]
This may be a duplicate issue.. but the MUC2 lollipop plot is not showing. I thought I saw this for other genes too.
http://bit.ly/2F58aR4

![image](https://user-images.githubusercontent.com/11892704/36852409-93212df6-1d39-11e8-9c99-d43886b32e63.png)

**Comment by inodb** [comment]
Ok so this is a data issue. Apparently the MUC2 canonical transcript `ENST00000630886` as set by vcf2maf is no in the grch37 set of transcripts, only in grch38. Either the list of canonical transcripts has to be set per grch37 or grch38. Or if the transcripts remain constants between different genome builds then we can use the same transcript info for both. 

This prolly applies to multiple genes. We should check which canonical transcripts in vcf2maf are not in the grch37 data dump.

**Comment by inodb** [comment]
Thought about this a bit more. So even though some default transcripts might be missing because of this data issue. What we could do instead is whenever `canonical-transcripts` returns an error (e.g. maybe that gene symbol is not in the list). We can use transcripts endpoint to query by hugo symbol and get all possible transcripts related to that hugo symbol. Then we can just pick the longest one. 

Also note that there's sometimes multiple canonical isoforms in vcf2maf (will file separate issue)
