### ISSUE TITLE
status when plotting a big oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3945]
When querying a big dataset (e.g. all studies), between the time of data loaded and that of oncoprint displayed, there is a delay. Is it possible to show some status, e.g Plotting OncoPrint... ?

![](https://media.giphy.com/media/DNweHBzELvLzXhHZyb/giphy.gif)

**Comment by alisman** [comment]
@adamabeshouse I did an experiment a little while ago.  It seems that the loader animation (which is a css animation) will continue to animate even when browser is locked due to oncoprint rendering.  i was able to hack in a way to detect when oncoprint is done rendering (measurement of width) which solved the problem @jjgao is talking about.  but it would be better if oncoprintjs itself issued events for this.  lets discuss.

**Comment by jjgao** [comment]
@alisman @adamabeshouse not critical issue if hard to solve.

**Comment by alisman** [comment]
should be easy

**Comment by adamabeshouse** [comment]
this has been fixed, loading doesnt disappear until oncoprint is rendered now

**Comment by jjgao** [comment]
After data is loaded, maybe we can change the message to "Rendering OncoPrint"? @adamabeshouse

**Comment by adamabeshouse** [comment]
merged into frontend `master`

**Comment by adamabeshouse** [comment]
done, check it out @jjgao http://www.cbioportal.org/index.do?cancer_study_id=msk_impact_2017&Z_SCORE_THRESHOLD=2&RPPA_SCORE_THRESHOLD=2&data_priority=0&case_set_id=msk_impact_2017_cnaseq&gene_list=KRAS%2520NRAS%2520BRAF&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna
