### ISSUE TITLE
[beta] downloads - add OQL to download files

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#3966]
The old downloads tab included the OQL applied to each gene. The new downloads tab only has that for the Gene Alteration Frequency table. I think we need to add it to the Type of Genetics Alterations Across All Samples table/download also.

**Comment by jjgao** [comment]
@onursumer: Ideally we should OQL only when an oql is specified by the user. Is that possible?

**Comment by onursumer** [comment]
@jjgao It seems possible, but needs some work. 

First, we need to add an option for the table to define a download function for the headers as well, a property like `headerDownload`. Because, OQL is part of the header in that table. (Mousing over each gene header reveals the full OQL string, but it is not included in the download file.)

Also, If the information (whether OQL is specified by user or not) is not available in the store, then we need to modify that part, too.

**Comment by jjgao** [comment]
@onursumer could you see if it's easy to do the first part: downloading oql / header? Please don't worry about the second one (whether OQL is specified by user or not).

**Comment by onursumer** [comment]
@jjgao first part is relatively easier, I'll look into that.
