### ISSUE TITLE
Downloaded Mutations data: NS vs WT

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3972]
Currently if a sample has no mutations in a gene, we put NA. It should be possible to put NS or WT. Can we do that? Maybe we need to use [this API](https://github.com/cBioPortal/cbioportal/pull/3793) for OncoPrint data?

**Comment by adamabeshouse** [comment]
@jjgao you're talking about oncoprint download tabular format, right?

**Comment by jjgao** [comment]
I was talking about Downloads tab, but I guess it can apply to OncoPrint too.

**Comment by ersinciftci** [comment]
@adamabeshouse @jjgao I had to revert the `includeNonMutated` feature I made to Mutations API because it was depending on the Gene Panel Data logic that we changed later https://github.com/cBioPortal/cbioportal/pull/4020#discussion_r176571198, so if someone is going to work on this, I need to re-implement it.

**Comment by dippindots** [comment]
@adamabeshouse No, I am not working on this one, I am working on the issue #4514 . Thanks for the mention.

**Comment by jjgao** [comment]
@dippindots was working on https://github.com/cBioPortal/cbioportal-frontend/pull/1729 to fix https://github.com/cbioportal/cbioportal/issues/4183, which is related to this issue.

@ersinciftci maybe we can wait for the `is-profiled` endpoint https://github.com/cBioPortal/cbioportal/issues/4225? It's probably time to do it.

**Comment by jjgao** [comment]
@adamabeshouse could you also help with this? I think the data is already available in oncoprint?
