### ISSUE TITLE
mutations tab should remember which columns are visible when filtering

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4011]
If I change which columns are visible on the mutations table, and then apply a filter (either through clicking on the lollipop plot or typing into the search box), the table currently completely re-renders and forgets which columns I had chosen.

Here, I add the functional impact column, then filter to breast samples, and the functional impact column disappears:
![mar-21-2018 13-37-48](https://user-images.githubusercontent.com/10508276/37727158-7c2d637e-2d0d-11e8-86d5-e2a312a792e3.gif)

Filtering shouldn't involve forgetting what a user has previously specified. Can we make it so the table remembers column visibility settings?

**Comment by onursumer** [comment]
Good catch.

Apparently this bug was introduced by https://github.com/cBioPortal/cbioportal-frontend/pull/975.

This bug is affecting only the tables with duplicate mutations. We are dynamically calculating the number of duplicate mutations **outside** the table component, so each time that number changes due to a filter action, the whole table re-renders. Seems like this resets the visible columns to initial state.

Moving this logic inside the `ResultsViewMutationTable` component would probably fix this bug.
