### ISSUE TITLE
profile frontend performance of oncoprint

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4017]
- API loading time
- Are we loading unnecessary data?
- Frontend processing
- Rendering

**Comment by adamabeshouse** [comment]
as far as oncoprint rendering, it seems basically 100% of javascript time spent sorting the tracks. 

I've logged an issue to oncoprintjs that I think will help address that - to allow radix sort which is O(n) instead of the costly comparator-based sort which is O(nlogn) (which will also make it possible to make some other optimizations). For impact this could mean a 10+ times speedup .. hopefully..
