### ISSUE TITLE
Negative values in Read Counts

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4162]
@ritikakundra commented on [Tue Apr 24 2018](https://github.com/cBioPortal/datahub/issues/199)

This issue was reported by a user:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/eER8Y1IzWj0/wga2g53NCAAJ

**Comment by jjgao** [comment]
Currently, the read counts (t_ref_count, t_alt_count, n_ref_count, n_alt_count) are defaulted to -1. We should probably change the default to NULL.

- [ ] write a migration script to set read counts to NULL if it's -1.
- [ ] fix import code to change the default to NULL.
- [ ] make sure web API and frontend functionality are working fine.

**Comment by n1zea144** [comment]
@jjgao I have a pr ([4206](https://github.com/cBioPortal/cbioportal/pull/4206) to fix import code to change default to NULL.  Front-end code seems to handle NULL in database ok (blanks instead of -1 is placed in table), but front-end code should be updated when multiple samples are displayed.  In this case, a NULL gets transformed to "undefined".

**brca_broad before fix (-1 in table)**
![image](https://user-images.githubusercontent.com/366003/39885642-24d6ffde-545b-11e8-8ba1-2bc52782fa68.png)

**brca_broad after fix (blank in table)**
![image](https://user-images.githubusercontent.com/366003/39885720-4e04ce9a-545b-11e8-8a8f-8db8e446e039.png)

**brca_bccrc_xenograft_2014 before fix (-1 in table)**
![image](https://user-images.githubusercontent.com/366003/39885824-9f61c298-545b-11e8-996a-d8071c9e0a92.png)

**brca_bccrc_xenograft_2014 after fix (undefined in table)**
![image](https://user-images.githubusercontent.com/366003/39885845-b4bb39f8-545b-11e8-8df1-a0155092696f.png)

**Comment by n1zea144** [comment]
Here are some links to dev/fix -

[brca_broad](http://dashi-dev.cbio.mskcc.org:8080/ben-portal/case.do#/patient?studyId=brca_broad&caseId=BR-M-005&navCaseIds=BR-M-005,BR-M-026,BR-M-027,BR-M-028,BR-M-030,BR-M-034,BR-M-036,BR-M-037,BR-M-038,BR-M-041,BR-M-045,BR-M-047,BR-M-048,BR-M-050,BR-M-055,BR-M-059,BR-M-073,BR-M-074,BR-M-076,BR-M-079,BR-M-080,BR-M-083,BR-M-085,BR-M-094,BR-M-095,BR-M-098,BR-M-105,BR-M-106,BR-M-110,BR-M-116,BR-M-120,BR-M-121,BR-M-122,BR-M-123,BR-M-126,BR-M-129,BR-M-150,BR-M-154,BR-M-155,BR-M-158,BR-M-165,BR-M-166,BR-M-167,BR-M-169,BR-M-172,BR-M-174,BR-M-184,BR-M-186,BR-M-189,BR-M-191,BR-M-192,BR-M-193,BR-M-198,BR-M-200,BR-V-002,BR-V-003,BR-V-007,BR-V-008,BR-V-009,BR-V-011,BR-V-012,BR-V-013,BR-V-014,BR-V-015,BR-V-016,BR-V-017,BR-V-018,BR-V-019,BR-V-020,BR-V-021,BR-V-022,BR-V-023,BR-V-024,BR-V-026,BR-V-027,BR-V-028,BR-V-030,BR-V-031,BR-V-032,BR-V-033,BR-V-034,BR-V-036,BR-V-037,BR-V-038,BR-V-039,BR-V-040,BR-V-042,BR-V-043,BR-V-044,BR-V-045,BR-V-047,BR-V-048,BR-V-049,BR-V-050,BR-V-051,BR-V-052,BR-V-054,BR-V-060,BR-V-064,BR-V-067,BR-V-069,BR-V-070,BR-V-071)
[brca_bccrc](http://dashi-dev.cbio.mskcc.org:8080/ben-portal/case.do#/patient?caseId=SA429&navCaseIds=SA429%2CSA493%2CSA494%2CSA495%2CSA496%2CSA499%2CSA500%2CSA501%2CSA530%2CSA531%2CSA532%2CSA533%2CSA534%2CSA535%2CSA536%2CSA542T&studyId=brca_bccrc_xenograft_2014)

links to cbioportal:
[brca_broad](https://cbioportal.mskcc.org/case.do#/patient?studyId=brca_broad&caseId=BR-M-005&navCaseIds=BR-M-005,BR-M-026,BR-M-027,BR-M-028,BR-M-030,BR-M-034,BR-M-036,BR-M-037,BR-M-038,BR-M-041,BR-M-045,BR-M-047,BR-M-048,BR-M-050,BR-M-055,BR-M-059,BR-M-073,BR-M-074,BR-M-076,BR-M-079,BR-M-080,BR-M-083,BR-M-085,BR-M-094,BR-M-095,BR-M-098,BR-M-105,BR-M-106,BR-M-110,BR-M-116,BR-M-120,BR-M-121,BR-M-122,BR-M-123,BR-M-126,BR-M-129,BR-M-150,BR-M-154,BR-M-155,BR-M-158,BR-M-165,BR-M-166,BR-M-167,BR-M-169,BR-M-172,BR-M-174,BR-M-184,BR-M-186,BR-M-189,BR-M-191,BR-M-192,BR-M-193,BR-M-198,BR-M-200,BR-V-002,BR-V-003,BR-V-007,BR-V-008,BR-V-009,BR-V-011,BR-V-012,BR-V-013,BR-V-014,BR-V-015,BR-V-016,BR-V-017,BR-V-018,BR-V-019,BR-V-020,BR-V-021,BR-V-022,BR-V-023,BR-V-024,BR-V-026,BR-V-027,BR-V-028,BR-V-030,BR-V-031,BR-V-032,BR-V-033,BR-V-034,BR-V-036,BR-V-037,BR-V-038,BR-V-039,BR-V-040,BR-V-042,BR-V-043,BR-V-044,BR-V-045,BR-V-047,BR-V-048,BR-V-049,BR-V-050,BR-V-051,BR-V-052,BR-V-054,BR-V-060,BR-V-064,BR-V-067,BR-V-069,BR-V-070,BR-V-071)
[brca_bccrc](http://www.cbioportal.org/case.do#/patient?studyId=brca_bccrc_xenograft_2014&caseId=SA429&navCaseIds=SA429,SA493,SA494,SA495,SA496,SA499,SA500,SA501,SA530,SA531,SA532,SA533,SA534,SA535,SA536,SA542T)

**Comment by jjgao** [comment]
Thanks @n1zea144. Your fix looks good.

@onursumer: could you update the frontend code for multiple samples?

**Comment by n1zea144** [comment]
@jjgao I merged the code and updated the databases.

**Comment by jjgao** [comment]
created https://github.com/cBioPortal/cbioportal/issues/4222. closing this one.
