### ISSUE TITLE
pancancer mrna data can be negative

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4186]
See analysis:

https://gist.github.com/inodb/26e77fb017d6b7b639a0d17d58b79728

A very small portion of v2 mrna continuous data is negative (.58% of all values). We are not sure why but for now we'll treat all as 0 instead. Based on the distribution it seems that `10^-2` might be a decent cap value for the log scaling.

**Comment by jjgao** [comment]
It was due to batch correction.

Here are the methods we had put in our pancan paper.


RNA Data Batch Correction

The expression data for mRNA and miRNA were batch-corrected to adjust for platform differences between the GAII and HiSeq Illumina sequencers. For mRNA, additional adjustments were made for different sequencing centers (The University of North Carolina [UNC] and British Columbia Cancer Agency [BCCA]) and a plate effect observed in PRAD. For the mRNA data, first batch 312 and 320 PRAD were adjusted to remove batch effects. UNC GA samples (UCEC, COAD, READ) were adjusted to the UNC HiSeq data. Genes with mostly zero reads or with residual batch effects (∼10% of genes) were removed from the adjusted samples and replaced with NAs. A similar adjustment was made for BCCA GAII-sequenced samples (LAML, STAD, ESCA) to HiSeq. Genes were adjusted using a novel algorithm called EB++; a variant of the Empirical Bayes / ComBat algorithm with training and testing features added.
