### ISSUE TITLE
Modify Query button missing

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4219]
@schultzn reported this one: "there is no modify query button when running a query on a subset of a virtual cohort." But I couldn't reproduce it.

In the session below, Modify Qury button is missing.

http://www.cbioportal.org/index.do?session_id=5af5fdf3498eb8b3d56617bc

**Comment by onursumer** [comment]
A quick debug shows that this condition resolves false: https://github.com/cBioPortal/cbioportal-frontend/blob/8826743e4cefd171660f2158f3fa419dbfd545a2/src/pages/resultsView/querySummary/QuerySummary.tsx#L85

More specifically, `this.props.store.queriedStudies.isError` is true. Seems like a virtual study issue to me.

**Comment by kalletlak** [comment]
I know what causing the issue, I'll create a PR once fixed it.

**Comment by kalletlak** [comment]
This problem comes when the number of studies in custom case set is a subset of selected studies. @jjgao @alisman @zhx828 how should we solve this?

**Comment by jjgao** [comment]
@kalletlak: Thanks. But I still don't understand exactly why Modify Query does not show up.

**Comment by kalletlak** [comment]
@jjgao that because of API fails which are looking for those studies. I can fix it depending on what we want to show(name and description) and studies that needs to be selected in modify query button click.

**Comment by zhx828** [comment]
@karthik just talked with JJ. I think the most corner cases are coming from study view. And there should be two fixes here: 
1. In study view, we only send selected studies after filtering to main/result page instead of originally selected studies. 
2. In the result’s page, if selected cases are not in all selected studies, only studies with these cases should be selected in the query selector and give a warning message that subset of studies are not selected.

**Comment by jjgao** [comment]
@kalletlak : discussed with @zhx828 , let do the followings:

- [ ] when querying from study view, let's only send studies with selected samples.
- [ ] on the results page summary, display studies with selected samples.
- [ ] for Modify Query, it's OK to select all query studies even if some of the studies have no samples selected (this will only happen when a user manually enter sample IDs)
