### ISSUE TITLE
1.14 beta plots tab fails to color by mutation status

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4354]
There are samples with mutations, but the plots tab shows all samples as "not mutated":
![image](https://user-images.githubusercontent.com/10508276/41246171-37e00d2e-6d78-11e8-868a-7c5ff18266a6.png)

The same query on production:
![image](https://user-images.githubusercontent.com/10508276/41246180-3f82ee2a-6d78-11e8-9bd1-7649ad41d62c.png)

http://www.cbioportal.org/beta/index.do?cancer_study_id=lgg_tcga&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=lgg_tcga_cnaseq&gene_list=TP53%2520ATRX%2520PTEN&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=lgg_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=lgg_tcga_gistic

**Comment by alisman** [comment]
@adamabeshouse you might be in position to diagnose this most quickly.  i did try mapping release 1.14.0 branch in production site and colors do appear, which suggests this might be a data issue?

**Comment by adamabeshouse** [comment]
I really dont know whats going on because it works on local (using release-1.14.0 branches in frontend and backend), which can only point to a /beta-specific environment issue, which points to some kind of data issue, which seems weird to me because the data is loading correctly for the mutations tab? But looking at the network tab, the call to `getMutationData.json` returns an empty array in /beta, and a nonempty array of mutations in production and local, so it must be related to that. Any ideas @jjgao ?

**Comment by jjgao** [comment]
@alisman has the backend `master` been merged to `release-1.14.0` and released to beta?
