### ISSUE TITLE
Move network servlet into legacy folder

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4366]
http://www.cbioportal.org/beta/network.do

This is used by Network tab.

**Comment by ersinciftci** [comment]
@jjgao NetworkServlet has a lot of dependency on other parts of the legacy code, and those dependencies has a lot of dependency on other parts as well, so it's not as easy as just moving the servlet to another folder.

**Comment by jjgao** [comment]
@ersinciftci thanks. Let's give it a low priority for now then.

Can I ask you to look into the code and see if we can support sample IDs as a parameter? Currently it only support case_set_id and case_set_key. Since we don't want to support case_set_key in the new frontend repo, it would be necessary to post all sample IDs.

**Comment by jjgao** [comment]
https://github.com/cBioPortal/cbioportal/issues/4369

**Comment by jjgao** [comment]
I moved this to icebox. But we will have to do it later if we want to get rid of the dependency to core module.

**Comment by ersinciftci** [comment]
@jjgao we basically can't get rid of the dependency to some big chunk of core module if we keep this servlet, and I believe our ultimate refactoring goal was to get rid of all the old code. So I think we should just create a new API for interactions and create a new frontend store for the Network tab. Otherwise we are just postponing the refactoring of the Network tab to later, basically.

**Comment by jjgao** [comment]
We are considering replace the network tab with new pathway mapper viz, so we may not need to work on this any more.
