### ISSUE TITLE
enrichments - rna/protein boxplot is missing y-axis tickmark at 0

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4379]
![image](https://user-images.githubusercontent.com/10508276/41616995-64d0fd42-73cd-11e8-9861-cba2da2d401b.png)

![image](https://user-images.githubusercontent.com/10508276/41617021-712ceb78-73cd-11e8-8bc0-e755fe80390b.png)

**Comment by ersinciftci** [comment]
I couldn't make this work, @alisman any idea what might be causing this?

**Comment by ersinciftci** [comment]
It actually turned out to be pretty simple https://github.com/cBioPortal/cbioportal-frontend/pull/1307, I was focused on the `default: crossAxis={false}` in https://formidable.com/open-source/victory/docs/victory-axis/#crossaxis, but apparently the default is not always false and is determined on the runtime.
