### ISSUE TITLE
Networks are super jumpy and jittering

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#458]
When opening the network tab for the first time or performing a new layout, the network bounces around like crazy.  Not sure exactly how to describe this, but it's as if the network jitters and bounces around for several seconds until it settles down.

It eventually settles down, but it looks like a serious bug.  And, I would nominate this as a high / critical bug to fix.

**Comment by onursumer** [comment]
It's not a bug, it's a feature :) It should be trivial to disable this animated layout feature. If we need better animation I guess we can also try to improve the animation behavior.

**Comment by ugurdogrusoz** [comment]
Ethan, this is the new layout animation feature that comes with Cytoscape.js. It shows how the layout progresses. Since networks in the portal are super dense, it's hard to see the underlying physical spring model used with layout (normally it's nice attractive feature). We can turn the default setting off if you like.

**Comment by ecerami** [comment]
I think we should disable this feature then.

**Comment by ugurdogrusoz** [comment]
Disabled

**Comment by ecerami** [comment]
Verified on hotfix branch.  Thanks.  Closing.
