### ISSUE TITLE
computePutativeDriverAnnotatedMutations doesn't find gene when you edit query

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4645]
In SPA, load a query, then edit query by removing a gene and then submit query.  You will get an error in computePutativeDriverAnnotatedMutations because gene is missing for corresponding mutations (in cache?).  Potential architectural issue we should review

**Comment by adamabeshouse** [comment]
@alisman this reflects an up and coming bug with switching to SPA - much of our code relies on the hidden assumption that the query happens once and all the data flows from the same query. a good caching system would be the best way to fix this. a naive GET- or POST-level caching system wont work for this, we need more granularity. but we also dont need something w too much versatility because our use case is pretty specific. lets have a serious talk about this, we can probably figure something out with an appropriate trade-off

**Comment by alisman** [comment]
@adamabeshouse  i think this bug was actually fixed by the change to mobxpromise.  Caching is separate issue, right?  (i.e. preserving data for individual genes across queries)

**Comment by adamabeshouse** [comment]
yes @alisman you're right
