### ISSUE TITLE
Copy number events: gain, shallow deletions

### ISSUE THREAD

**Issue by messersc** [cBioPortal/cbioportal#4664]
Hi

Maybe some context: we have been on a pretty old version of cbioportal for some time and have only recently spun up some up-to-date instances.

Comparing old and new results as well as investigating some missing data, we have stumbled across shallow deletion and gains not being imported and shown in the portal. The public instance also does not have them for the studies we checked.

I guess we should have paid closer attention and now I also found this old ticket https://github.com/cBioPortal/cbioportal/issues/95, but this needs to be communicated better.

# What the code does
```
 if (values[i].equals(CNA_VALUE_AMPLIFICATION) 
                                           // || values[i].equals(CNA_VALUE_GAIN)  >> skipping GAIN, ZERO, HEMIZYGOUS_DELETION to minimize size of dataset in DB
                                           // || values[i].equals(CNA_VALUE_ZERO)
                                           // || values[i].equals(CNA_VALUE_HEMIZYGOUS_DELETION)
|| values[i].equals(CNA_VALUE_HOMOZYGOUS_DELETION)) {
```

# What the FAQ says
> What do "-2", "-1", "0", "1", and "2" mean in the copy-number data?

# What the docs say
https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#data-file-1

    "-2" is a deep loss, possibly a homozygous deletion
    "-1" is a single-copy loss (heterozygous deletion)
    "0" is diploid
    "1" indicates a low-level gain
    "2" is a high-level amplification.

# Possible resolutions

From our point of view, it would be preferable if the user could decide on import if shallow events should go into the database or not.

But at least, I expect the validator or importer to generate errors or warnings.

Hope I'm not being unreasonable.
Kind regards,
Clemens

**Comment by jjgao** [comment]
@messersc the discrete copy number data is imported into two places: `cna_event` and `genetic_data`. For `cna_event` we only import 2 and -2, but for `genetic_data` we import all values.

The patient view page CNA table uses `cna_event` and therefore shows only AMP and HOMDEL. But you can query for all values in the query page. You would need to use [Onco Query Language](http://www.cbioportal.org/onco_query_lang_desc.jsp) in order to query HETLOSS and GAIN: e.g. `TP53: HOMDEL HETLOSS; EGFR: AMP GAIN;`.
