### ISSUE TITLE
inconsistent x-axis label style

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4754]
Expression & Plots:
![image](https://user-images.githubusercontent.com/840895/45117383-7170f500-b123-11e8-8c69-97eab6e0f7cc.png)

Cancer Types Summary:
![image](https://user-images.githubusercontent.com/840895/45117399-76ce3f80-b123-11e8-92b6-1553148f50cf.png)

Personally I like the direction in the "Cancer Types Summary" tab but maybe tilt it a little more (similar to Expression tab)

thoughts? cc'ing @cBioPortal/product

**Comment by schultzn** [comment]
I find the one used in Expression and plots easier to read though.

**Comment by alisman** [comment]
@jjgao We changed the angle/orientation in plots because leftward slant creates a difficult problem for padding on the left side of the chart (unless we make them very steep like Expression).   Like @schultzn, I actually find Expression now easier to scan because the beginning of the label aligns with the tick.   So, for both technical and aesthetic reasons, my vote is to adopt the Expression style elsewhere.

**Comment by jjgao** [comment]
@alisman @schultzn sounds good. Let's change `cancer types summary` to the same style too.
