### ISSUE TITLE
Build generic validation script for cBioPortal staging files

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#479]
The validation process for input data files needs to be extended and improved in a number of cases, such as listed in [RFC10](https://docs.google.com/document/d/1kxkXG-lRDX429eWmtUi5_b76XDxMuv14lNFAfR2vO4g/edit#heading=h.kt4rrolx4v8h).

The tasks are as follows: 
- start with the existing validation code found in  core/src/main/scripts/validateData.py
- improve and refactor validateData.py where necessary 
- add the new validation scenarios
- build unit tests to ensure validateData.py works correctly 

Goals: 
- more extensive validation of the input files
- clearer error messages when something is wrong/invalid in the input files
- report the error messages in such a way that it is easy to send the errors to different output formats: log file or html file for example

**Comment by fedde-s** [comment]
As part of the refactoring effort to make the script less buggy and more maintainable/adaptable, I have started the following tasks in [this branch](https://github.com/thehyve/cbioportal/tree/issue479_ImproveImportDataValidation):

- [x] move function and class documentation to [docstrings](https://www.python.org/dev/peps/pep-0257/) as customary in Python
- [x] refactor output message emission to use Python’s [logging framework](https://docs.python.org/2/library/logging.html) to isolate filtering and message formatting functionality to a single place, for consistency and customisability of output
- [ ] move duplicated column and format validation (and adaptation) functionality from the validator classes for different data file types to a superclass
- [ ] move global constants associated with the different data file type validators to their corresponding classes
- [ ] skip checking the data in a file if no assumptions can be made on their format because the column headers are incorrect
- [ ] load data files based on their corresponding meta files instead of looping over all files in the directory individually and making assumptions about the types based on file name expectations
- [ ] parse clinical data first (as would be done while loading), so that errors about undefined sample identifiers can be emitted by the validators that encounter them (with filenames, line numbers and column numbers)
- [ ] parse the character-delimited files with [the CSV parser in Python’s standard library](https://docs.python.org/2/library/csv.html) and use the `csv.Sniffer.sniff()` function to check their dialect (absence of quotation marks, etc.)
- [ ] remove the misfeature where the MAF validator expects the initial comment line to contain a list of all sample IDs in the file instead of the version number of the format, it is a violation of the MAF standard
- [ ] remove the unnecessary singleton factory pattern for validator classes for different data types, as currently having multiple files of the same type causes the first-found file to be checked multiple times
- [ ] base the exit status of the script on whether any errors were emitted through the logger, and remove the dysfunctional updates to global and local ‘exitcode’ and ‘errorcode’ variables

**Comment by fedde-s** [comment]
The validation scenarios that have been listed in [RFC 10](https://docs.google.com/document/d/1kxkXG-lRDX429eWmtUi5_b76XDxMuv14lNFAfR2vO4g/edit?usp=sharing) are as follows:

- [ ] allow only one mutation dataset per study, and require its id to be `study_id`_mutations (when deviating, the mutations tab does not work correctly)
- [ ] check if a case list with the id `study_id`_all is supplied – until #494 is implemented (the study view requires this to work)
- [ ] warn the user of how cBioPortal will behave when providing multiple datasets of the same type in a study, see #249
- [ ] if multiple profiles of specific types also leads to multiple case_lists, it is likely the counts in the Data Sets will be off or missing. Maybe a warning should be given when deviating from the standard naming
- [ ] improve validation of required columns for specific data, e.g. for mRNA hugo symbol and entrez are required, for miRNA a hugo symbol suffices (?)
- [ ] check whether clinical attributes with IDs that already exist from previously-loaded studies have the same type, priority and display name, and handle different studies that use the same column name to mean a different thing (or the same thing with a different priority). This requires access to the database. Note that a discussion on defining the data types of clinical attributes in another place than the data file is currently going on.
- [ ] check whether a cancer_type.txt file is present (and parseable) if the cancer type is not defined in the database, and fail if cancer_type.txt contradicts an existing database entry. This requires access to the database.
- [ ] check whether Entrez IDs and HUGO symbols of genes exist in the database, and fail if the data contradicts them. This requires access to the database.
- [ ] check if segment-wise copy number data files cover a significant potion of the genome (say, 80%), using the chromosome sizes on http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes or the corresponding url for the reference genome used in the cBioPortal instance, in case someone tries to load a file containing only significantly altered segments. cBioPortal needs to know what regions of the genome were actually measured in order to extrapolate the overall percentage altered.

**Comment by pieterlukasse** [comment]
remaining issues will be addressed in #249 and #244. 
Closing it now to focus on remaining issues. Will refer to this ticket in pr.
