### ISSUE TITLE
SPA: white space above table in Enrichments

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4818]
Can we remove the white space? Maybe the Mutations/Copy-number/mRNA header doesn't have to occupy a line.

![image](https://user-images.githubusercontent.com/840895/45641730-46bc6000-ba84-11e8-9516-20e3a1aaf4ee.png)

**Comment by alisman** [comment]
I think it's important to maintain heirarchy of controls b/c that's what makes the UI intelligible.   The Mutations/Copy-number/mRNA is really a submenu of enrichment and I thought about treating it that way more clearly (e.g. putting it in a band directly under the menu above it or centering it under the enrichments tab).     I will try putting the Data Set dropdown above the mRNA expression title.  That will compress a line and make things more compact, although I think it could be slightly confusing because it won't be totally clear that it governs the chart.

**Comment by alisman** [comment]
@jjgao I fixed the the unnecessary margin above the mRNA expression title.  But nesting the dropdown component inside what is effectively its child (the display) is something I would rather not do.  The whitespace to the right doesn't bother my eye.  I think the heirarchy is necessary to convey the logic of the UI.   I DO think the submenu could use some design/alingment work.

![image](https://user-images.githubusercontent.com/186521/45758376-7342ba00-bbf3-11e8-9350-1a2faa5fca22.png)

**Comment by jjgao** [comment]
@alisman Thanks. It's definitely improved. But I think it's looking better in the current production with a line under.

![image](https://user-images.githubusercontent.com/840895/45782032-bae73700-bc2f-11e8-9ab5-357d52b2b0b8.png)

Is there any reason the line is removed?

Another improvement we can do: Can we move the Data Set dropdown after the `mRNA Expression, RSEM ...` header? Maybe with one button "Select another profile"? The same for Protein.

**Comment by alisman** [comment]
I didn't like that design but i understand what you are saying.  I will try something else
