### ISSUE TITLE
lazy loading issue in SPA

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#4824]
In cross cancer query for mut and cna, when we open Cancer Types Summary, why are expression data being loaded? They should be loaded after clicking Expression.

http://www.cbioportal.org/alpha/results/cancerTypesSummaryTab?session_id=5b903556498eb8b3d567b494

![image](https://user-images.githubusercontent.com/840895/45644623-255f7200-ba8c-11e8-9e18-81f444707640.png)

**Comment by alisman** [comment]
@jjgao 

I believe this is because in Cancer Type Summary expression data is taken into account when tallying alteration counts and in fact is represented like any other alteration in bar chart.  See below.  Possible we could be smarter when expression data is not part of query?

http://www.cbioportal.org/alpha/results/cancerTypesSummaryTab?session_id=5ba0049c498eb8b3d567e40d

**Comment by jjgao** [comment]
@alisman but they are not loaded in the current production...

**Comment by alisman** [comment]
@jjgao looked into this a little further.
We are loading the molecular data in the old site, just in a single call instead of a separate call per profile as we do in the latest version.  The reason this changed is that we started using a cache to load the molecular data.  There's a tradeoff.  If we load them call per profile, we can then cache them per profile and have more granular caching control.  The downside is we're back to making lots of calls.   We can discuss further.

**Comment by jjgao** [comment]
@alisman two points for discussion.

- We don't think we should load expression data at all in this case since only mutaitons and CNAs were queried. We should only load them once the Expression tab is opened.
- Is there a way to cache per profile but pull together instead of caching per call? I don't think we should make a lot of calls -- we learned our lesson.

**Comment by alisman** [comment]
Agreed that we shouldn't load it unless expression data is selected, in which case we do need it for cancer type summary.  I will see if I can accomplish that. 

As for the caching issue, this is a good example of the difficult that we've run into.  If we make a single call but still want to cache on per profile basis, we have to not only "split and merge" on fetch, but then have a customized way of splitting the response into corresponding buckets we want to cache.  It's specific to each endpoint.  

We should discuss further if it this is an important enough use case to justify the added work/complexity.

**Comment by jjgao** [comment]
@alisman we may not be able to avoid having a customized way of caching. For example, when you add a new gene, you would only load the data for that gene. That means now you would need to split the calls per gene if we cache per call. The same applies to profiles and samples.
