### ISSUE TITLE
Document `-D` parameter configuration

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4832]
Following up on https://github.com/cBioPortal/cbioportal/pull/4787:

- [x] copy over runtime configuration for all parameters in GlobalProperties using resolveStringValue from heltgrewe's PR https://github.com/bihealth/cbioportal/compare/1352749b72a03db5a9091f79ceead4e268503b4c...bihealth:feature/spring-style-properties
- [x] Make sure the properties work
- [x] Document the following priority order of property loading:
    ```
    1. -D parameters
    2. PORTAL_HOME/portal.properties
    3. baked in portal.properties
    ```
- [x] Document that one can use `dbconnector=dbcp` so one doesn't need to set the db parameters in a tomcat recourse

**Comment by jjgao** [comment]
@inodb could you update this one?

**Comment by pieterlukasse** [comment]
@inodb the order should be 
1. PORTAL_HOME/portal.properties
2. -D parameters
right? Can we remove the baked in portal.properties altogether? See also discussion in https://github.com/cBioPortal/cbioportal/issues/5982

**Comment by pieterlukasse** [comment]
Should `dbcp` be the default? Would be nice if we don't need to set this explicitly.

**Comment by fedde-s** [comment]
I'd expect the way to specify options that is supplied last, closest to the runtime behaviour itself, to override any properties set earlier, in less flexible ways. So command-line parameters to the server process take precedence over environment variables and runtime configuration files, which in turn override compile-time options (if we continue to support those), which override defaults in the source code itself.

**Comment by fedde-s** [comment]
Also, isn't the first of the four check marks resolved already? Most, if not all, properties that are retrieved by methods of `core/src/main/java/org/mskcc/cbio/portal/util/GlobalProperties.java` should be overridable by `-D`-style Java system properties since the changes we implemented in [commit cbcbd05 of pull request 4787](https://github.com/cBioPortal/cbioportal/pull/4787/commits/cbcbd050ff224cbad75aedd5a062db859eedf870#diff-d5234aefb7508dcc8a8f17cb9684d495).

**Comment by inodb** [comment]
@fedde-s @pieterlukasse made a PR here: https://github.com/cBioPortal/cbioportal/pull/6046. We can discuss further

**Comment by pieterlukasse** [comment]
@inodb just a quick comment on the PR #6046 linked here: I don't think it solves the current issue, i.e. it does not "make all properties in GlobalProperties configurable in the same manner", since it leaves one or more of them to be configured via -D only. Are you planning to do a follow-up PR?

**Comment by fedde-s** [comment]
In addition, I believe that the current implementation leaves another inconsistency regarding properties that are not listed in the portal.properties file. For most properties, this will cause cBioPortal to use the default value listed in the code. However, for _some_ properties (ones that are read from the file by one of the various Spring applicationContext configurations instead of by the logic in the `GlobalProperties` class), cBioPortal will consult both the runtime _and_ the compile-time portal.properties file before falling back to the defaults.

**Comment by pieterlukasse** [comment]
good point by @fedde-s . I think we should also try to get rid of the "baked in portal.properties" (item 3 in @inodb's list above).

**Comment by inodb** [comment]
@pieterlukasse @fedde-s thanks for reviewing! You are right that not all issues are solved. I created two follow up issues. First I believe auth can only be configured with `-D` atm: https://github.com/cBioPortal/cbioportal/issues/6109. Then there's the issue that not all properties are configured in the same way: https://github.com/cBioPortal/cbioportal/issues/6110. I think both of these are outside the scope of necessary documentation updates for 3.0.0, which is mainly to be able to deploy session service using Docker. Unfortunately that makes the current documentation still quite complicated but we will try to address that with follow up PRs

**Comment by fedde-s** [comment]
All boxes in the original definition of the issue are checked and any remaining followup seems to be captured in other issue reports; I agree with the robot that this issue looks redundant now.
