### ISSUE TITLE
Network tab won't load

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#4865]
Network tab won't load with an error on the console.

**Comment by marriott-er** [comment]
Has this same issue, was due to the {,}, and \ characters in the request.
What version of tomcat are you using? Current releases don't allow those [0]
I "fixed" this by adding the relaxedQueryChars to my server.xml.
```
<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"
               relaxedQueryChars="{}\" />
```

[0] [https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters](https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters)

**Comment by jjgao** [comment]
it's fixed in production.

@alisman have the issue in beta now.

**Comment by ugurdogrusoz** [comment]
I confirm that it's fixed in live portal.

**Comment by pieterlukasse** [comment]
@jjgao @alisman is there a PR to fix this? What @marriott-er shared is of course only a workaround. I think the real solution would be to let the client side encode the url so that it only has valid characters.

**Comment by fedde-s** [comment]
Has this been addressed? And if so, in what PR, or approximately which branch/release?
