### ISSUE TITLE
Handle missing MUTATION_COUNT data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4895]
On OncoPrint the MUTATION_COUNT now shows up as having 92% data available, even though it is 100%, we are just treating missing data as 0. Possible solutions

- Fill in missing data on frontend as 0
- Add 0 values in the clinical database
- Fill in 0 values in backend at API level

I guess advantage of adding it in db is that we won't have to deal with it in multiple places. Downside is that it increase table size n response size

As reported by @schultzn 

CC @adamabeshouse 	@ersinciftci

**Comment by adamabeshouse** [comment]
@inodb filling in missing data would also have to take into account if the sample is sequenced at all, right? Personally I think it would be great not to have to code this as a special case, and fill it in at the clinical database level. But I dont know whats involved with that.

**Comment by inodb** [comment]
@adamabeshouse Correct - Im not sure how this was originally handled

**Comment by jjgao** [comment]
@inodb @adamabeshouse it was missing from the database previously too and was handled in the front end. https://github.com/cBioPortal/cbioportal/issues/4799

@inodb @ersinciftci: we should add the sequenced sample without mutaitons and assign 0 as their mutation_count. Could you prioritize that?

**Comment by yichaoS** [comment]
@schultzn ^

**Comment by sheridancbio** [comment]
PR #4907 has been merged and deployed. This corrected almost all cases, but after deployment it was noticed that the coverage for the mskimpact study went from 92% to 99%  (not 100%). The issue was looked into, and we think we understand what happened. If a sample is in the profile and yet has no mutation records in the MAF, we use a LEFT JOIN operation to construct a single record which does not populate any fields from the mutation / mutation_event tables. This is handled properly, and a single MUTATION_COUNT record with value 1 is inserted into clinical_sample.

However, if there *are* mutation records from the MAF, and all mutation records are filtered out of the count by the filtering of GERMLINE and Fusion records, then no records at all are present in the result, and no MUTATION_COUNT 0 record is set for that sample.

In the mskimpact study, there seem to be 451 samples that fall into this category .. where mutations are comprised only of GERMLINE or Fusion records. Here are some example sample ids:

**Comment by inodb** [comment]
There's also an internal issue where MUTATION_COUNT fails with a key constraint when you import mutation data split over two files, I've created a separate issue here: https://github.com/cBioPortal/cbioportal/issues/4950
