### ISSUE TITLE
lollipop plot text overflow issues

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#4922]
(1) When a lollipop is annotated with a long list of amino acid changes, it can get cutoff.
(2) The top y-axis number can overlap the y-axis label (this seems to be a problem when the y-axis goes up to a 4-digit number)

![image](https://user-images.githubusercontent.com/10508276/46433616-53e17c00-c71f-11e8-912e-b814e2be4780.png)
http://www.cbioportal.org/genie/index.do?session_id=5bb5159e498eb8b3d5682704

**Comment by jjgao** [comment]
This is strange. Why `12` and a few `G12` repeated. The one below looks better.

![image](https://user-images.githubusercontent.com/840895/46436840-eede5400-c727-11e8-915f-a337ccbfbc77.png)

http://www.cbioportal.org/index.do?session_id=5a36db91498eb8b3d5623600

**Comment by onursumer** [comment]
@jjgao The reason why `12` and `G12` repeated is that we have protein changes like `GG12DC` and `GG12AC`. We are running the `longestCommonStartingSubstring` algorithm on the entire set of the protein changes at the same position and this results in no common starting substring.

For the cut off problem for the long strings, in the older version of MutationMapper we used to justify the label so that it would never overlap the y-axis (see image below), but apparently we are missing that feature for the refactored version.

<img width="206" alt="lollipop_label_justified" src="https://user-images.githubusercontent.com/3604198/46475845-4b587680-c7ef-11e8-9ad5-1f0f73470976.png">

And, the reason for the overlapping y-axis label and the number is that we added the gene name to the y-axis label for the refactored version, which made the label longer enough to overlap with the number. An easy solution is to shift the label a few pixels to the left.

**Comment by jjgao** [comment]
@onursumer I see. Thanks for the explanation! Maybe we shouldn't show so many of them. Can we just show the top 3 sorted by occurrence, e.g. `G12D/V/S and 10 more`.

**Comment by onursumer** [comment]
@jjgao Showing `G12D/V/S and 10 more` is a good idea. I think we can still show the full label text in the tooltip.

**Comment by jjgao** [comment]
@onursumer per discussion, let's change the tooltip to “G12D/V/C and additional mutations”
