### ISSUE TITLE
Network tab broken in beta

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/cbioportal#5042]
Just tried the example query TP53 and MDM2/4 alterations in GBM with the beta (http://www.cbioportal.org/beta/). When trying to open the Network tab we get:
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at network.htm?20181018-2343&apiHost=%2F%2Fwww.cbioportal.org%2Fbeta%2F:151

**Comment by alisman** [comment]
Because we have to use a heroku hosted HTML page to get around the MSK network security issue, it's some work to get this this back in business.  The new code handles the encoding issue (brought up by Hyve) so it's incompatible with the heroku version.  When we deploy SPA, we'll also update the heroku version (that serves iframe) and this will all work everywhere.

**Comment by alisman** [comment]
Duplicate #4865
