### ISSUE TITLE
Don't use QueryBuilder for DOWNLOAD DATA

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5189]
@alisman since we are getting rid of QueryBuilder/index.do, I think we should reimplement the DOWNLOAD DATA functionality. We will need to pull data based on the form from the API. Hopefully they are the same ones as QUERY form. We will also need to reformat the data for downloading.

Alternatively, if the above is not easy, I am fine with remove the DOWNLOAD DATA query completely and add an option in Download tab in Results page that allow selection of any profile. (currently only queried profile is available there and not all profiles are available for querying, e.g. methylation)

**Comment by jjgao** [comment]
@alisman I think this is the last dependency to QueryBuilder. Let's prioritize this one.

**Comment by jjgao** [comment]
Should we also add this to the forked interface? ... but it should not be a big button like the other two.

**Comment by alisman** [comment]
JJ, I think the problem with forked interface is that, in download mode, you can only select a single study.   We could have a button but it would be disabled if there was more than one study selected?

**Comment by jjgao** [comment]
@alisman good point. Let's keep it separate. I might be a good idea to get rid of the Download Data tab and enable the functionality in the Download tab in Results page.

![image](https://user-images.githubusercontent.com/840895/61749026-b586db80-ad6f-11e9-969e-d18118802b9a.png)

That way, we can clean up a lot of code, I think.

**Comment by jjgao** [comment]
Maybe @dippindots can help with this once https://github.com/cBioPortal/cbioportal-frontend/pull/2197 is done?

**Comment by jjgao** [comment]
@cBioPortal/product any objections if we remove "DOWNLOAD DATA" form and move the functionality to Download tab in the Results page?

**Comment by jjgao** [comment]
@alisman @dippindots let's remove the DOWNLOAD DATA interface (ideally also clean up the code), and implement it in the Download tab in the Results page.

![image](https://user-images.githubusercontent.com/840895/61749026-b586db80-ad6f-11e9-969e-d18118802b9a.png)

**Comment by alisman** [comment]
@dippindots, as JJ's last comment shows, in order to replace the download data feature on homepage, the results view donwload tab needs to give the user a chance to select a molecular profile (which may not be the same profile as was submitted in query).   That's what the dropdown above shows.   I would implement this as a modal.  When user clicks a download in this list, we should show them a dialog that contains a dropdown with molecular profiles.  @jjgao this will be same list as they would see on homepage, correct? 
![image](https://user-images.githubusercontent.com/186521/62577912-ef76d800-b86d-11e9-831e-926864acc6ea.png)
The modal will also have a download button which will download the data for the selected profile.

**Comment by jjgao** [comment]
Instead of a moodel diagram, how about just have the dropdown in the page, as in the mock-up above?
