### ISSUE TITLE
No readiness/liveness probe endpoints available when authentication is turned on

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5326]
When authentication is turned on, there are no readiness/ liveness probe endpoints available. 

Desired solution:
- add specific webservice that is always open
or 
- open up `api/info` (e.g. http://www.cbioportal.org/api/info) in `security/security-spring/src/main/resources/applicationContext-security.xml`

**Comment by abessifi** [comment]
Something like `http://www.cbioportal.org/healthz` would be great too.

**Comment by pieterlukasse** [comment]
@inodb any ideas for this one? I'm guessing you already have a solution since you have recently moved all deployments to the cloud. Please let us know.

**Comment by inodb** [comment]
@pieterlukasse actually just ran into this issue during the hackathon when we moved our first authenticated portal to the cloud. We'll prioritize this

**Comment by abessifi** [comment]
@inodb do some HTTP endpoints for liveness and readiness are implemented ?

**Comment by inodb** [comment]
@abessifi yes since v3.1.7: https://github.com/cBioPortal/cbioportal/releases/tag/v3.1.7. Specifically: https://github.com/cBioPortal/cbioportal/pull/6910. 

Do note that the location will change from `/health` to `/api/health`: https://github.com/cBioPortal/cbioportal/pull/6920

We are using it like this now for one auth portal:

https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/cbioportal/cbioportal_backend_genie_public.yaml#L167-L173

But note that we will update it to use `/api/health` later. Probably with release 3.2.0

**Comment by abessifi** [comment]
Thanks @inodb !
