### ISSUE TITLE
Archer fusions truncated under Protein Change Column

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#5409]
I noticed the "Archer" annotation on fusions called by Archer gets truncated.  Is it possible to give this column a little more real estate?

![image](https://user-images.githubusercontent.com/366003/49652952-8b132880-fa01-11e8-814f-a4d0cd5d28f0.png)

**Comment by jjgao** [comment]
@n1zea144 that's doable. But I am not sure if creating a `- archer` fusion event is the best option. There is actually just one fusion event in the patient, but now we have four entries, which is confusing. Another confusing part is that the archer one has it's own row which only associates with sample 3, but it is very likely that the event occurred in all samples as they were detected in sample 1 and 2.

Another option would be adding the archer sample as a different sample and then for the archer validated samples, there will be an additional sample in Tumors column. We would need to find a way to merge fusions, e.g. the order could be different (I don't understand why though).

Adding @schultzn to this too.

**Comment by jjgao** [comment]
@alisman maybe you or @dippindots can do a quick fix to support more text in the `Protein Change` column?

At the same time, @n1zea144 and @schultzn I think we should reconsider this implementation. If using a different sample IDs for archer samples is not an option, we could also use the validation column to indicate a fusion is validated by Archer.

**Comment by schultzn** [comment]
Or maybe we can tackle this when we have fusions / rearrangements as a separate data type and then implement everything properly?

**Comment by jjgao** [comment]
@alisman and @dippindots please allow more text in the `Protein Change` column so that the current implementation can work.

@schultzn I think we'll have the same issue (msk-impact based and archer based) after we have SVs as a separate data type. I think it's probably worth some more discussion and see if we can solve it now. I also realized that the Archer samples were named differently initially and were mapped to the msk-impact samples. Maybe instead of doing that, we could try to model the sample relationships?

There is currently a gene panel issue b/c we mapped samples IDs. The IMPACT sample and Archer sample should have different panels, but it is impossible to assign two panels for the sample and same profile. Later when we have separate SV profile, it would be possible, but it would still be confusing since the same sample will have different panels. But if we treat them as separate samples, we would be able to assign gene panels properly even without separate SV profile.

**Comment by dippindots** [comment]
@n1zea144 Could you provide me the link to reproduce this issue? Thank you so much!

**Comment by dippindots** [comment]
@jjgao I can do a quick fix by changing the max length of the text. We are now allowed to display up to 20 letters. How many do we need to display?

**Comment by jjgao** [comment]
@dippindots could you increase it to 40?
