### ISSUE TITLE
Study view: columns in frequency tables should be right justified

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5412]
Columns in frequency tables in the new study view should be right justified. This should apply to The "#" and "%" columns. Percentages should always show one decimal, e.g. 10.0%.

**Comment by zhx828** [comment]
@schultzn I can do a alignment for the frequency column, but the # is tricky because of that checkbox. Do you think we need the right alignment for that column? 
![screen shot 2018-12-07 at 2 02 28 pm](https://user-images.githubusercontent.com/5400599/49667344-be1ce280-fa28-11e8-8769-f451513853dd.png)

**Comment by schultzn** [comment]
Thanks. It would look a lot better with alignment, but only if easy to do…

The Freq column looks much better already!
