### ISSUE TITLE
No data returned after selecting the top bin in density plot

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5420]
This seems apply to all combination study. http://www.cbioportal.org/beta/study?id=acc_tcga,lgg_tcga

If you select any dot on the density plot, no data returned for other charts

**Comment by zhx828** [comment]
Well seems like this issue is for some dots only. And the filter shows as < 1677 for mutation count, but the dot actually represents 1677

![dec-10-2018 20-50-29](https://user-images.githubusercontent.com/5400599/49772988-44e9ed80-fcbd-11e8-9196-a6fe310f10c6.gif)

**Comment by ersinciftci** [comment]
Yeah it happens only with the dots on the very top, because it's the only time a sample's mutation count is the same with the bin's yEnd, because it's the only open ended side of the plot, and normally bin's yEnd is not inclusive. It's a bit hacky but we can do something like: if it's the top bin, add +1 to the yEnd in mutationCountVsCNASelection filter in the frontend. (It won't affect any other samples because we know it's the top bin and there is no other samples above it).

**Comment by zhx828** [comment]
Issue has been addressed https://github.com/cBioPortal/cbioportal-frontend/pull/1821
