### ISSUE TITLE
Clinical data: downloaded file does not contain study name

### ISSUE THREAD

**Issue by paulcwvandijk** [cBioPortal/cbioportal#5439]
Steps to reproduce:
Go to study view --> clinical data: <http://www.cbioportal.org/beta/study?id=brca_tcga&tab=clinicalData>

Downloading the data results in a file with the generic name "data.tsv"
![screenshot 2018-12-13 at 16 45 38](https://user-images.githubusercontent.com/44695112/49949695-93ce9780-fef6-11e8-850e-26b54d70769c.png)

desired solution: the study name is included as in previous versions of cBioPortal

**Comment by paulcwvandijk** [comment]
notify: @jjgao @zhx828

**Comment by zhx828** [comment]
@paulcwvandijk the copy to clipboard has limitation on the size of data. We decided to remove copy button for clinical data table since the download would serve the functionality pretty well, also keep the  consistency instead of the current production study view, show copy for small study(the logic is not well designed, have potential issue anyway).
