### ISSUE TITLE
Clinical data tab:  COPY does not work (always)

### ISSUE THREAD

**Issue by paulcwvandijk** [cBioPortal/cbioportal#5440]
Related to issue #3073

Steps to reproduce:
Go to study view --> clinical data tab: <http://www.cbioportal.org/beta/study?id=brca_tcga&tab=clinicalData>

Clicking on copy does not work for this study.
Tested for other studies as well and then it worked so behaviour seems inconsistent.

desired solution: consistent behaviour when clicking on copy.

**Comment by paulcwvandijk** [comment]
notify: @jjgao @zhx828

**Comment by zhx828** [comment]
@paulcwvandijk the copy to clipboard has limitation on the size of data. We decided to remove copy button for clinical data table since the download would serve the functionality pretty well, also keep the consistency instead of the current production study view, show copy for small study(the logic is not well designed, have potential issue anyway).
