### ISSUE TITLE
This VS does not work

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#5503]
http://www.cbioportal.org/genie/study?id=5af36efd498eb8b3d5660e24

The summary endpoint returns 403

**Comment by zhx828** [comment]
@jjgao this study contains two public studies(nsclc_tcga_broad_2016, lusc_tcga_pub) which are not presented in the genie portal. Need to follow up with Ino why this VS is even showing up in the genie portal. But in the similar scenario, what's the expected study view behavior? Showing some error message saying the study is not accessible?

**Comment by jjgao** [comment]
@zhx828 the problem is that we don't have a way to know where a virtual study is created and if I save a virtual study in private portal, it'll show up in genie portal. Let's discuss when @inodb is back.

**Comment by inodb** [comment]
@zhx828 @jjgao so the problem with this is that genie's session service url is `/api/sessions/msk_portal/`. If this would've been `/api/sessions/genie_portal/` for genie portal, there wouldn't have been any issues. I think we'll have to

1. come up with some migration code to move all sessions with a genie study to be of `source ` `genie_portal` instead of `msk_portal`
2. update the genie portal session-service url to point to `/api/session/genie_portal/`

**Comment by inodb** [comment]
This issue applies to these portals as well:

```
acc
gdac
glioma
immunotherapy
kras
poetic
prostate
sclc
su2c
target
```

**Comment by inodb** [comment]
- [ ] anything in msk_portal source that has genie study copy over to genie_portal source
- [ ] create new sources for the other ones (ignore existing ones)

**Comment by inodb** [comment]
@jjgao 	this is done now - lmk if u notice anything strange
