### ISSUE TITLE
Mutated Genes table does not calculate frequencies correctly

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5613]
I see this issue in the AACR GENIE study when selecting samples that have mutations in multiple different genes. I see frequencies greater than 100% sometimes.

I think this happens when selecting genes that are only covered in some samples.

![image](https://user-images.githubusercontent.com/11892704/51227745-aee05d00-1923-11e9-8902-cc82ce472dbb.png)

**Comment by zhx828** [comment]
@ersinciftci @onursumer could one of you take a look this ticket? If you go to genie portal, select NUTM1, ZFHX4 from Mutated Genes table, then click `Select Sample` you will see the endpoint returns frequency: 121.57 for NUTM1.

**Comment by schultzn** [comment]
Got it - thanks. Another reason why we need to decouple fusions from mutation…

**Comment by jjgao** [comment]
Separate fusions from mutation would fix the issue. It'll take some time before we separate them completely.

For the moment, maybe we can create a Fusion Genes table in study view by using all the fusions in mutations table and for Mutated Genes table, let's not pull fusion data? @schultzn @zhx828

**Comment by schultzn** [comment]
That would be good!

**Comment by jjgao** [comment]
@zhx828 @onursumer 

- [ ] do not return FUSIONS in the mutated genes API
- [ ] add an API to return FUSION gene count
- [ ] add Fusion Genes table
  - in this table, not sure if we can have the Freq column since we don't have proper gene panels for fusion.

**Comment by jjgao** [comment]
@khzhu do you think you'll have the bandwidth to handle this one?

**Comment by khzhu** [comment]
yes, will start to work on it next week.

**Comment by n1zea144** [comment]
Hi @khzhu Any progress on this?  It was reported by another GENIE user recently.

**Comment by khzhu** [comment]
Hi @n1zea144 , was told to hold till JJ came back. Hongxin and myself had some discussion on how to implement web APIs to retrieve the Fusion data from the database. Fusion currently is stored in the mutation/mation_event table, so it does not has it own business models, web services would still have to use those mutation repositories.
I will ask @jjgao if we could schedule a meeting to discuss the issue.

**Comment by zhx828** [comment]
- Make sure `https://www.cbioportal.org/api/swagger-ui.html#/Study_View/fetchMutatedGenesUsingPOST` will only return mutations (it's under internal set of endpoints)
- Add an new endpoint  `/fusions/fetch` under internal study view returning the fusion data
- The sql query should support the filtering, by default, returning everything(this is important for other pages)
- Follow the data stream of endpoint `/mutated-genes/fetch` to find out how the mutation frequency is calculated and do the same thing for fusion. There may be some discussion need to have about how the fusion frequency should be calculated, but you could leave it as TODO until the later phase of implementation

**Comment by zhx828** [comment]
@khzhu let me know if you have more questions

**Comment by khzhu** [comment]
thanks, @zhx828! will take a look and get back to you.

**Comment by jjgao** [comment]
A tricky one is gene panel. We don't have proper gene panel for fusions because the gene panel for mutations are not the same as fusions. And also fusion partners are everywhere.

One option is ignore gene panels. The problem will be that the frequencies will be lower than the actual number. 

Moveover, in GENIE, only a subset has fusion data. Maybe we can create a fusion case list and use that as the denominator? @n1zea144 

@schultzn thoughts?

**Comment by khzhu** [comment]
thanks, @jjgao ! agree. it might be a good idea to set gene panel aside and see if the new fusion api will resolve the issue Niki reported first.

**Comment by n1zea144** [comment]
It would be relatively easy for us to create a fusion case list for IMPACT samples.  Seems like a good way to restrict the mutation frequency to a pool of samples where fusion calls were attempted to be made.

**Comment by khzhu** [comment]
Hi @jjgao @zhx828 , here is my plan:
1. backend:
- [ ] modify existing myBatis query **getSampleCountInMultipleMolecularProfiles** and filter out fusions
- [ ] add a new myBatis query **getSampleCountInMultipleMolecularProfilesForFusion** to pull only Fusions out from the **_mutation_** table.
- [ ] add a new web service **_getSampleCountInMultipleMolecularProfilesForFusion_**
- [ ] add a new API endpoint **_/fusion-genes/fetch_**
2. frontend:
- [ ] add a new **_Fusion_** table without Frequency column in the study view

What do you think? Thanks!

**Comment by jjgao** [comment]
@n1zea144 it would be great if you can priotize that. The case list ID can probably be `[study_id]_fusion`.

@khzhu if the fusion case list exists, please use it (its overlapping samples with selected samples) as the denominator; otherwise, use all selected samples.

**Comment by khzhu** [comment]
@jj, will work on fusion case list with @n1zea144 . thanks!

**Comment by jjgao** [comment]
@khzhu I think you can assume _fusion case list may exist. Once @n1zea144 creates the case list, it'll work.

**Comment by khzhu** [comment]
@jjgao , okay, thanks!

**Comment by khzhu** [comment]
@jjgao @zhx828 , quick updates on this. I got backend part done, now working on the frontend, adding the new fusion table. 
Have a quick question: since we filter out fusions from muteded_genes, those fusions will not show up in the oncoprint is that okay?

**Comment by zhx828** [comment]
I think the decision is leave other pages unaffected, only filter out
fusions out of mutated genes table in study view.

**Comment by khzhu** [comment]
seems that query is used by oncoprint as well.

**Comment by khzhu** [comment]
@jjgao @zhx828 , I've completed all tasks as planned. Now, the **_Mutated Gene_**s table excludes all fusions (please see attached, the one on the left is the one excluding all fusions. I used [breast_msk_2018](https://www.cbioportal.org/study/summary?id=breast_msk_2018) dataset for testing), while new Fusion Genes table lists all fusions (please see attached). No other pages such as oncoprint are affected. 
I had problems to get the genie dataset imported to my local test database (downloaded data from genie site, but somehow the clinical data was not the up-to-date one). So, if the fusions were the root cause then this fixing should revolve the issue @schultzn reported.

![Screen Shot 2019-05-11 at 1 14 11 PM](https://user-images.githubusercontent.com/17375786/57572898-cd94c300-73ee-11e9-8f61-53c955aac9bf.png)

![Screen Shot 2019-05-11 at 12 59 51 PM](https://user-images.githubusercontent.com/17375786/57572772-2a8f7980-73ed-11e9-91f9-d1e77274ee72.png)
