### ISSUE TITLE
Incorrect mapping of RARA in Network tab

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#5650]
From a user:

I was playing around with PIK3CA mutations in Breast Cancer (MSK Cancer Cell, 2018). In the Network tab I looked at the RARA protein/gene that popped up, and under Details there was information (name and references etc.) linked to TP53 - not RARA.
I tried to do this again, and this time I can not even see RARA (it did not have a direct link to PIK3CA the first time). Even though it is listed in the Genes list. And when I click on it (in the Genes list) it first says there is no information (in red text) and after playing around a bit and trying to click it again, then it links me to AKT3 instead...

**Comment by ugurdogrusoz** [comment]
Steps to reproduce:
- Choose Breast Cancer (MSK, Cancer Cell 2018)
- Choose PIK3CA
- Open network tab, and locate RARA in genes list
- Double click on RARA to display its properties. No results since RARA and some other genes are not in the network view even though they are listed in this tab

**Comment by ugurdogrusoz** [comment]
This is not reproducible. I tried the above steps and things are fine as follows. By default RARA is not shown since not all interaction types are displayed initially. If you click Modify and Select All under Interactions tab, all genes including RARA are shown and when double-clicked on RARA, correct Details are displayed in the Details tab:
![rara-properties](https://user-images.githubusercontent.com/3874988/51743810-e7fc9800-20ae-11e9-8408-a139b1d3870c.png)
Maybe the confusion came from the fact that RARA is listed in the table under Genes tab but by default it's not in the network (since not all interactions are shown).

**Comment by schultzn** [comment]
I was able to reproduce it. I think I did a query for just RARA. RARA showed up in my query, but it was linked to an incorrect gene.

**Comment by ugurdogrusoz** [comment]
I tried the query with RARA: Breast Cancer (MSK, Cancer Cell 2018), RARA as only GoI, and it seems to work.
Can you perhaps list the exact steps to reproduce it and take a screenshot?

![image](https://user-images.githubusercontent.com/3874988/51745643-95be7580-20b4-11e9-960d-c27b312f19a1.png)

**Comment by schultzn** [comment]
Strange, but I can no longer reproduce the issue.
