### ISSUE TITLE
enrichments tab qvalue inconsistency

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5660]
We're upgrading an old version to the current version, and in doing so I was comparing the enrichments tab and noticed that the q-values are different in 2.0.1 than they were in 1.17.1. The p-values and all other numbers are identical, it is only the q-value that differs. In 1.17.1 the q-value calculation was done in the backend and in 2.0.1 it is done in the front end -- so this appears to be an issue relating to the change in the q-value calculation from the front end vs the back end.

1.17.1
![image](https://user-images.githubusercontent.com/10508276/51855973-83cf1380-22fc-11e9-85fb-d1d7be0fba0b.png)

2.0.1
![image](https://user-images.githubusercontent.com/10508276/51855961-7d409c00-22fc-11e9-96cc-130b1621c854.png)

**Comment by jjgao** [comment]
@tmazor I assume it's your internal data. Do you think it's OK to download the results in both cases and share it on Slack (#refactoring)?

**Comment by tmazor** [comment]
@jjgao yes this is internal data -- I will email you the enrichments tab table from both versions

**Comment by jjgao** [comment]
@tmazor thanks. @dippindots I've forwarded you the data. Please look into it. thanks.

**Comment by dippindots** [comment]
Thanks @tmazor and @jjgao. I am working on it.

**Comment by dippindots** [comment]
@ersinciftci Adam and I tried to reproduce this issue, but it turns out there is no problem with the q values calculation nor the columnFormater.

What I have tried: 
1. Using the p values data from Tali's data sets, and calculate by the calculateQValues function, results are correct.
2. Created the dummy data and use it to render the column, the results are still correct.

Could you help us to take a look at this issue? Since we can not debug directly with the internal data. If you need any info, please let me know. Thank you!

**Comment by tmazor** [comment]
I can point you to public data with the same problem.

In one of the tutorials slides is a screenshot of the enrichments tab from ~12/22/18. I ran the same query on the site today, and the data is identical except for the q-value column.

I'm having trouble pasting in images for some reason, so go to Tutorial #2, Slide #28 to see the old enrichments table: https://www.cbioportal.org/tutorials

Go here to see the same query on the current site: https://www.cbioportal.org/results/enrichments?session_id=5c1d2fc0e4b05228701f9a6e

Note that all q-values are different, including that ATRX changes from being un-significant to significant.

Again, the data is identical, but the q-values have changed. The old q-value calculations (in the back-end) and the new q-value calculations (in the front-end) are not the same. We need to figure out why they are different and which is correct.

@dippindots @adamabeshouse @jjgao

**Comment by adamabeshouse** [comment]
okay, I'm going to check it out shortly, but I'm almost certain the reason is that we're now filtering out the query genes from enrichments *after* computing the Q values, whereas it was previously the case that these genes were filtered on the server. I plugged it into an online calculator and the old results seem to be the correct ones. I'll confirm that filtering *before* computing Q values will fix it, and make a PR if so.

**Comment by adamabeshouse** [comment]
@tmazor @dippindots confirmed! please see my PR fixing it: https://github.com/cBioPortal/cbioportal-frontend/pull/2067

**Comment by tmazor** [comment]
Thanks @adamabeshouse !
