### ISSUE TITLE
Google+ sign in deprecated

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#5666]
We're using googleplus authentication method. This uses the spring.social.google library which uses the "Google+ Sign in" that's being deprecated: 
https://developers.google.com/+/integrations-shutdown
It seems the library itself won't be updated:
https://github.com/spring-social/spring-social-google/issues/115

Are there any plans to migrate to the new "Google Sign-In"? It's also an issue for GENIE, right?

**Comment by n1zea144** [comment]
HI @j-hudecek  We became aware of this yesterday.  AFAIK, we've been authenticated via OAuth2, not OAuth or any plus.me scope.  I did a quick cursory dive into spring-social-google code and this seems to be the case: [GoogleOAuth2Template.java](https://github.com/spring-social/spring-social-google/blob/master/src/main/java/org/springframework/social/google/connect/GoogleOAuth2Template.java).  Of course the shutdown of Google+ may still be an issue.  We are looking closer into the matter.

**Comment by jjgao** [comment]
closing. @j-hudecek please let us know if you have more information.

**Comment by PawelJagus** [comment]
For me it stopped working. Logging in with google seems to be impossible without changes to spring-social-google now.

**Comment by j-hudecek** [comment]
It seems some things (updating spring-social) will indeed need to be done on this, don't you want to keep the ticket open as a reminder?

**Comment by n1zea144** [comment]
Hi @PawelJagus I think something else may be affecting your environment as we are still running Google signon on a number of cBioPortal instances here at MSK.

**Comment by n1zea144** [comment]
Hi @j-hudecek We have it on our SCRUM backlog and will be addressing this issue soon.

**Comment by jjgao** [comment]
@j-hudecek sorry I jumped the gun -- was trying to reduce the number of tickets on github :) Reopening.

**Comment by PawelJagus** [comment]
> 
> 
> Hi @PawelJagus I think something else may be affecting your environment as we are still running Google signon on a number of cBioPortal instances here at MSK.

I have found out that I was using a prehistoric version of google social the one from here: https://mvnrepository.com/artifact/org.springframework.social/spring-social-google (1.0.0.RELEASE) while I should have been using the one mentioned in github, which is

```
<dependency>
  <groupId>com.github.spring-social</groupId>
  <artifactId>spring-social-google</artifactId>
  <version>${social.version}</version>
</dependency>
```

Upgrading worked for me with little effort. Signing in is still working.

**Comment by sheridancbio** [comment]
@jjgao @cBioPortal/msk-developers : 

@angelicaochoa and I have looked into the functioning of spring-social-google in the cBioPortal authorization process. The conclusion we come to is: our use of spring-social-google was *only* using the OAuth2Operations interface from spring-social-google ... the PlusOperations interface (also in spring-social-google) was not being used by cBioPortal for authentication or looking up of user details (in particular, their email address)

How we verfied this:
- first @n1zea144 turned off the plus api for the cBioPortal project through the google developer console api management screen. Portal functionality was not disrupted.
- we also created a fork of the spring-social-google codebase and removed all of the code which referenced the plusoperations interface, and all googleplus api endpoint references. See: https://github.com/cBioPortal/spring-social-google/tree/without-google-plus-calls ... then we built and deployed the cBioPortal using this reduced functionality library, and authentication still functioned correctly, including the proper determination of the user email after authentication.
- @angelicaochoa also modified our code for the GoogleplusConnectionFactory.java for the GoogleAuthenticationService so that it explicitly called the OAuth2Operations methods for retrieving user details (rather than using the indirect getApiAdapter().fetchUserProfile() method we previously were using). This resulted in the previous (successful) behavior.

So we conclude that in our current usage of spring-social-google, we are only using the OAuth2Operations facilities, and not using the PlusOperations. Tracing the security configuration for our "googleplus" authenticate setting (in portal.properties), we can tell that this is the case:
Beginning with the authenticationEntryPoint bean, a socialAuthenticationFilter bean controls authentication and is constructed using the usersConnectionRepository bean, which in turn is constructed with a connectionFactoryLocator bean (an instance of SocialAuthenticationServiceRegistry), which uses the cBioPortal class GoogleplusConnectionFactory (through a bean).

In our GoogleplusConnectionFactory code, we use getServiceProvider() which returns a ServiceProvider of type GoogleServiceProvider (a spring-social-google class), and the constructor for GoogleServiceProvider instantiates GoogleOAuth2Template, which extends OAuth2Template, which implements the OAuth2Operation interface and defines the string for retrieving user information from the oauth2 api endpoint : 
private static final String USERINFO_URL = "https://www.googleapis.com/oauth2/v2/userinfo";
GoogleServiceProvider holds a constructed and configured instance of GoogleAdaptor.
Our code (GoogleplusConnectionFactory) uses the method GoogleAdapter.fetchUserProfile() (implemented in spring-social-google) which explicitly uses OAuth2Operations for retrieving user info.

**Comment by n1zea144** [comment]
@angelicaochoa @sheridancbio Thank for the investigative work and detailed comment.  For completeness, we talked about replacing our use of the spring-social-google library for OAuth2 functionality with spring-security-oauth, but decided to revisit that topic when time permits.

@jjgao We consider this issue closed, but we'll leave it to you to do the actual closing.

**Comment by jjgao** [comment]
Thanks, @angelicaochoa @sheridancbio @jjgao ! Always feel good to close an issue :)
