### ISSUE TITLE
patient view stuck after clicking on View selected cases

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5681]
Open: http://www.cbioportal.org/study?id=msk_impact_2017
Click "View Selected Cases"

![image](https://user-images.githubusercontent.com/840895/52240069-fbbdb080-289d-11e9-865d-5311acf531c0.png)

Two issues:
- It takes long tome to load the patient view page
- Study view got stuck while patient view is loading

**Comment by alisman** [comment]
@jjgao @tmazor @schultzn the reason for this bug is that google analytics crashes when confronted with a url of >250,000 characters, which is what it takes to represent 10,000 samples in the url.   We can figure out a solution based on your response to the following.

Do we really need to allow users to navigate through >1000 patients?  Is that practical for the user?   If this is in fact important then there are ways to solve it, but they involve more work.  Simplest solution is just to truncate the list with the idea that it's highly unlikely anyways that a user would actually flip through more than a few hundred patients.

**Comment by schultzn** [comment]
Hmm… I am pretty sure some people might use this feature to line up all samples, then jump to the last one to see the most recently added samples (probably only applies to internal sequencing cohorts that are updated daily, like ours). As a solution for this very special case, maybe we could show the last 1000 selected samples?

But even if we do this, do we need to notify the user that not all selected samples were actually lined up? Is it enough to show a message in the tooltip, or will users miss that?

**Comment by jjgao** [comment]
@alisman Maybe we can use local storage for this when there are >n samples (n to be determined)? Users will not be able to send a link with navIDs to others but I think that's fine. For small urls, we will still include navIDs. @schultzn do you think that's ok?

**Comment by schultzn** [comment]
I think that would be ok.

**Comment by tmazor** [comment]
This seems reasonable to me

**Comment by debyani-chakravarty** [comment]
Hi this issue is on the public portal too -- just ran into it again.
