### ISSUE TITLE
support virtual study on heroku

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5693]
We need to support virtual study on heroku instances otherwise we cannot test features such as virtual study and custom group.

@alisman what's the reason what it's not working on heroku?

**Comment by alisman** [comment]
@jjgao @inodb 
If we continue to think this is really important, we try using https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials to enable login on heroku instances.  "Access-Control-Allow-Credentials" is setting of CORS which allows the browser to include cookies (JSESSIONID) when making cross domain requests (cookies associated with request domain instead of page domain).    So, one could log in on the ORIGINAL site, and then, I believe use that established session when using a heroku frontend.

**Comment by jjgao** [comment]
let's close this for now and see if it comes back again.
