### ISSUE TITLE
make the cn-segments tab responsive vertically

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5703]
... for both results and study view.

Or at least set the height based on initial window size.

**Comment by onursumer** [comment]
@jjgao making it responsive seems currently tricky, because with each window resize event the whole IGV component starts re-rendering and it may take some time depending on the size of the copy number data.

At this point, I think it is better to set the track height based on the initial window size.

**Comment by jjgao** [comment]
@onursumer that's fine.
