### ISSUE TITLE
CN segments tab should be hidden when no data is available

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5706]
This study has no copy number data yet the CN segments tab still appears: http://www.cbioportal.org/beta/study?id=lgg_ucsf_2014&tab=cnSegments

**Comment by onursumer** [comment]
Actually, even if there is data, depending on the active filters, we can still end up with no data. So, instead of hiding the tab, maybe we should just hide the IGV viewer and update the header line to "No segmented copy-number data for the selected xxx sample(s)". This would also be an enhancement for the issue #5678.

@tmazor @jjgao what do you think?

**Comment by jjgao** [comment]
@onursumer I think if there is no data in the studies at all, we should hide the tab. If no selected samples have segment data, then show "No copy number segment data available for the selected xxx sample(s)"

Maybe we can add another quick filter "w/ CN segment data"?
