### ISSUE TITLE
group comparison tweaks

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#5727]
study view group comparison manager:
- [x] newly-saved groups start out being selected
- [x] autogenerate simple names - collections of clinical attribute selections (in some canonical order based on chart id)

group comparison page
- [x] allow one group to be selected. just grey out tabs the same way we do when too many groups are selected.
- [x] only show selected groups in overlap tab
- [x] only show selected groups in survival tab
- [x] thoughts @jjgao @alisman? save filters into the group when creating it, so that when selecting the group on the study page we can actually select the specific filters, rather than making a general selection of the included samples?

refactoring
- [x] get rid of 'categoryToColor' - move that functionality to automatically assigning a color to the comparison group, and handle it right in Overlap and Survival

**Comment by adamabeshouse** [comment]
@jjgao @alisman thoughts on the idea I added above?

**Comment by jjgao** [comment]
> * save filters into the group when creating it, so that when selecting the group on the study page we can actually select the specific filters, rather than making a general selection of the included samples?

Good idea to save the filters into the group. It would be useful for updating the group later.

We will need to support OR (UNION) logic to the filter since we can incrementally add samples into a group. Could you discuss with @kalletlak and @zhx828 on that?

It may not be easy to use them for selection when a study is updated and the group is out of date...
