### ISSUE TITLE
SAML AssertionConsumerServiceURL

### ISSUE THREAD

**Issue by zisimo** [cBioPortal/cbioportal#5809]
I am trying to set up saml with cbioportal.

The connection works fine with http requests, the question is how to make it work with https though.
The AssertionConsumerServiceURL that is created in the assertion of cbioportal contains http, even if the initiator page had https. In other words, I am trying to get cbioportal to create 
AssertionConsumerServiceURL="https://cbioportal.weill.cornell.edu:80/cbioportal/saml/SSO"
instead of
AssertionConsumerServiceURL="http://cbioportal.weill.cornell.edu:80/cbioportal/saml/SSO"
when it makes the call to keycloak.

**Comment by jjgao** [comment]
@zisimo would you please email our support group: cbioportal@googlegroups.com?

**Comment by khzhu** [comment]
Hi @zisimo , in order to use **_https_**. you will have to set up a SSL for both your tomcat and the keycloak server. 
1. please follow this [article](https://tomcat.apache.org/tomcat-8.0-doc/ssl-howto.html) to set up a SSL for your tomcat server if you are using tomcat 8.  
2. Steps to set up a SSL for keycloak can be found [here](https://www.keycloak.org/docs/latest/server_installation/index.html#setting-up-https-ssl). 
3. once you are done step 1 & 2, you might need to update  the **_Master SAML Processing UR_** for your keycloak server if it is not automatically re-configured. 
4. next, please re-download the SAML metadata IDPSSODescriptor file and replace the one you had in your installation site. Please remember to update the **_saml.idp.metadata.entityid_** property in your portal.properties file and replace http URL with https.
5. finally, restart your portal if everything goes well and you should have a https. 
hope this helps.

**Comment by khzhu** [comment]
please note you can not use port 80 for https, port 443 is reserved for https.
