### ISSUE TITLE
long url is broken in public portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5836]
We recently switched to nginx when moving to aws and it looks like we have a limit on the url.

https://groups.google.com/d/msg/cbioportal/0dZ3Cm6-FH4/AuZX7LdwBwAJ
https://groups.google.com/d/msg/cbioportal/zEvkMQX5zcE/GnppOGhGBwAJ
https://groups.google.com/d/msg/cbioportal/2eiP2TiNy_E/1kInmbhzBwAJ
https://groups.google.com/forum/#!topic/cbioportal/Q4e3B9duxu0

**Comment by inodb** [comment]
@jjgao 	Long URL should be working now. It was actually at the tomcat level:

https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/cbioportal/cbioportal_spring_boot.yaml#L128-L129

Oddly enough it was working when port-forwarding the service instead of going through nginx. Which made it seem like the problem came from there. Maybe the extra headers nginx adds were pushing it over the limit in Tomcat. This error only shows up once in the tomcat logs, after that you need to run with DEBUG parameters to see it. It became clear once spinning up a new cluster from scratch

**Comment by jjgao** [comment]
Thanks, @inodb. Good detective work and great that we can spinning up a whole cluster for debugging.
