### ISSUE TITLE
study view - mutation count plot labels are cut-off

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5844]
x-axis labels are cut-off:
![untitled](https://user-images.githubusercontent.com/10508276/54040624-d3beb700-4193-11e9-8b2c-321bd19bfc85.png)

https://www.cbioportal.org/study?id=5c82931ee4b0d20a23998c75

**Comment by brettvanderwerff** [comment]
If no one is actively working on this, I can open a PR. I think the issue is in:

`cbioportal-frontend/src/pages/studyView/charts/barChart/BarChart.tsx`

There is not quite enough padding on charts with tilted ticks, but doubling that padding seems to look ok 

![l3Q1db6 - Imgur](https://user-images.githubusercontent.com/34728357/54332813-2b6a8180-45dd-11e9-974e-6982eb3be2b7.png)
:

I have used bioportal for a while as a researcher and have been watching the code base for a while, I hope I can help out.

**Comment by zhx828** [comment]
@brettvanderwerff thanks for looking into the issue. The margin is calculated base on the string length. I would check why in this particular case the length is not calculated as expected. Welcome to send a PR.

**Comment by brettvanderwerff** [comment]
@zhx828 OK, I see now it is not as easy as just adding extra padding. I will see if I can identify the root of the problem with that calculation and will open a PR if I have a solution. I think this project is great and would like to be of help. I am still getting familiar, so if time becomes an issue please let me know.

**Comment by brettvanderwerff** [comment]
@zhx828 I look into this quite a bit more and opened PR #2147 on the frontend repo to try and resolve it. Thank you.

**Comment by zhx828** [comment]
Thanks Brett. I will take a look.

**Comment by zhx828** [comment]
@brettvanderwerff I took a look the PR, it works but not fixing the actual issue. It's a bit more complicated but let me know if you still want to continue solving the issue.

Here are few nodes 
- the `10`px you pointed out is the reserved height for the tick under the axis, not the text, the small black vertical line. So when you increase to 20, it seems solve the issue, but that's not guaranteed for all studies
- The issue is the algorithm calculating the `bottomPadding`. In current implementation, it only calculates the height base on the text width, but it should be text diagonal length. Once you switch to diagonal, it works.
![IMG_0602](https://user-images.githubusercontent.com/5400599/54832243-2f0f9f80-4c92-11e9-87de-a4fa124b675b.jpg)
- Then I realize there is another issue(optional to solve together). The height and padding settings for VictoryChart is not inline. The height has the `10`px fixed height but padding does not. So this needs to be fixed.
- Another issue(optional): when the text is not tilted, we currently use the `20`px reserved height for the text but it's not ideal, it should be the actual text height. You can use the similar way of calculating text width, function name `getTextWidth`

Thanks for sending the PR, you are very close now. :) Welcome to portal dev team.

**Comment by brettvanderwerff** [comment]
@zhx828 That makes sense. I looked at `bottomPadding`, but honestly just wasn't able to see that at first pass. Yes I would like to continue on this issue. Thank for your patience and time.

**Comment by zhx828** [comment]
@tmazor this issue is solved in production.
