### ISSUE TITLE
simplified search: allow customize the study list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5850]
e.g. using instance-specific configuration.

Some feedback from steering meeting last Friday:

Both physical studies and virtual studies should be supported as the default studies.

For the public portal, it would be a good idea to create a TCGA PanCancer Atlas virtual study and use that for query, so that the study name and description can be properly displayed in the Results page. (currently, it's Combined Study)

**Comment by inodb** [comment]
@jjgao  there are a few ways to solve this:

1. We change the session service model to include a `name` in the data part for sessions of type `main_session` (https://github.com/cBioPortal/session-service#valid-type). Similar as we have for `virtual_study`

2. We could set the title in a property of quick search config. Say e.g. it will query study x+y+z. Then on query view we can display a diff name if all those studies are being queried (instead of the usual "combined study")

1. is prolly cleaner solution

**Comment by inodb** [comment]
Discussed with Hongxin - virtual studies are actually not private if u have the id. So as long as all studies in the session are public, one can access it. So instead will create a virtual study of TCGA pancan under cbioportal account. Then at some point we can show all virtual studies owned by cbioportal on the homepage.
