### ISSUE TITLE
Allow Separate Insertions and Deletions for Oncoprinter

### ISSUE THREAD

**Issue by DarioS** [cBioPortal/cbioportal#5921]
If the variant annotation has categories such as Inframe Insertion and Inframe Deletion, it would be nice to allow these to be separate categories instead of just `INFRAME`. Also, I'd like splice site variants to be able to be represented as a distinct category.

**Comment by jjgao** [comment]
@DarioS any reason you'd like to have inframe ins and del separate?

We are also considering separating out splice mutations https://github.com/cBioPortal/cbioportal/issues/5129

**Comment by DarioS** [comment]
The motivation for it is the user might be researching a disease which has already been characterised to have a particular variant (either insertion or deletion in a specific gene) in a number of samples, and it would be more precise if you could draw an oncoprint which specifically shows it's also an inframe insertion in your own data set rather than the less precise INFRAME designation to show agreeability with the older findings.

It's a good coincidence that the splice variants are being considered to be their own category. It would be a useful addition.

Another feature which the standard oncoprint has is being able to plot vectors of clinical variables alongside the mutations. Could Oncoprinter allow more than four columns as input, so that varibles such as age and smoking status could be in the plot?

**Comment by jjgao** [comment]
@DarioS I am still not convinced that we should separate inframe insertions and deletions, considering that we treat nonsense and frameshift the same.

One possibility is giving the option to show different colors for all different types of mutations: missense, inframe ins, inframe del, frameshift ins, frameshift del, nonsense, nonstart, splice site, (and maybe a couple of more). The issue is that we would be running out of colors.

I added another issue for adding clinical data to oncoprinter: https://github.com/cBioPortal/cbioportal/issues/5941

**Comment by DarioS** [comment]
I suppose that simplicity is best for the plot. It could be hard to interpret with many colours.
