### ISSUE TITLE
What happened to MIR21?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#5960]
From https://groups.google.com/forum/#!msg/cbioportal/mn_f0x1wqFQ/KaT86eMgCAAJ 

Apparently MIR21 was present in a previous version of the data and had higher alteration frequency (6%): 

![image](https://user-images.githubusercontent.com/2900303/56025063-a5437700-5d11-11e9-9b62-3134b61fdc06.png)

When I query the MIR21 gene in the current version, the portal will present me with 2 options (apparently MIR21 is now a synonym for 2 different genes). See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/56025233-feaba600-5d11-11e9-90d9-5579215fb706.png)

Adding both to my query gives **very different results when compared to previous analysis**:

![image](https://user-images.githubusercontent.com/2900303/56025329-374b7f80-5d12-11e9-8d76-870710d2baf4.png)

Query URL: https://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acbc_mskcc_2015%2Cbrca_metabric%2Cbreast_msk_2018%2Cbfn_duke_nus_2015%2Cbrca_bccrc%2Cbrca_broad%2Cbrca_sanger%2Cbrca_tcga_pub2015%2Cbrca_tcga_pub%2Cbrca_tcga_pan_can_atlas_2018%2Cbrca_tcga%2Cbrca_bccrc_xenograft_2014%2Cbrca_igr_2015%2Cbrca_mbcproject_wagle_2017&case_set_id=all&clinicallist=CANCER_STUDY%2CNUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_COPY_NUMBER_ALTERATION%2CPROFILED_IN_MUTATION_EXTENDED&data_priority=0&gene_list=MIR-21%252F21*%250AMIR-21%252F21&geneset_list=%20&show_samples=false&tab_index=tab_visualize

**Comment by pieterlukasse** [comment]
notify: @jjgao @ritikakundra

**Comment by jjgao** [comment]
We remapped all miRNA symbols. @yichaoS could you respond to the user by email?

**Comment by pieterlukasse** [comment]
hi @jjgao, @yichaoS : I couldn't find a reply in the email thread. Can we please still do this before closing the issue?

**Comment by yichaoS** [comment]
@jjgao @pieterlukasse
(I'm replying the google group email w/ this msg below as well, closing the issue here)

We recently remapped all miRNAs in our database to their correct precursor/mature forms, based on mirbase.org. 

In expression profiles, mature form-ed symbol is now used instead, and in CNA, precursor form-ed symbols are used. If only the simplified symbols are provided in the original expression/CNA data, the values will be duplicated and different mature/precursor forms will be assigned, when importing the dataset into portal. 

Therefore, MIR21 here in original expression profile is mapped to 2 different of its mature forms MIR21 and MIR21* (please find details on this webpage: http://www.mirbase.org/cgi-bin/mirna_entry.pl?acc=hsa-mir-21), and the values are duplicated. 

We are not sure at the moment by the expression level dropped in the previous query, but when I check back with the query URL @pieterlukasse provided, the expression level is remained at 6% (see screenshot below)

![Screen Shot 2019-05-15 at 3 53 03 PM](https://user-images.githubusercontent.com/5973438/57804816-8f1e4180-7729-11e9-9356-65b96977f49b.png)

**Comment by pieterlukasse** [comment]
Thanks @yichaoS!
