### ISSUE TITLE
No case lists available for all brca_tcga

### ISSUE THREAD

**Issue by rdistefano** [cBioPortal/cbioportal#6047]
It seems there are no cases available for all brca_tcga*

```
> mycgds = CGDS("https://www.cbioportal.org/")
> 
> test(mycgds)
getCancerStudies...  OK
getCaseLists (1/2) ...  OK
getCaseLists (2/2) ...  OK
getGeneticProfiles (1/2) ...  OK
getGeneticProfiles (2/2) ...  OK
getClinicalData (1/1) ...  OK
getProfileData (1/6) ...  OK
getProfileData (2/6) ...  OK
getProfileData (3/6) ...  OK
getProfileData (4/6) ...  OK
getProfileData (5/6) ...  OK
getProfileData (6/6) ...  OK
> 
> # Get list of cancer studies at server
> mycancerstudies = getCancerStudies(mycgds)
> 
> # Get available case lists (collection of samples) for a given cancer study
> mycancerstudy = getCancerStudies(mycgds)[38,1] # brca_tcga: Breast Invasive Carcinoma (TCGA, Provisional)
> mycaseslist = getCaseLists(mycgds,mycancerstudy)
> mycaseslist
[1] Error...No.case.lists.available.for...brca_tcga_pan_can_atlas_2018.
<0 rows> (or 0-length row.names)
```

**Comment by jjgao** [comment]
it's confirmed: https://www.cbioportal.org/webservice.do?cmd=getCaseLists&cancer_study_id=brca_tcga

@n1zea144 @ritikakundra @yichaoS could you look into this?

**Comment by ritikakundra** [comment]
@jj Not sure of the issue. @rmadupuri confirmed that all caselists for this study were added in datahub as well as reimported to public portal

**Comment by yichaoS** [comment]
@jjgao The data itself and the data in the database are both fine I believe. Because:  
1) The same API works for the private portal (https://cbioportal.mskcc.org/webservice.do?cmd=getCaseLists&cancer_study_id=brca_tcga). I doubled checked both the private and public database, the case lists there for brca_tcga are identical. 
2) The newer version of our API also works fine for this study on both private and public: curl -X GET `https://www.cbioportal.org/api/studies/BRCA_TCGA/sample-lists?projection=SUMMARY&pageSize=10000000&pageNumber=0&direction=ASC`

The code version for these two portals are slightly different (2.2.0-4 vs. 2.2.0-6) but shouldn’t affected this matter.

My main suspicion is there's some bug in webservice.do

**Comment by inodb** [comment]
This is fixed (the portal wasn't restarted after data import)

**Comment by jjgao** [comment]
@yichaoS: curious what was the issue?

**Comment by inodb** [comment]
@jjgao it was b/c the aws tomcat wasn't being restarted after study import

**Comment by jjgao** [comment]
@inodb got it. Thanks! I assume now we have fixed the process.

**Comment by inodb** [comment]
@sheridancbio @n1zea144 do u know if this is the case? The restart script gets executed after import now?
