### ISSUE TITLE
group comparison: user-defined genes allows OQL but ignores it

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6154]
If I enter my own list of genes on the mutations or CNA tab, the input box allows OQL, but the tab ignores it.

We need to either respect the OQL, or not allow it to be entered in the gene box, or notice when it is entered in the gene box and add a warning to the page saying that OQL is ignored.

For this first release, I'm fine with whichever of those options is easiest to implement, and we can discuss how practical option 1 is at a later date (since I feel confident in assuming that won't be the easiest choice to implement).

**Comment by alisman** [comment]
@jjgao i think you had the idea that we should actually be able to respect the oql.  shall we put this in for 3.1.0?

**Comment by jjgao** [comment]
@alisman it's very hard to fully respect OQL. You would have to do it in the backend and we don't have backend OQL anymore.

For Mutations, we should only stick to genes. 

For CNAs, OQL was added to fix #6142 so that we can order AMP and DEL separately. Is it poissible to support AMP and DEL only? Or maybe we should just show the more frequent event per gene?

**Comment by kalletlak** [comment]
@jjgao currently it supports `AMP` and `HOMDEL`

**Comment by jjgao** [comment]
@kalletlak let's show some warning when OQL is used in Mutations tab or OQL except AMP and DEL is used in Copy-Number tab.
