### ISSUE TITLE
GA: track specific tabs instead of /results

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6216]
currently, it's still tracking /results after submission. Can we change that?

**Comment by alisman** [comment]
Correct me if I'm wrong but I think the only new data we would obtain from this is whether we went to oncoprint or cancer type summary as default.   I believe I would need to determine this in the query selector prior to submission so that I could choose the route at that point.   I don't remember quite why but this proved problematic.  I can look into it again. 

Doing this would also mask the difference between initial load of the results view and subsequent tab clicks (which are treated as page views).

**Comment by jjgao** [comment]
One piece of new information is the exact number of visits to each tab.

Some other information that could be useful:
- number of results sessions (newly created or load from old sessions)
- number of newly created sessions
- number of old sessions

Would it be possible to fire the GA event after the page is fully loaded so it can get the redirected url?
