### ISSUE TITLE
upset tooltip extends off screen

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6220]
![image](https://user-images.githubusercontent.com/10508276/58907151-80e59480-86db-11e9-8499-f9322c1be710.png)

https://beta.cbioportal.org/comparison?sessionId=5cf6aa24e4b0ab4137874305

**Comment by alisman** [comment]
@kalletlak would be great if we could use same solution as you came up with for bar chart

**Comment by adamabeshouse** [comment]
@alisman I think the problem here is different - its not that the tooltip is bounded by its container, its that the tooltip is going offscreen. what we need is to flip its orientation. i was in the middle of trying as i couldnt figure out how to position the popover relative to its top right corner instead of its top left corner - changing its placement prop only changes the way its displayed ie with the arrow on the right side of the bubble

**Comment by kalletlak** [comment]
@adamabeshouse  we have the same issue even with gene bar plot. and @alisman suggested to flip the orientation.
