### ISSUE TITLE
group comparison: comparisons from histograms

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#6223]
If I click "vs" for a histogram, I expected that the groups in the group comparison would be based on the bins in the histogram.

So for MSK-IMPACT Mutation Count, I expected groups of samples that had <=1 mutation, 2 mutations, 3 mutations, etc:
![image](https://user-images.githubusercontent.com/10508276/58908655-1fbfc000-86df-11e9-8afb-2fdd4a9cda54.png)

Instead I get 4 groups that are defined in a way I cannot define:
![image](https://user-images.githubusercontent.com/10508276/58908692-382fda80-86df-11e9-8910-aafba68f7c14.png)
https://beta.cbioportal.org/comparison?sessionId=5ce84920e4b0ab413787411b

How are these groups defined? Can we base it more closely on the bins in the histogram?

**Comment by adamabeshouse** [comment]
we discussed this before. I think we had decided that in order to do this properly we'd need to update the API to be able to return the bin contents, that we didn't want to redo the slightly complicated bin computation on the frontend.

as-is, the groups are quartiles. maybe we can make that clearer in the group names?

**Comment by adamabeshouse** [comment]
temporary fix until 3.1 https://github.com/cBioPortal/cbioportal-frontend/pull/2414

**Comment by jjgao** [comment]
@adamabeshouse I am wondering why the sizes of the groups are so different if they are quartiles?

![image](https://user-images.githubusercontent.com/840895/58985465-5c57ee00-87a9-11e9-8f8f-cb08a77a6dea.png)

**Comment by adamabeshouse** [comment]
@jjgao ah okay so that's because we do the quartile splitting based on distinct values. so even if there are 10000 samples with 30 mutations, for the quartile calculation we're only considering 30 once. maybe not the best way to do it. But if we don't do it like that then different samples with the same value will fall into different bins.


also I just realized we have a bit of an issue with these quartile groups because the groups are sorted alphabetically. Ill fix that

**Comment by schultzn** [comment]
I think actual quartiles would be better. So in this example, the 25% of samples with the highest mutation number should be in the first quartile, and so on. Can you do that?

**Comment by adamabeshouse** [comment]
I'll paste my reasoning from slack:

```i think thats actually the desirable way to do it. the most important thing is to split the data into groups according to value, you're really measuring the effect of the value variable on various other variables like enrichment (edited) 
the group size itself is controlled for in all the tests (edited) 
so i think this is the right way to do it``

I'm curious if/why you disagree?

**Comment by jjgao** [comment]
@adamabeshouse We can probably write a paper to compare the two methods. Your way of calculating quartiles based on unique values had never occurred to me (and I hadn't seen this way in other places). Do you have a reference for that?

**Comment by schultzn** [comment]
I was thinking in terms of quartiles of populations. The top quartile has 25% of the population in it, and each quartile should have the same number of subjects. I think that is the right way to do this for a continuous value.

**Comment by jjgao** [comment]
future improvement logged https://github.com/cBioPortal/cbioportal/issues/6252
