### ISSUE TITLE
Deprecated DB seed docs for PDB and drug targeting

### ISSUE THREAD

**Issue by brainstorm** [cBioPortal/cbioportal#6280]
@inodb Since you seem to be updating the docs lately, would you mind helping me out with a couple of cbioportal db seeding doc issues? ;)

I'm working from `master`, so presumably close to version`3.0.1` at the time of writing this and putting together an AWS Aurora RDS serverless install of cbio-db, later on Fargate for the web container. I'm happy to see that the docker work by the Hyve was adopted as part of the main cbioportal repo :)

I'm just following the [DB seeding docs step by step](https://docs.cbioportal.org/2.1-deployment/import-the-seed-database) for now, finding the typical scientific software deployment hiccups, namely:

**Point 3 of:** [importing the cbioportal-seed-database](https://docs.cbioportal.org/2.1-deployment/import-the-seed-database#import-the-cbioportal-seed-database).

After importing the main seed successfully (`seed-cbioportal_hg19_v2.7.3.sql`), I cannot find the PDB part of the seed database (`seed-cbioportal_hg19_vX.Y.Z_only-pdb.sql`). There's a succint mention on the datahub that the protein info was removed ["cBioPortal 1.9.0 with database schema 2.4.0 removed PDB annotations from the database."](https://github.com/cBioPortal/datahub/tree/master/seedDB)... Or perhaps current versions of that seed db already contain uniprot data but the docs were not updated? 😕 I need some clarity here :-S

The other issue is the [drug-target-data](https://docs.cbioportal.org/2.1-deployment/import-the-seed-database#drug-target-data) db where the docs mention that:

> "(...) importPiHelperData.sh which is distributed as part of cBioPortal"

but in reality:

```bash
root@ip-172-31-20-212:/mnt/cbioportal# find . -iname "importPiHelperData.sh"
root@ip-172-31-20-212:/mnt/cbioportal#
```

**Comment by inodb** [comment]
Hey @brainstorm ! Glad to see you're using cBioPortal as well 😄 ! 

Sorry the documentation isn't up to par. I sent a PR to address your issues:

https://github.com/cBioPortal/cbioportal/pull/6281

To answer your questions:

1. That PDB step has been removed. This is now all contained in a separate web service called genome nexus (https://www.genomenexus.org, https://github.com/genome-nexus/genome-nexus)
2. The drug target data is no longer shown on the website. We are mostly using OncoKB to indicate targetability (https://www.oncokb.org, https://github.com/oncokb/oncokb)

Also just realized we're missing a description in the architecture overview of those external services: https://github.com/cBioPortal/cbioportal/blob/3e7ebff5f710dd83d72504bde52e44f09b1a7dbc/docs/Architecture-Overview.md. Filed an issue for that: https://github.com/cBioPortal/cbioportal/issues/6282

Hope that helps!

I'm curious to hear how your experience with AWS Aurora RDS will pan out. We're currently using AWS RDS for MySQL. We also provide Kubernetes config here of our production instance: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment. Not sure if it's useful for your use case, but just FYI

**Comment by brainstorm** [comment]
Thanks a ton Ino! Since I read the kubernetes definitions, we are currently holding it off a bit since we're not sure a fully serverless approach (as in [Aurora Serverless](https://aws.amazon.com/rds/aurora/serverless/) plus [Fargate](https://aws.amazon.com/fargate/)) would be something you guys would support/maintain in the future if we put effort into it?

We are interested in a fully managed and serverless way to deploy cBio without the Kubernetes admin overhead and continuous running costs, if that makes sense.

You seem to be fairly invested in Kubernetes (AWS EKS?) so we will re-evaluate depending on feedback/resources... in any case, thanks again for your super-fast help and feedback! :)

/cc @MrsLaviniaG @ohofmann

**Comment by inodb** [comment]
@brainstorm My pleasure!

We don't have much experience with serverless on our end. We moved our internal public version of cBioPortal (www.cbioportal.org) recently from internal hardware to kubernetes on AWS. We used kops to deploy a k8s cluster on AWS, EKS wasn't available then (https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/tree/master/kops). Uptime is much better now. A major factor of this is that monitoring through prometheus + grafana and logging w loggly makes finding performance issues a lot easier. Having multiple replicas and auto restart through k8s is very helpful as well. We chose k8s for a variety of reasons, one was that we didn't want to lock into Amazon. Another goal was to be more transparent about our internal deployment infrastructure, such that we could collaborate on that in an open source manner.

That being said. I would be curious to see if a serverless setup would be more performant / cheaper. I imagine for portal instances that don't receive a lot of traffic it will def be cheaper. Since we'd like to see everybody be able to run cBioPortal, supporting that use case would already be worthwhile. Also for ourselves to e.g. have the option to spin up cheap dev instances.

If you have some experience with moving apps to a serverless infrastructure, maybe you can elaborate a bit on the type of issues that come up? I'm wondering what it would entail to implement and support/maintain such a deployment

**Comment by inodb** [comment]
Closing this b/c it seems these particular docs issues related to pdb and drug targeting have been solved. Please re-open if not

@brainstorm Happy new year! If you're still interested in looking at a serverless deployment let me know and we can open a separate issue for it. Happy to do a call to hash that out a bit. These docs give an overview of the various services that cBioPortal consists of: https://docs.cbioportal.org/2.1-deployment/architecture-overview
