### ISSUE TITLE
not all url parameters saved in the Share link

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6297]
![image](https://user-images.githubusercontent.com/840895/59862417-bed7ef00-9350-11e9-922a-c262202ab89a.png)

When bookmarking query, only the initial query parameters are saved in the session. For example when saving [this query](https://www.cbioportal.org/results/oncoprint?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&show_samples=false&clinicallist=MSI_STATUS), the clinical track (clinicallist url parameter) gets lost in the saved session: https://www.cbioportal.org/results/oncoprint?session_id=5d0ba965e4b0ab4137876b4d. We should save the new parameters in the link. There are two options.

1) Save the full url into the session. When the url changes, a new session should be created when the link icon is clicked.
2) Only save the core query parameters like we do now, but include the new parameters in the Share link url, e.g. https://www.cbioportal.org/results/oncoprint?session_id=5d0ba965e4b0ab4137876b4d&clinicallist=MSI_STATUS. (the bitly link should be regenerated in either case)

I am leaning towards 1). @alisman thoughts?

**Comment by alisman** [comment]
There's a lot of layers here.  
First, we actually DO save the clinicallist setting into the session.  The problem is, it's not being READ from the retrieved session.  I think it's just looking for param in url.  
But if we were to fix this, it would cause another strange situation where if user updated clinicallist (using dropdown), the they would have both a url param AND the parameter from session.   So who would win?  Seems like the url should win, right?

**Comment by adamabeshouse** [comment]
oh jeez

**Comment by jjgao** [comment]
Ah, got it - that makes sense. I think URL should win.

**Comment by alisman** [comment]
@adamabeshouse lets meet to chat about this one
