### ISSUE TITLE
network tab does not load on mskcc portal?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6379]
Keeps showing loading icon:

https://cbioportal.mskcc.org/results/network?session_id=5d2795a1e4b0ab413787ae17

**Comment by alisman** [comment]
@n1zea144 @sheridancbio this is security issue which appears to be specific to network.do endpoint.  network.do is trying to redirect to login page.
![image](https://user-images.githubusercontent.com/186521/61134892-92fee380-a48e-11e9-9b8d-25cc32b62b96.png)

**Comment by n1zea144** [comment]
Hi @alisman I made a change to allow all requests through to network.do (like we do for case.do and patient.do).  Further progress is made, but there is still an error loading the page.  I see the following in the browser debugger:

![image](https://user-images.githubusercontent.com/366003/61304062-8fcd6580-a7b6-11e9-8528-03fef9466322.png)

Is this due to an erroneous response from the backend (its always hard to debug the MSK production server backend).

**Comment by n1zea144** [comment]
@jjgao @alisman Here is the fix (I've deployed to MSK portal already):

[PR-6396](https://github.com/cBioPortal/cbioportal/pull/6396)
