### ISSUE TITLE
tweaks the limit of number of query genes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6384]
A recurrent question in our support group is how to query for more than 100 genes. We have discussed in the steering meeting and are thinking of relaxing it a little, e.g. we can support a query if

- it has 100 or fewer genes (the current criterion)

or 

- genes x samples are 1 million (TBD) or fewer.

@cBioPortal/product @alisman @inodb

**Comment by jjgao** [comment]
@inodb if you will do the analysis of the current email requests for >100 genes, may add them to this thread. thanks

**Comment by inodb** [comment]
@jjgao 	

i did a search for gene limit and found that the majority is roughly one of these cases:

1. Potentially legitimate 100-1000 range queries. But not clear always why they need it.
2. Comparing expression of large gene sets
3. They want all the data

(1) can be addressed by the newly proposed limit

Maybe for (2) and (3) we can have some configurable message that points people to the data sets or datahub page when they try to query a large number of genes. I think it makes sense to show that message whether or not we can display them on the results page. It should just be shown when querying a large number of genes.

I also think people don't know they can use the study view page to only query the e.g. top x recurrently mutated genes. So that might be some link to a FAQ or something.

Another idea for (2) - maybe this should be addressed with gene sets queries? We could maybe mention this in the FAQ as well e.g. if you're trying to query a lot of genes for expression analysis it might be better to download the data.

**Comment by jjgao** [comment]
> I think it makes sense to show that message whether or not we can display them on the results page. It should just be shown when querying a large number of genes.

+1

> I also think people don't know they can use the study view page to only query the e.g. top x recurrently mutated genes. So that might be some link to a FAQ or something.

Aaron's forked button might bring more awareness of study view.

> Another idea for (2) - maybe this should be addressed with gene sets queries? We could maybe mention this in the FAQ as well e.g. if you're trying to query a lot of genes for expression analysis it might be better to download the data.

I think it's a good idea to mention that. It's also problematic to use oncoprint to derive binary conclusions about expression data as discussed in #5528.
