### ISSUE TITLE
overlapping not highlighted

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6404]
Esophageal Carcinoma (TCGA, Nature 2017) overlaps with both Esophageal and Stomach studies, but the overlapping is not highlighted.

![image](https://user-images.githubusercontent.com/840895/61505913-7989fa00-a9ae-11e9-83e1-da2b8c401243.png)

**Comment by alisman** [comment]
@jjgao right now we determine overlap purely based on study name.   That study name is not related any of the studies you cite (e.g. stes_tcga_pub vs. esca_tcga) and that's why it's not highlighted here.   I think we've concluded that the only robust solution to this issue is precalculated overlap pairs delivered in meta data.   Lets open an new ticket for a project of that nature.
