### ISSUE TITLE
Mobx issue awaiting the promised returned by function

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#6465]
If you look at @khzhu  [PR](https://github.com/cBioPortal/cbioportal-frontend/pull/2180) , there's a function makeEnrichmentDataPromise in resultsViewPagetStoreUtils which makes use of hugoGeneSymbolToReferenceGene.  (This is new code introduced by PR).  This would seem to require that we add hugoGeneSymbolToReferenceGene to the await collection of the remoteData which the function is returning. But when I do that, I get a mobx error and app crashes.  Question is why that happens.  I tracked it down to the refenceGenes promise of the resultsViewStore.  It awaits:
 [this.studies,
 this.mutationEnrichmentData,
 this.copyNumberAmpEnrichmentData,
this.genes]
The problem seems to arise from the middle two.  If I remove both of them, the errors goes away. Obviously code fails for other reasons, but these seem to be source of the mobx error.  Or rather it crashes when this promise is itself awaited.

**Comment by adamabeshouse** [comment]
makeEnrichmentDataPromise depends on hugoGeneSymbolToReferenceGene
which depends on referenceGenes
which depends on mutationEnrichmentData
which is a makeEnrichmentDataPromise, thus depends on hugoGeneSymbolToReferenceGene

**Comment by khzhu** [comment]
followed Adam proposal and got the issue resolved. Huge thanks to @alisman and @adamabeshouse!
> since referenceGenes uses enrichment data, 
and our final enrichment data uses referenceGenes, we had to break this codependence apart
thus we have _mutation...WithoutCytoband, which does all the enrichment data stuff, but doesnt add cytoband
i.e., doesnt need referenceGenes
now referenceGenes can safely depend on that
finally, mutationEnrichmentData can use referenceGenes
so instead of referenceGenes->mutationEnrichmentData->referenceGenes
we have mutationEnrichmentData->referenceGenes->_mutationEnrichmentDataWithoutCytoband
and mutationEnrichmentData->_mutationEnrichmentDataWithoutCytoband
where -> denotes dependence
so now there is no circular dependency, and it should work
