### ISSUE TITLE
look at tests failing in frontend release-3.1.0

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6476]

**Comment by adamabeshouse** [comment]
looks like the group comparison enrichments tests are failing because cytoband no longer appears. not sure if this is due to API change relating to @khzhu 's changes for varying reference genes

**Comment by adamabeshouse** [comment]
the oncoprint tests are failing because the gene panel API is returning null responses

**Comment by khzhu** [comment]
@adamabeshouse , I will take a look at it as well.

**Comment by jjgao** [comment]
@adamabeshouse Thanks. Maybe create separate issues for them? I think we can ask @n1zea144's team to look at the second one. Please slack them.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/issues/6480
https://github.com/cBioPortal/cbioportal/issues/6479

**Comment by leexgh** [comment]
the mutation table tests are failing because the mutation structure was changed (see https://github.com/cBioPortal/cbioportal/pull/5891 and https://github.com/pughlab/cbioportal/blob/a46a54aa4873979ce7ae9170e2b68fcbfad09bd9/model/src/main/java/org/cbioportal/model/Mutation.java#L17). 
See quick fix here - https://github.com/cBioPortal/cbioportal-frontend/pull/2587
But we need to update the cBioPortal API first

**Comment by adamabeshouse** [comment]
looks like we're down to around 3 failing tests!
