### ISSUE TITLE
Treatments feature UI improvement ideas

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6528]
Some suggestions that would make the treatments feature less confusing:

- [x] 1 - remove numbers from drug names.
- [x] 2 - after selecting a drug, show the actual drug name in the breadcrumb list
- [ ] 3 - but why do we have the breadcrumbs anyway? Why not follow the model we have for gene symbols? We seem to already allow users to type in drug names. 
- [x] 4 - the descriptions of the available categories for CCLE need to be improved
- [ ] 5 - Can we find a more descriptive name for the heatmap button? How is anybody ever going to find that we have treatment data here? Can the name change based on data availability? But that might be too complicated - captured in #6570

![image](https://user-images.githubusercontent.com/11892704/63562022-126de100-c52a-11e9-9cd0-3d6c7eceef0f.png)

![image](https://user-images.githubusercontent.com/11892704/63562057-34676380-c52a-11e9-9eff-a3cb5507a93a.png)

**Comment by pvannierop** [comment]
@schultzn Thank you for your report. I will go through your points below.

>1 - remove numbers from drug names.
>2 - after selecting a drug, show the actual drug name in the breadcrumb list
>4 - the descriptions of the available categories for CCLE need to be improved
This is determined by the study data, not the frontend feature. I am currently working with Sander and Navetika to correct this. We will update the numbers to reflect the treatment names. In addition, the profile categories will be renamed.

>3 - but why do we have the breadcrumbs anyway? Why not follow the model we have for gene symbols? We seem to already allow users to type in drug names.
The reason for this is are:
1) different form genes, names of treatments may differ between studies and we have to assume that these are not known to the user by heart. A simple text field for typing names is not sufficient since the user in some form needs feedback on what are recognized treatment names (hence the selection menu). Because of the combination of the text area and the selection menu a separate element (the breadcrumbs) to present the currently selected treatments seemed more appropriate.
2) the breadcrumb method of showing selected treatments has the additional benefit of clearing up the text area when a name has been recognized. This makes identification and correction of wrong id's by the user more convenient.
3) The gene name recognition/feedback was introduced in the heatmap menu at the same time as the treatment selection menu. @adamabeshouse and me decided to possibly harmonize these methods in the future.

>5 - Can we find a more descriptive name for the heatmap button? How is anybody ever going to find that we have treatment data here? Can the name change based on data availability? But that might be too complicated.
This is a valid point that I feel that goes a bit beyond the scope of this feature. The user also needs to learn that gene expression data is added using this menu rather than _mRNA_ or _protein expression_ being a term in the menu button. If you want we can make separate issue of this to discuss this further and design an improvement in a release update?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao @schultzn can we clean this up? I think most of this was resolved. For the bits that are not we should create new issues.

**Comment by jjgao** [comment]
1, 2, & 4 are done. 5 is captured in #6570. Let's focused the discussion on 3 here.

@pvannierop I think @schultzn is suggesting that maybe we don't need the breadcrumbs and just add the drugs in the text box directly... @schultzn is that right?
