### ISSUE TITLE
Treatments feature - gradient issues

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6529]
The sort by IC50 feature does not seem to work.. see screenshot below.
Also, the color gradient in the example below seems to be completely distorted by maybe a data outlier?

https://beta.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=mixed_broad_ccle_2018&case_set_id=mixed_broad_ccle_2018_cnaseq&data_priority=0&gene_list=BRAF&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=mixed_broad_ccle_2018_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mixed_broad_ccle_2018_mutations&show_samples=false&tab_index=tab_visualize&heatmap_track_groups=mixed_broad_ccle_2018_CCLE_drug_treatment_IC50%2C1373&treatment_list=1373

![image](https://user-images.githubusercontent.com/11892704/63562317-2cf48a00-c52b-11e9-9cd9-d34e46a36c61.png)

**Comment by pvannierop** [comment]
@schultzn You are right. I will look into this behavior.

**Comment by pvannierop** [comment]
@schultzn @inodb I fixed the oncoprint sort (see screenshot below). This is fixed in [cbioportal-frontend PR #2637](https://github.com/cBioPortal/cbioportal-frontend/pull/2637). I confirm that value 869.23 is indeed an outlier.
![fixed_oncoprint_sort](https://user-images.githubusercontent.com/745885/63754704-9e2e9700-c8b5-11e9-9f78-3a146ec4ba04.png)

**Comment by pvannierop** [comment]
P has been merged. Discussion on styling of treatment response heatmap tracks is continuing in #6569. I am closing this issue.
