### ISSUE TITLE
Treatment waterfall plot: change style slightly

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6532]
The waterfall plot seems a little taller than necessary - can it be a little shorter so that the plot plus legend fit on a 13" screen.

Also the y-axis should start at 0 and end at 1 - currently it extends below and above.

![image](https://user-images.githubusercontent.com/11892704/63563932-ee61ce00-c530-11e9-9daf-572f9cfee290.png)

**Comment by pvannierop** [comment]
@schultzn I will update the y-axis. Due to the nature of the plot we cannot control the size of the plot in the horizontal dimension; it depends on the number of samples presented. I will tweak the layout of the plot so that the legend will be presented below the plot when the plot is wider than a 13' screen.

**Comment by schultzn** [comment]
I am not concerned about the width of the plot. I think it is too tall - and the legend is always pushed “below the fold”. The plot would look much better anyway if it were less tall.

**Comment by pvannierop** [comment]
@schultzn @inodb I have tidied up the layout of the waterfall plot in the y-dimension. I removed the padding from on the y-axis and reduced the overall height. I also moved the legend more to the right so that keeps right of the y-axis (see screenshots below). I looked for options to move the gene selection menu on view on a small screen, but this is rather hard to do when we do not want to change the look of the menu on other plots (that are smaller).

# Before
![old_waterfall_layout](https://user-images.githubusercontent.com/745885/63696272-a1c11000-c81a-11e9-91c7-48fcbb5e2feb.png)

# After
![new_waterfall_layout](https://user-images.githubusercontent.com/745885/63696280-a685c400-c81a-11e9-8098-2821b69e4daf.png)

**Comment by schultzn** [comment]
I think that is fine… I am not concerned about the width, more the height. Even your new version seems a little too tall. 

And what about the “Style samples by” menu - should that be left-justified so that it is always visible?

**Comment by pvannierop** [comment]
> Even your new version seems a little too tall.

I have further reduced the y-dimension. But please notice that many other plottypes are much larger in y-dimension than the waterfall plot (see screenshots below). 
![smaller_y](https://user-images.githubusercontent.com/745885/63701699-b656d580-c825-11e9-906f-b409a15d29a0.png)

>And what about the “Style samples by” menu - should that be left-justified so that it is always visible?

It would easy to pin this menu to a fixed offset right next to the axis-menu (left justified). However, at the moment the “Style samples by” menu floats to the middle of the graph container element. This is visually attractive since the menu nicely pairs with graph showing up in the middle. It would easy to pin this menu to a fixed offset right next to the axis-menu. However, this would mean that it no longer will float in the middle of graphs of different sizes as it does now. I have included some screenshot on how it would look when the menu keeps to the extreme left. Do you like the menu pinned to the left?

Examples:
![Screenshot from 2019-08-26 17-24-54](https://user-images.githubusercontent.com/745885/63702114-9b389580-c826-11e9-94b7-963f3f2d54d9.png)
![Screenshot from 2019-08-26 17-25-10](https://user-images.githubusercontent.com/745885/63702118-9c69c280-c826-11e9-849e-d16884a9e47b.png)
![Screenshot from 2019-08-26 17-25-28](https://user-images.githubusercontent.com/745885/63702120-9e338600-c826-11e9-880b-ee75bf4d71af.png)
![Screenshot from 2019-08-26 17-25-48](https://user-images.githubusercontent.com/745885/63702123-9f64b300-c826-11e9-8f77-aec9f0911144.png)

**Comment by pvannierop** [comment]
@alisman I have changed the position of the utilities menu and added an overscroll-x styling in [cbioportal-frontend PR #2662](https://github.com/cBioPortal/cbioportal-frontend/pull/2662).

**Comment by Sjoerd-van-Hagen** [comment]
PR was merged already two months ago.
