### ISSUE TITLE
Treatments in Plots tab: Mutation and CNA option should not be available when no gene is selected

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6547]
When no gene is selected on the Plots tab, like in the example below (Treatments vs Clinical), the "Style samples by" option should not be available and all dots should be in the standard darker blue. 

![image](https://user-images.githubusercontent.com/11892704/64040126-464c9600-cb2a-11e9-977e-a0056e0296a1.png)

**Comment by schultzn** [comment]
Or we use the same functionality as in the waterfall plot. 

But for both cases, should we give the user the option to select no gene?

![image](https://user-images.githubusercontent.com/11892704/64042598-3041d400-cb30-11e9-8840-272aeff461bd.png)

**Comment by pvannierop** [comment]
The utilities/styling menu appearing when styling based on gene mutation/CNA makes no sense is fixed with the [cbioportal-frontend PR #2665](https://github.com/cBioPortal/cbioportal-frontend/pull/2665).

The use of the gene selection menu for these situations is a very good idea. Also we agree that selection of _no gene_ for styling makes sense. Considering the timeline of release we propose that this option is discussed and implemented in scope of a 3.1.1 update.
