### ISSUE TITLE
treatment radio buttons should not be able to be "unselected"

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6550]
currently to not color by anything you can click on the radio button again:

![image](https://user-images.githubusercontent.com/1334004/64047438-cbd94180-cb3c-11e9-8c9e-90b6831e0de8.png)

- [x] Maybe better to allow one to select `None` in the dropdown of the gene

- [ ] On the plots tab when displaying clinical attribute, we might want to reuse that component. Currently it's unclear what gene the dots are colored by:

![image](https://user-images.githubusercontent.com/1334004/64047551-1d81cc00-cb3d-11e9-92cb-bf450ff7c184.png)

**Comment by pvannierop** [comment]
The unselecting of the radiobuttons was a bug, not a feature. It is corrected in [cbioportal-frontend PR #2675](https://github.com/cBioPortal/cbioportal-frontend/pull/2675).

For the other requests I would propose to add these to the 3.1.1 milestone since not covered in the RFC for the treatment feature.

**Comment by Sjoerd-van-Hagen** [comment]
@inodb can this be closed?

**Comment by inodb** [comment]
The second point still needs to be addressed but should be in a separate issue

**Comment by Sjoerd-van-Hagen** [comment]
@inodb Yes, that would be a general improvement.

Will you make the separate issue and close this one?

**Comment by inodb** [comment]
@Sjoerd-van-Hagen done: https://github.com/cBioPortal/cbioportal/issues/6668
