### ISSUE TITLE
sorting of treatment tracks not working

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6569]
See screenshot:

![image](https://user-images.githubusercontent.com/11892704/64454638-790e0580-d0b9-11e9-9506-24d71d50f254.png)

Link:

https://beta.cbioportal.org/results/oncoprint?Action=Submit&cancer_study_list=mixed_broad_ccle_2018&case_set_id=mixed_broad_ccle_2018_all&clinicallist=PROFILED_IN_mixed_broad_ccle_2018_cna%2CPROFILED_IN_mixed_broad_ccle_2018_mutations&gene_list=BRAF%0AEGFR&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=mixed_broad_ccle_2018_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mixed_broad_ccle_2018_mutations&heatmap_track_groups=mixed_broad_ccle_2018_CCLE_drug_treatment_IC50%2CDabrafenib%2CAfatinib-1%2CAfatinib-2%3Bmixed_broad_ccle_2018_CCLE_drug_treatment_zscore%2CDabrafenib%2CAfatinib-1%2CAfatinib-2%3Bmixed_broad_ccle_2018_CCLE_drug_treatment_AUC%2CDabrafenib%2CAfatinib-1%2CAfatinib-2&show_samples=false&tab_index=tab_visualize&treatment_list=Dabrafenib%3BAfatinib-1%3BAfatinib-2%3BDabrafenib%3BAfatinib-1%3BAfatinib-2%3BDabrafenib%3BAfatinib-1%3BAfatinib-2

**Comment by schultzn** [comment]
![image](https://user-images.githubusercontent.com/11892704/64454638-790e0580-d0b9-11e9-9506-24d71d50f254.png)

**Comment by schultzn** [comment]
Link:
https://beta.cbioportal.org/results/oncoprint?Action=Submit&cancer_study_list=mixed_broad_ccle_2018&case_set_id=mixed_broad_ccle_2018_all&clinicallist=PROFILED_IN_mixed_broad_ccle_2018_cna%2CPROFILED_IN_mixed_broad_ccle_2018_mutations&gene_list=BRAF%0AEGFR&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=mixed_broad_ccle_2018_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=mixed_broad_ccle_2018_mutations&heatmap_track_groups=mixed_broad_ccle_2018_CCLE_drug_treatment_IC50%2CDabrafenib%2CAfatinib-1%2CAfatinib-2%3Bmixed_broad_ccle_2018_CCLE_drug_treatment_zscore%2CDabrafenib%2CAfatinib-1%2CAfatinib-2%3Bmixed_broad_ccle_2018_CCLE_drug_treatment_AUC%2CDabrafenib%2CAfatinib-1%2CAfatinib-2&show_samples=false&tab_index=tab_visualize&treatment_list=Dabrafenib%3BAfatinib-1%3BAfatinib-2%3BDabrafenib%3BAfatinib-1%3BAfatinib-2%3BDabrafenib%3BAfatinib-1%3BAfatinib-2

**Comment by schultzn** [comment]
Another observation: The color gradient / scale works well for the z-scores, but not for AUC and IC50. Any ideas how to fix that?

**Comment by inodb** [comment]
@adamabeshouse 	regarding Niki's last point, how hard would it be to add a logarithmic colorscale to oncoprint? Another option might be to make the min & max colors span a larger range

**Comment by adamabeshouse** [comment]
@inodb I think its already an option in the library, so it wouldn't be hard at all

**Comment by pvannierop** [comment]
@schultzn Fix of the sort functionality in oncoprint is in [cbioportal-frontend PR #2647](https://github.com/cBioPortal/cbioportal-frontend/pull/2647).

On the color gradients: they work fine.The AUC profile has a pivot-threshold of 0, so all samples are considered effective and shown in blue. The IC50 profile is completely colored in blue since all tested concentrations are considered ineffective since none are smaller than the pivot-threshold of 0.000001 M (1 micromolar). This may be too stringent. Relation between some pivot-thresholds for IC50:

< 0.001: 464 samples in 17 treatments
< 0.0005: 113 samples in 12 treatments
< 0.0001: 2 samples in 2 treatments

Obviously the pivot threshold is arbitrary. Would you agree with setting the threshold for IC50 to `0.001` to highlight the more effective samples?

**Comment by jjgao** [comment]
What's the plan on this?

**Comment by pvannierop** [comment]
Well, exactly as stated in my last message. The problem has been fixed with merge of PR 2647. In addition I asked for feedback on a proposal from Niki that never had followup.

**Comment by jjgao** [comment]
@pvannierop how were the pivot thresholds decided? I have an naive idea: would it make sense to use the median value as the default pivot threshold?

**Comment by pvannierop** [comment]
@jjgao Well, when it is not defined in the meta file for the profile this is a good idea. For the IC50 values of the CCLE study I was thinking it would be nicer to set it at a low concentration value since these low values are of interest therapy-wise. Needless to say this is an arbitrary value. Would it not be better to set the value at the first quartile in this case?

**Comment by Sjoerd-van-Hagen** [comment]
Can we clean up a bit by closing this issue and creating a new one for adding the thresholds to the study?

**Comment by Sjoerd-van-Hagen** [comment]
@inodb @jjgao @schultzn

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen created another issue: https://github.com/cBioPortal/cbioportal/issues/6772
