### ISSUE TITLE
Need for links to single study query from Cancer Type Summary in a multi-study query

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#6594]
It would be nice to have two direct links in the tooltip of each study:
1 - Link to the study view of that study
2 - Link to the same query but only in the single study selected from the bar chart

![image](https://user-images.githubusercontent.com/11892704/64820866-54190700-d57f-11e9-9a6b-55184ae17307.png)

**Comment by Luke-Sikina** [comment]
Documenting why this may take a minute:  
This is a bit more difficult than just adding two links because of the current behavior of the tool tip. Right now, the tool tip follows your mouse and disappears when you leave your current bar. This means that with the current implementation, the tool tip is impossible to click. That's problematic when you're adding clickable links.
