### ISSUE TITLE
better UI for adding heatmap tracks

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#6788]
CC: @tmazor 

see discussion starting here for an example of how our current UI fails to be clear: https://github.com/cBioPortal/cbioportal-frontend/pull/2836#issuecomment-551227279

**Comment by tmazor** [comment]
My proposal: When a user clicks the "Add" button, text appears below the button with a message, similar to the Add Chart functionality in Study View.

Messages can be:
[profile] added (first time adding a profile)
[profile] updated (adding new genes to an existing heatmap)
[profile] already contains these genes (all genes in list are already present in the heatmap)

**Comment by Sjoerd-van-Hagen** [comment]
My proposal is something like this for adding heatmaps.
![image](https://user-images.githubusercontent.com/9987381/68458991-6bcdde00-0204-11ea-9396-3b30e6e81518.png)
This way:
- you can see the data types that are available, and there is plenty of space for 20 data types or more
- heat maps are added where the buttons are, so it is intuitive and easy to find, and consistent with many other web UIs where you need to add things at the bottom
- we have more space in the top bar for the other buttons which are more focused on the oncoprint

With the new heatmap headers and their small menu that Adam implemented, we can add an 'add tracks' option there. This way for each heat map that is displayed you have the option to add tracks close at hand. You could actually remove the data type from the bottom list after adding a heat map because it would not be necessary any more. It would reappear when the heatmap is deleted.

I think this adequately addresses all concerns that were raised earlier.

To Tali's concern that it splits the menu, I think it actually makes things more clear. I think the menu is a bit overloaded with too many different things. I would actually suggest we consider taking out the clinical tracks as well. We could put a similar component at the top to add clinical tracks, where the buttons would correspond to the most popular clinical tracks, with one button that says 'other...' or something. This way all the 'adding' workflows are taken out of the menu, if consistency in that respect is a concern.

Perhaps we should also give some thought on what to do the the extra space in the top menu because I think we can put that to use to make it a lot more user friendly.

For instance, we now have a button 'mutations', which to me is really unclear in terms of what I can expect there. I would prefer to have separate menus 'Color by' and 'Filter'. Perhaps we can also take the events per sample/patient selector out of the view menu, and have a 'Show' menu for the other options in 'View'. I am sure you would agree that that would be a big improvement in usability.

@cBioPortal/product

**Comment by Sjoerd-van-Hagen** [comment]
Hm just realized I posted this ^ in the wrong issue.

**Comment by inodb** [comment]
let's close for now
