### ISSUE TITLE
on study view move selections to the top of the table

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6896]
It sometimes hard to find your selection in the various tables on the study view

**Comment by jjgao** [comment]
For example, in this one, the four selected genes should be listed first. Ideally we should alternate colors between different selections, e.g. (SMARCA4) one color (e.g. gray) and (TP53, PIK3CA, KMT2C) (e.g. light gray)

![image](https://user-images.githubusercontent.com/840895/70822104-b9f97280-1daa-11ea-8cf3-aede10772525.png)

**Comment by kalletlak** [comment]
@inodb its because of some of the unselected rows have higher frequency. Here is an example

<img width="736" alt="Screen Shot 2020-01-10 at 1 28 01 PM" src="https://user-images.githubusercontent.com/12956870/72176751-0c7b7e00-33ad-11ea-94ea-43e5cb8b4830.png">

@jjgao there will be another issue doing alternate colors between different selections, genes within the selection are not always grouped together(as seen in the above image)

**Comment by jjgao** [comment]
@kalletlak for the selected genes, is it possible to always add them first and follow the same order as in the filters (ideally the same order as user adds)?

**Comment by kalletlak** [comment]
@jjgao in this case we may have to exclude them from sorting. is the ok?

**Comment by jjgao** [comment]
@kalletlak that's ok.
