### ISSUE TITLE
Mutation count is sometimes NA and sometimes 0

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#6934]
The generated "mutation count" clinical attribute has two different behaviors between studies when the sample has no mutations:
* `NA` / empty value: https://www.cbioportal.org/study/clinicalData?id=brca_tcga
* `0`: https://www.cbioportal.org/study/clinicalData?id=msk_impact_2017

I believe this is a bug and the correct value should be `0`.

**Comment by kalletlak** [comment]
Looks like both are correct.

`NA` for samples that are not sequenced
`0` for samples that are sequenced and has no mutations

cc: @jjgao

**Comment by oplantalech** [comment]
@kalletlak How do you indicate that a sample is "sequenced" if it has no mutations? Adding them to the sequenced case list do not change the `NA` to `0`...

**Comment by kalletlak** [comment]
@oplantalech yes, adding them to sequenced case list should change it to 0

**Comment by oplantalech** [comment]
@kalletlak Is this a new feature from a relatively newer version?

**Comment by kalletlak** [comment]
I think no, it is an existing functionality

**Comment by oplantalech** [comment]
@kalletlak I have played with a study and:
1. The fact that the samples are in the sequenced case list does not turn `NA` to `0`.
2. The only way I found to change `NA` to `0` is to add a comment line in the first line of the maf file with `#sequenced_samples: ` followed by the sample IDs separated by spaces **AND** that one of the samples that does not contain mutations should have another data (e.g. CNA).

I think that this last condition should not be enforced, so that we can define as sequenced samples regardless of the data they contain.

**Comment by kalletlak** [comment]
@oplantalech yeah, looks like this is related to https://github.com/cBioPortal/cbioportal/issues/4109

**Comment by oplantalech** [comment]
Adding @n1zea144 to the discussion, since he worked on this part. Can you check my last comment?

**Comment by n1zea144** [comment]
Hi @oplantalech @kalletlak #sequenced_samples was an early method for providing a list of sequenced samples so that users of the MAF could distinguish between a sample that was not sequenced and one that has no mutations.   After that as in place, we introduced the sequence sample list.  Sounds like there is some functionality that relies on the #sequenced_samples list and some that relies on the case list.

I would vote to drop the use of #sequenced_samples header and rely on the sequenced sample list only.  With this in mind, I would create an issue to refactor any relevant code.
