### ISSUE TITLE
Study View Clinical Data tab dataTable replace to React Table

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#695]
First prototype is here 
* http://dashi-dev.cbio.mskcc.org:8080/react-table 
* https://intense-bastion-9218.herokuapp.com

It's really fast for large dataset.
The table is built with our enhanced-fixed-datatable(https://github.com/cBioPortal/enhanced-fixed-datatable). Any suggestions are welcomed. Please edit the following list directly.
- [x] Solve the sorting icon issue
- [x] Sort column order alphabetically
- [x] Make the fixed column customizable
- [x] Number of samples isn't matched with study(https://intense-bastion-9218.herokuapp.com/study.do?cancer_study_id=acc_tcga) -- Reason is that the mismatched cases are only have CNA or/and mutated genes info
- [x] Reset filters

**Comment by inodb** [comment]
Nice! Looks better and the filtering is super useful!

- [ ] In firefox the 'input a keyword' box is out of screen:

    ![screen shot 2015-12-30 at 10 44 37 am](https://cloud.githubusercontent.com/assets/1334004/12052972/6c0acb40-aee2-11e5-8f36-ba86c493fc65.png)
- [ ] The *SAMPLE ID* column shows weird characters in both FF and Chrome:

     
    ![screen shot 2015-12-30 at 10 46 55 am](https://cloud.githubusercontent.com/assets/1334004/12053002/acaf94e6-aee2-11e5-8317-c213518ce5c3.png)

Other suggestions:

- Maybe the order of the columns can be the same as the one on the study summary page? Since we intend to keep track of those (with a priority number or smth else), it might be useful to use the same ordering in multiple places. I could perhaps use the same ordering on the patient view.

- *Input a keyword* is not super clear to me. Maybe make the text *Filter column*. Another idea would be to separate the top row visually in some way to make it clear that they are all filters.

**Comment by zhx828** [comment]
Last call on React Table library. Please feel free to leave comments. The new pull request will be sent on Friday.

**Comment by j-hudecek** [comment]
There are still some issues with this:
- patient and sample IDs are not clickable (how do you get to patient view?)
- column widths are set to a hardcoded number (we could be smart about it and calculate something - age doesn't have to be full width)
- column widths can't be changed
- it's impossible to copy contents of the cell if they overflow
- the scrollbars replacements are cute, but are they really necessary?
- why is the ordering of the columns random?

**Comment by jjgao** [comment]
@zhx828 I am closing this issue. Could you log @j-hudecek's points in another issue.
