### ISSUE TITLE
change endpoint path of GENERIC_ASSAY

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/cbioportal#6955]
Change generic endpoints to `/generic-assay-data/` and `/generic-assay-entity/`

------------Previous discussion--------------

Thanks for @inodb brought up this, we want to have a discussion here to re-evaluate the current endpoint path of GENERIC_ASSAY (`/generic_assay_data/` and `/generic_assay_meta/`). 

We think it would be good to avoid using `-data` or `-meta` in the endpoint because everything is data, so the word doesn't convey any extra information. Maybe better to use something like `generic-assays-molecular-data` and `/generic-assays/`? 

Could I get some ideas from you @n1zea144 @pvannierop? Thanks!

**Comment by jjgao** [comment]
Good point. I think `/generic_assay_data/` may be fine but `/generic_assay_meta/` may be confusing. I would think of `/generic_assay_meta/` similar to `genetic_profile` instead of meta data for the measured entities. `/generic_assays/` would not work either for the same reason. Maybe we can use `/generic_assay_entity/` or something similar?

**Comment by dippindots** [comment]
Thanks @jjgao! I think your suggestion for using `/generic-assay-data/` and `/generic-assay-entity/` is a great idea! @n1zea144 @pvannierop @inodb Do you think we can use those as API path?

**Comment by jjgao** [comment]
@dippindots do we have a conclusion on this?

**Comment by dippindots** [comment]
@jjgao I think we decided to use `/generic-assay-data/` and `/generic-assay-entity/`.

**Comment by inodb** [comment]
I've created a new issue for this #7647. I think we should think a bit more about the naming and the structure before updating
