### ISSUE TITLE
PathwayMapper misc UI issues

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#6959]
- [x] 1. The height of the viewer is larger than my screen - can we make it smaller? Or maybe set a maximum height relative to the screen height?
- [x] 2. When I select a new pathway, sometimes there is a green box of text that appears in the lower left corner but it disappears far too quickly, before I can fully read it.
- [x] 3. If I change the ranking options between match count & frequency, it automatically selects the top pathway according to the new ranking scheme. However, changing the sort order shouldn’t change the selected pathway.
- [x] 4. If I click “Show More” in the pathway list, and then select a pathway, the list reverts back to the original 10 and forgets that I clicked “Show More”.
- [x] 5. Similarly, if I scroll to page 2 of the pathways list, and then select a pathway, it jumps back to page 1

(reported by @tmazor)

TODO:

- [x] Fix CircleCI build
- [ ] Get another round of product review

**Comment by ugurdogrusoz** [comment]
1. This might break a lot of things might want to leave for later.
2. More delay?
3. I am not sure about this. When you change the parameters, it means you're interested in another pathway
4. Should be fixed
5. Should be fixed

**Comment by ugurdogrusoz** [comment]
@onursumer @tmazor Issues are addressed now. Please review.
http://cbio-pm.herokuapp.com/

**Comment by tmazor** [comment]
1. Ok
2. I'm not sure about this pop-up behavior. I'm still just barely able to read the text before it disappears and this is very different than loading behavior than elsewhere on the site. I also haven't found the loading time for other genes to be excessive. And really, we don't need to provide a full explanation, just a generic "Loading..." indication should be sufficient. Are there other ways we can do this?
3. When I change the parameter, it is sometimes because I want to know the score for the pathway I am already visualizing according to the other scoring metric. For example, one way I try to understand the impact of different score options is by looking at one pathway and seeing how different metrics change the score. Just because I change the parameters doesn't necessarily mean I want to see a different pathway.
4. Looks great
5. Looks great
@ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
2. Let's change it to "Loading...". We tried to make this pop-up look like the warnings in some other tabs, such as:
![image](https://user-images.githubusercontent.com/3874988/74626735-957e9580-5161-11ea-8fa2-912066e0e310.png)

3. This was originally designed as you're suggesting but if I am not mistaken it was Niki who said in cBio we immediately apply such changes and asked for this change.

**Comment by jjgao** [comment]
3. I also think it's a good idea to stick to the same pathway when changing parameters... adding @schultzn.

**Comment by ugurdogrusoz** [comment]
3. If you guys agree with it, we could apply the change immediately on option change *without* changing the pathway being visualized.

**Comment by jjgao** [comment]
@ugurdogrusoz @onursumer about 3, let's not change the pathway after parameter change. Thanks

**Comment by tmazor** [comment]
Looks good to me!
