### ISSUE TITLE
tweaking ng-chm button in oncoprint menu

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6973]
The new ng-chm button in oncoprint (see #6306) was discussed in the steering meeting and it was agreed that the button needed to be tweaked/redesigned.

Concerns raised:
a. The button doesn't seem belong to the "Add Heatmap Tracks" as it's not adding any tracks to the heatmap 
b. The NG-CHM tab will not open the same set of samples of genes and it was not clear from the message.
c. The [link](https://bioinformatics.mdanderson.org/public-datasets/about-the-tcga-compendium/) in "Read details on the data processing used for this TCGA compendium here (opens in a new tab)." leads to a placeholder page.

Potential solutions:
i. Change "View Next_Generation Clustered HeatMap (NG-CHM)" to "Whole Study Heatmap (HG-CHM) [linkout icon]"
ii. Add a horizontal line above the button to separate it from the add Heatmap menu.
iii. Rewrite the text blurb in the popup, e.g. "You will have the option to open the Next-Generation Clustered Heatmaps (NG-CHM) developed by The University of Texas MD Anderson Cancer Center for the same selected study. Note: NG-CHM will not be limited to your selected samples and genes."

![image](https://user-images.githubusercontent.com/840895/71732952-6cef4600-2e16-11ea-8eda-a0f3c54215b1.png)

@cBioPortal/product @alisman @ChrisWakefield 

---
Screenshot of the current implementation:
![image](https://user-images.githubusercontent.com/840895/71731620-36fc9280-2e13-11ea-8f4f-f6e46a198562.png)

A query with the ng-chm button: http://bit.ly/37yGzFH

**Comment by ChrisWakefield** [comment]
If it helps with the discussion, here's some explanation:
For (a), the dropdown was just titled "Heatmap" at the time this was planned.  The title since changed to "Add Heatmap Tracks".

For (b), it's tough to explain that the compendium NGCHM are of more recent versions of the dataset than what may have been published in specific papers, and are also grouped by disease, whereas the cBioPortal study has the specific data to match the publication (?).  I think we're open to any wording that conveys the gist of it, but I didn't want to be too lengthy in the modal popup.

For (c), that page was supposed to be completed, so I'll follow up on my end.  It seems to me the link should still be used to better explain (b), and also give relevant detail.

In addition, we should remove specific mention of TCGA, as there are other studies and datasets that result in non-TCGA NGCHM compendia.

**Comment by jjgao** [comment]
@ChrisWakefield thanks for the explanation!

> For (a), the dropdown was just titled "Heatmap" at the time this was planned. The title since changed to "Add Heatmap Tracks".

It was a recent change. I think adding a horizontal line above the button might alleviate the confusion. (proposed solution ii)

For (b), it's tough to explain that the compendium NGCHM are of more recent versions of the dataset than what may have been published in specific papers, and are also grouped by disease, whereas the cBioPortal study has the specific data to match the publication (?). I think we're open to any wording that conveys the gist of it, but I didn't want to be too lengthy in the modal popup.

Given that it's complex, maybe we don't have to explain the nitty-gritty but only note that "NG-CHM will not be limited to your selected samples and genes"? (proposed solution iii)

Also change the button to "Whole Study Heatmap (HG-CHM)" may also help reduce the confusion. (proposed solution i)

> For (c), that page was supposed to be completed, so I'll follow up on my end. It seems to me the link should still be used to better explain (b), and also give relevant detail.

Again, maybe it's not necessary to have the details here. Would it be possible for your site to detect the user is from cBioPortal and display a message on your site and point them to the details?
