### ISSUE TITLE
Design API for File list tab inside patient view (RFC)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7003]
We want to make it possible to attach file urls and iframes to samples and patients.

Either we:

- Use clinical data. When we detect file data type, we render this in a certain way. This will require filtering of clinical data that is of type FILE/IFRAME on study view, results view, comparison tab
- Create a new table attachments. Update importer and validator to import attachments

TODO:

- [x] spec out pros/cons
- [x] Make RFC
- [x] Get community feedback

**Comment by jjgao** [comment]
@alisman @adamabeshouse: @tmazor pointed out that it would be useful to allow i-frame too.

Since we were considering markdown, maybe we can try to extend the markdown syntax to support that as suggested [here](https://github.com/cBioPortal/cbioportal/issues/6383#issuecomment-511516517)

- [ ] `[example](https://example.com)` -> [example](https://example.com)
- [x] `https://example.com` -> https://example.com
- [ ] `[example|i-frame](https://example.com)` -> this will generate a new tab named example to iframe https://example.com

**Comment by inodb** [comment]
A mockup is a good idea I think

Maybe good to write down which use cases we could support and which ones we can't. E.g.:

1. we currently have two tabs called pathology report (pdf) and TCGA tissue image (iframe). It would be nice if these could be handled with the same spec. See: https://www.cbioportal.org/patient/tissueImage?caseId=TCGA-OR-A5J6&studyId=acc_tcga. (Slide viewer is broken: https://github.com/cBioPortal/cbioportal/issues/7068)
2. there might be some things that you would want to show as a separate tab. That makes it easy to click through multiple patients and stay on the same tab. Some other files might be nice to have in a single tab called `Files` or `External Links` or something. I guess this could be accomplished with JJ's Markdown proposal.
3. I doubt the internal slide viewer could be part of the same spec, but it would be neat. For an example check out any MSK-IMPACT patient on internal portal. This might be tricky given the authentication required, but some ideas on how we could generalize the approach used there would be nice. We've had some requests of people wanting to integrate their own slide viewers.

I think it's fine if we can't support any of these cases for now, but e.g. only a `Files` or `External Links` tab. Could maybe apply some readme driven development (RDD) for this one by describing how someone external would go about adding a file/link here:

https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats

**Comment by inodb** [comment]
Some more thoughts on this:

If we decide to use clinical data for attachments/urls there are a few things to consider:

Don't show file data:

- in charts on study view. Only absence/presence is useful
- on results view page (you don't want to show it in oncoprint/plots tab etc)
- on comparison page

Might want to show attachment/urls
- as column on clinical data tab on study view
- in the sample and patient tooltip on patient view?

Show attachment/urls
- on patient view. Exact way we are still figuring out

Those things are prolly not too hard 👆. But we should evaluate whether the option open of using a separate table in the mysqldb for attachments/urls makes more sense. Because there might be some other issues like:

- clinical data calculations done on the backend. Prolly adding a filter is easy but not sure how adding more clinical data will affect performance at mysql level either
- we might have to do filtering on both controller layer and frontend layer
- connection between files. E.g. there might be multiple PDFs of a slide for the same sample. This is a use case for pathology slides. We should be able to put multiple PDFs in a single tab so you can easily browse the slides between patients. It would be pretty easy to capture this relation in a separate mysql table. Im not sure how to extend the markdown format to support these type of links between files. A common clinical attribute or value prefix?
- as an API consumer (e.g. R scripter or Python scripter) it's prolly fine to find URLs in the `clinical-data` endpoint. But I'm not 100% sure

Many times we go for using an existing backend solution, because we don't like to have to adjust:

- migration code
- import code
- pipeline code

it's easier to adjust frontend and api logic, since that update process is smoother. Just want to make sure it makes sense. We can always convert the clinical data later if we run into issues but it might mean double work as well

**Comment by adamabeshouse** [comment]
if there's a chance that we want the same "file" aka attribute id to have more than one link, then this situation is more complicated than expected. I think we should reconvene and figure out how we're going to do this on the backend.

**Comment by adamabeshouse** [comment]
the next step in terms of implementing the frontend has to do with what form the API calls will take, so can we reconvene and discuss all this and try to come to a conclusion next week? @inodb @alisman @jjgao

**Comment by adamabeshouse** [comment]
On the issue of using clinical data table and API, rather than making a new table and API endpoint specifically for file "attachments":

PROS OF USING CLINICAL DATA API:
- A lot less work - just make a new clinical data type "url" and use existing infrastructure.
    Would otherwise have to make new table, new API, new part of pipeline.

CONS (aka PROS OF USING NEW TABLE):
- is a URL "clinical data"? semantically it may be messy.
- more than one URL per sample doesn't match clinical data model of one datum per sample. (solution?: could we put more than one URL into the data for a sample, e.g. by tab-delimiting or comma-delimiting?)
- do we need to make sure these "url"-type clinical data don't make it into the oncoprint and study view clinical track selectors? if so, is it semantically sound to just filter out all "url"-type?

**Comment by jjgao** [comment]
@adamabeshouse @inodb thanks for the discussion here. I noticed that we keep change the issue titles now. I am not sure if that is an effective way of tracking things. For example, I think it might be better to have "File list tab inside patient view" as a epic and "pros/cons of API decision" as an issue/task in the epic. Let's discuss.

**Comment by adamabeshouse** [comment]
okay now that we've discussed that, let's discuss the issue 😁

**Comment by adamabeshouse** [comment]
after discussion, @inodb and I are thinking that the best plan is to make a new table and API for files that is very similar to the structure of clinical.

So there would be a files_meta table, then files_sample, files_patient, files_study

A few big reasons for this:
(1) Files and clinical attributes/data are semantically different entities. They need different details to specify them. It will be increasingly convoluted and straining on the logical coherence and maintainability of the system if we try to shoehorn files into the clinical system.

(2) Files and clinical attributes/data function differently in the portal. For example, files shouldn't wouldn't appear in clinical attribute selectors in the study view or the oncoprint. If we add files to the clinical system, we will have to manage this, filtering either on the backend or frontend. Either solution seems to add complexity to the code and reduce intuitiveness of the system.

(3) There is currently no concept of a study-level clinical attribute, but from the outset we are talking about study-level files. This is another semantic issue that immediately forces strain onto the way we store and conceive of the data.

**Comment by adamabeshouse** [comment]
Draft RFC https://docs.google.com/document/d/1_Re7ThLGYcyzvpEH9eMrdi-vbOx_He5Txkgt_L0onGA/edit#
