### ISSUE TITLE
End-to-End studyview.spec.js is failing

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#7135]
According to the last few front-end PRs, studyview.spec.js is failing.

For details, see:  https://circleci.com/gh/cBioPortal/cbioportal-frontend/61737?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I think this is due to two (large) screenshots failing.

The screenshot tests within studyview.spec.js should also probably be moved out to a new studyview.screenshot.spec.js, so that it follows the convention.

I can try to fix this.

@inodb how do I find the screenshots that are generated by circle CI, so that I can check these in instead?

**Comment by inodb** [comment]
@ecerami good catch! Looks like this is because of the backend binning fix for bar charts of integers on the study view (see also v3.2.2 release notes). The screenshot comparison tool can be found here:

https://61737-66571349-gh.circle-artifacts.com/0/imageCompare.html

You can get there by clicking on the "artifacts" tab of the circleci link you shared and clicking on imageCompare.html. At the bottom of the page there is a command that indicates how to update the screenshots. One needs to send in the screenshots through a pull request.

These tests aren't run on the backend which is why we didn't catch it earlier. We only run the localdb e2e tests on the backend as part of ci testing. If there are big backend changes in a release we currently run these frontend e2e tests manually after deploying to a test instance.

**Comment by ecerami** [comment]
Thanks @inodb!  I didn't see the artifact tab before, as I wasn't logged into circle CI.

I also wasn't sure if we wanted to break out the screenshot tests into its own file (that is part of #7134 discussion).  But, I did follow the instructions on Circle CI and created a PR with updated screenshots.
