### ISSUE TITLE
Documentation on how to update importers

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7171]
We currently have information on how to update the apps on various systems: https://docs.cbioportal.org/4.-development/release-procedure and https://docs.cbioportal.org/4.-development/deployment-procedure. But we don't have docs on how to update the importers.

The goal is that anyone with the right permissions should be able to do a complete deployment of a new version of the system that includes database migrations

**Comment by sheridancbio** [comment]
The building of new importers is centered around a build script in the current git repo for pipelines (pipelines.cbioportal.mskcc.org:/srv/data/local/pipelines-git/pipelines-configuration.git).

The build script is in build-importer-jars/buildproductionjars.sh and it addresses things such as iterating through all production importers and doing the maven build, deploying *.jar files to the importer account lib directory, bundling the correct portal.properties files into the builds, checking out the correct version of the cbioportal repo so that other resources (applicationContext_business.xml) can be bundled in to the importers, adding overlay files for special internal portals (msk) and cleaning up the repo afterwards.

This can all be explained more clearly and with helpful diagrams.

**Comment by inodb** [comment]
Thanks so much @sheridancbio ! That's helpful

I think it would also be useful to know how to disable imports before upgrading. Something like:

1. Disable imports (or let people know here & here to not run imports)
2. Run migrations here & here
3. Upgrade importers
4. Re-enable importers

**Comment by sheridancbio** [comment]
That's a great point ... I also think we should maybe make our deployment script aware of the import status, and possibly add controls so that a run of the "build and deploy new importers" script would be able to request a shutdown / lockout of the imports and would then wait until imports were not running before deploying newly built importers. (i.e. automating the proper control of active import runs)

**Comment by sheridancbio** [comment]
or better yet ... wrap the importer itself in a kubernetes deployment, so that redeployment can be managed through kubernetes and would not interrupt an "import-in-progress"
