### ISSUE TITLE
pathways svg download doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7177]
The file that downloads doesn't seem to work. I can open it in chrome as XML but I can't find an application in which it will open as an image.

**Comment by onursumer** [comment]
Adding `version` and `xmlns` properties to the `svg` element should fix this. Something like this:
```HTML
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" ...>
```

**Comment by ugurdogrusoz** [comment]
Opens fine with Inkscape but browsers such as Chrome fail to open it. What @onursumer suggests seems to fix it but we need to see if we construct this svg ourselves or comes from Cytoscape.js basic functionality or some library. If we're doing it ourself, we should just add these two attributes. Otherwise, we might try injecting these into the returned svg text.

**Comment by tmazor** [comment]
Looks good!
