### ISSUE TITLE
Group comparison page: create groups not working for public portal when logged in

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7188]
![image](https://user-images.githubusercontent.com/840895/74612690-b26d8700-50d5-11ea-9ba1-61d0b9b1f16e.png)

**Comment by adamabeshouse** [comment]
@jjgao can you send a link? I think this is related to the issue I raised the other day of legacy groups with broken formats

**Comment by dippindots** [comment]
@jjgao @adamabeshouse I can log in and create an overlapped group like this, could you provide a link to reproduce this issue?
![image](https://user-images.githubusercontent.com/15748980/74774718-3bb1c480-5262-11ea-85e1-a6bc7dba80fa.png)

**Comment by jjgao** [comment]
Strange, I had no problem with your session. @dippindots 

but try this one: https://www.cbioportal.org/comparison?sessionId=5e4c592fe4b0ff7ef5fd6d23

**Comment by adamabeshouse** [comment]
the issue is that for some reason some data on the backend is getting corrupted. this is related to an issue I pointed out a few weeks ago but I thought it was restricted to my account having corrupted data groups that I created during development. so it means somehow data for other users is getting corrupted as well. @jjgao has anyone else reported this?

this is a screenshot example of when it happens:
[Link here](https://www.cbioportal.org/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acc_tcga&case_set_id=acc_tcga_cnaseq&data_priority=0&gene_list=PTEN&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_mutations&profileFilter=0&tab_index=tab_visualize)
![image](https://user-images.githubusercontent.com/636232/74780792-4ffbbe80-526e-11ea-826c-7f02c3ef7906.png)

Notice that the top group is missing the critical `data` attribute which everything should have. This seems like it's probably some kind of backend session service issue. Any insight @kalletlak ?
