### ISSUE TITLE
Error downloading data in Mutations tab

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7203]
From [a user](https://groups.google.com/forum/#!topic/cbioportal/yZhHJCUVpak):

"I was looking at the MSK-IMPACT study, in the Mutations tab - here is a link:  http://bit.ly/2P5k8B9

I clicked the download button above the mutations table and after a while I got the error message "Download Error!  An error occurred while downloading the data.  Downloaded file may contain incomplete data.".  Screenshot attached.  

I tried again and got the same error, and the file was different.  I tried a third time, same error, this time the file was the same as the second attempt (I can provide the files if you want)."

![2020-02-18_05-56-28](https://user-images.githubusercontent.com/840895/74860230-4a59b380-5316-11ea-9ce5-532f2d9c8aa7.png)

**Comment by onursumer** [comment]
It worked fine for me, but it takes more than a minute to fetch all the necessary data from Genome Nexus. It is possible to experience such errors when the list of mutations to download is really long. In this case we have almost 5000 mutations. 

This error is most likely because of a Genome Nexus query failure. But, It may also be failing due to other network issues on the client side.

**Comment by dllahr-foghorntx** [comment]
Original reporter here, in the example above I used TP53 which has a lot of mutations but I also experienced it with a gene that has many fewer (can't report it b/c of confidentiality).

**Comment by sigmaclennan** [comment]
I am trying to download mutation data (from the mutations tab) on pedcbioportal for a particular gene in all studies and encounter this same error. Are there other ways I can download these data to ensure I don't have an incomplete table?
