### ISSUE TITLE
Adding RB1 to the query does not work

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#7231]
- Go to https://deploy-preview-3037--cbioportalfrontend.netlify.com/results/pathways?Action=Submit&Z_SCORE_THRESHOLD=1.0&cancer_study_id=gbm_tcga_pub&cancer_study_list=gbm_tcga_pub&case_set_id=gbm_tcga_pub_sequenced&gene_list=TP53%20MDM2%20MDM4%0AHRAS&gene_set_choice=user-defined_list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_pub_cna_rae&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_pub_mutations
- Select the pathway named `HNSC-2015-Cell-cycle...`
- Select `RB1` on the pathway
- Click `Add selected genes to query` menu button on the top.

Current behavior: Nothing happens, and no feedback provided to user.
Expected behavior: Either add the selected gene to the query or display an error/warning message.

**Comment by ugurdogrusoz** [comment]
How about we display a warning message as follows when none of the selected nodes are genes with valid gene symbols "Selected nodes are not genes or do not have valid gene symbols"

**Comment by ugurdogrusoz** [comment]
A message was added as specified.

**Comment by tmazor** [comment]
This is rather confusing as a user, since RB1 is in fact the name of a gene. How about we add another sentence to this message?

"Selection contains nodes that are not genes. See documentation for an explanation of node types."

Even better, can we link to the relevant section of the documentation? And can we specify the invalid nodes?

"Selection contains nodes that are not genes (RB1, node2, node3). See documentation (https://github.com/iVis-at-Bilkent/pathway-mapper#adding-genes-and-interactions)
 for an explanation of node types."

**Comment by ugurdogrusoz** [comment]
OK let's specify the labels of invalid non-gene nodes as well (using the same notation with invalid gene symbol listing). I don't think we should make this warning message so long as we try to keep them concise. I think it's user's responsibility to understand the notation and it's obviously under Help.

**Comment by tmazor** [comment]
Minor, but can we remove the word "following" from this message:
![image](https://user-images.githubusercontent.com/10508276/75807810-0faf3c80-5d54-11ea-98f1-16ba123a0412.png)

This doesn't need to hold up deployment, but should be fixed.

**Comment by jjgao** [comment]
unstale

**Comment by ugurdogrusoz** [comment]
@onursumer @msalihaltun We actually get an error on this now. Can you please take a look?

**Comment by onursumer** [comment]
To clarify, production is working fine currently.

This bug comes back with cBioPortal/cbioportal-frontend#3458. I think it is because of an incomplete banner fix on the PathwayMapper side. @msalihaltun can you confirm that?

**Comment by msalihaltun** [comment]
It is indeed because of the incomplete banner fix. We should either go back to using `toast` on PathwayMapper side for https://github.com/cBioPortal/cbioportal-frontend/pull/3458 or complete the changes for the `MessageBanner`. Apperantly changes were completed but never added to the PR itself. 

@onursumer which one should we go for?

**Comment by onursumer** [comment]
@msalihaltun Since we have already broken the functionality by cBioPortal/cbioportal-frontend/pull/3458, I think we should complete the fix in that PR as well.

Initially I was thinking a separate PR to fix the banner issue, but now considering the effort it doesn't seem right to go back to using `toast`.

**Comment by onursumer** [comment]
This seems fixed for the current Pathways tab.
