### ISSUE TITLE
Release Procedure docs are unclear about backend only release

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7273]
See: https://docs.cbioportal.org/4.-development/release-procedure

Alternative 1:

I was thinking to do backend only releases by tagging both backend and frontend. Such that versioning remains consistent in frontend + backend. If there are no frontend changes, one can still tag it (i.e. multiple tags for the same commit).

Alternative 2:

Backend only releases we call e.g. v3.2.7-rc1, v3.2.7-rc2. We only tag (so no release notes). Then whatever we have in there on Thursday we release as v3.2.7. This way the last digit of the versioning (x.x.LAST_DIGIT) is still a good indicator of how many weeks since we released the last release with a db migration (x.DB_MGRATION.x).

Ideally both frontend + backend tags + version notes are always identical. That is: in terms of versioning it's rather a mono repo than two separate projects. Open for discussion, but good to choose something and be consistent

CC: @alisman

**Comment by Luke-Sikina** [comment]
We had a small discussion about this on the engineer's call today (@oplantalech @sheridancbio @pvannierop @adamabeshouse). Our general consensus was that we prefer the first approach, but we felt that we were missing a lot of people's inputs.

Speaking for myself, I don't get any value out of having the third version number being the number of weeks since the last release with a database migration, so that does not matter to me. I like the simplicity of just incrementing the third number.

Why is it important that the third digit of the release version be the number of weeks since the last database migration?

**Comment by adamabeshouse** [comment]
I like option one, but I feel like I don't know much about the rationale behind versioning. But intuitively it does seem simpler to keep the versions aligned.

**Comment by alisman** [comment]
I'm cool with empty frontend release.  Seems like a small price to pay to keep them in line.

**Comment by Sjoerd-van-Hagen** [comment]
Alternative 1 makes a lot of sense. Changes in the back end can lead to things looking different in the front end so it should have a change log to make users aware of those.

**Comment by inodb** [comment]
hmm i think the docs should still be updated
