### ISSUE TITLE
add matching criteria explanation to pathway mapper tutorial

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7319]

**Comment by ugurdogrusoz** [comment]
@inodb Slide 7 of the tutorial already explains both the choices in drop down box (match count vs percentage) and the checkbox (whether matching genes should be counted by the number or alteration frequency). Are you asking for more detail?

**Comment by inodb** [comment]
Thanks for the quick follow-up @ugurdogrusoz ! I see indeed it's in the tutorial already. @ecerami @Sjoerd-van-Hagen do you think this is clear enough?

**Comment by Sjoerd-van-Hagen** [comment]
I was aware of that slide, and I think it is not very clear. For instance, what does 'match' mean? Is that against altered or in the query? It is not clear from the slide.

It would be better to split that slide into two or three slides. One slide can describe the interface elements and the others go into detail on the scoring. The tool tips in cBioPortal are currently more informative than the tutorial, which should be the other way around in my opinion. In the slides you have space to really explain how it works without being restricted by screen real estate in the interface.

To be honest, in the UI it is also a bit confusing due to the alteration frequency option. To me it would be more straightforward if the count would be only altered genes in the pathway (in any sample), and with the alteration frequency it would then simply be weighted. What interest are pathways that overlap with query genes but none of the query genes are altered? Perhaps I should ask @schultzn

**Comment by ugurdogrusoz** [comment]
@Sjoerd-van-Hagen I added another slide that explains the ranking options with an example.

**Comment by Sjoerd-van-Hagen** [comment]
Where can I find the latest version? On the drive and github I see the old one. @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
It's slide 8 of the tutorial on the drive (**not** the live version though).

**Comment by Sjoerd-van-Hagen** [comment]
Not sure if I have access to that.

**Comment by ugurdogrusoz** [comment]
@tmazor shared these presentations with me. Share your email address with me please (email me 
at [this address](https://user-images.githubusercontent.com/3874988/77904988-2763dd00-728e-11ea-839d-59e8d3719fe9.png) privately?) so I can give you access and point you to it.

**Comment by Sjoerd-van-Hagen** [comment]
The new slide looks great. Really helpful! Ready to be published.

**Comment by tmazor** [comment]
The new slide is now live @ugurdogrusoz @Sjoerd-van-Hagen
