### ISSUE TITLE
Oncoprint controls hidden while loading generic assay data

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7427]
There's quite a long period during which controls are hidden.  Might be due to some particular slugishness of a service, but we should handle it better.  Like, for me it just took ~10 seconds for it to show up.  Rest of oncoprint was showing but controls hidden.

https://www.cbioportal.org/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ccle_broad_2019_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ccle_broad_2019_cna&cancer_study_list=ccle_broad_2019&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=ccle_broad_2019_cnaseq&gene_list=CDKN2A%2520MDM2%2520MDM4%2520TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by adamabeshouse** [comment]
@dippindots it looks like this may be because the controls wait for generic assay stuff to finish loading before showing up. maybe you can take a look at a way to pass the promise in instead of passing in the loaded promise result, and handle rendering some kind of loading indicator within the controls?

**Comment by dippindots** [comment]
@adamabeshouse That makes sense! I should wait at the very beginning before we show the oncoprint, I will take care of this, thanks!

**Comment by dippindots** [comment]
@adamabeshouse Yes, that's a good idea! I will give it a try!

**Comment by adamabeshouse** [comment]
@dippindots thanks!
