### ISSUE TITLE
react-mutation-mapper LollipopMutationPlot example throws an error

### ISSUE THREAD

**Issue by ynotdraw** [cBioPortal/cbioportal#7434]
Hello!  Following the notes on https://github.com/cBioPortal/cbioportal-frontend/issues/new, it says to create an issue here instead of the frontend area.

I'm really interested in embedding one of these lollipop charts in my app, so I tried following https://github.com/cBioPortal/cbioportal-frontend/tree/master/packages/react-mutation-mapper.  After installing all of the dependencies and copy/pasting the example in the README, it appears I'm getting a mobx error of `Cannot read property 'getAtom' of undefined`.

I decided to create a codesandbox to ensure it was nothing in my app causing any issues.  I have shared the link here, where I get a blank page (no errors though, which is weird).  Is there a way to get the lollipop plot working as a standalone component?  Am I missing something?

https://codesandbox.io/s/fervent-thompson-lguj9?file=/src/App.js

**Comment by alisman** [comment]
@ynotdraw my first guess is that this is due to mobx versioning issues.  we are rather behind in mobx and react.  i can see that your sandbox includes much later versions that we are using in the cbioportal, which is the main home of the react-mutation-mapper.   when i brought mobx and mobx-react in line with versions in cbioportal package.json, the errors went away (unfortunately i got new ones).  Lets see what @onursumer has to say.  I believe we have successfully embedded the mutation mapper in other projects.

**Comment by onursumer** [comment]
@ynotdraw right now `react-mutation-mapper` works only with mobx version 3. Unfortunately, you cannot use it with the latest versions of mobx and mobx-react yet. Also, try removing the line `filterMutationsBySelectedTranscript: true`. For some reason all the mutations are filtered out, something with the default configuration might have changed. You also need to `import "react-mutation-mapper/dist/styles.css"` for proper styling.

@alisman we should probably reopen #6144 at some point. And also update/improve the docs eventually.
