### ISSUE TITLE
The frontend repo versioning of lerna is out of sync with our release versioning

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7461]
Just released v3.3.1 for the frontend but noticed that lerna is already at 3.3.2 for for the root repo:

https://github.com/cBioPortal/cbioportal-frontend/releases/tag/cbioportal-frontend%403.3.2

We should figure out how to keep it in sync. Either we only use lerna versions and we skip a few minor releases from backend. That is we go from v3.3.0 straight to v3.3.2. Or we figure out some other way to keep backend/frontend tags in sync

**Comment by onursumer** [comment]
This is the expected behavior for the current auto-version setup. Whenever there is a change, lerna automatically patches the `cbioportal-package` version. Unfortunately there is no fine tuning of auto patching as far as I know. It would be great if we could configure `lerna version` to auto patch everything but just add a prelease tag for the main `package.json`.

Another (not an ideal) option is to ignore the version in the root `package.json`. `cbioportal-frontend` is a private package and we never intend to publish it anyway. We only version it to make sure that lerna properly updates dependencies for the `cbioportal-frontend` package.

Yet another (and probably better) option is to move the entire `cbioportal-frontend` package to a subdirecory (workspace), say `webapps/cbioportal-frontend`. In that case the version in the root `package.json` wouldn't get updated automatically. The root package.json would become a meta package (which is the proper monorepo setup anyway). We can manually update the root `package.json` version whenever we want, and ignore the auto patched version of the `cbioportal-frontend` package.
