### ISSUE TITLE
upload image in cbio under sample or patient

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7488]
Hi Team,

Could you please share the steps to upload the image shown under this study (Brain Lower Grade Glioma (TCGA, Firehose Legacy)).

Can we upload images under our local instance studies?

https://www.cbioportal.org/patient/tissueImage?caseId=TCGA-DH-5142&studyId=lgg_tcga

**Comment by jjgao** [comment]
Hi @Mohammedhusen, The imaging data was hosted by [CDSA](https://cancer.digitalslidearchive.org/) and we are using iframe to include their site into our patient page. We are currently working with CDSA so that cBioPortal and CDSA can be co-deployed for local installation, but it will take some time (at least 6 months) before it's available.

If you have your web tool to host the imaging data, you could include them as an tab with the newly released Resource data file: https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#resource-data

**Comment by Mohammedhusen** [comment]
Thanks for quick reply on this.

I just tried with resource definition but getting below error.

May I know under which version this functionality available ?

ERROR: meta_resource_definition.txt: Could not determine the file type. Did not find expected meta file fields. Please check your meta files for correct configuration.

ERROR: meta_resource_sample.txt: Could not determine the file type. Did not find expected meta file fields. Please check your meta files for correct configuration.

Regards,
Mohammedhusen Khatib.

**Comment by jjgao** [comment]
please use the latest version 3.3.2.

**Comment by Kekananen** [comment]
@jjgao Is there a timeline for when this will be done? I'm eager to also have pathology slides hosted without having to sustain our own individual urls.

**Comment by francoise231101** [comment]
Hello, @jjgao,

Recently, I've been trying to find the function on cBioPortal to upload images under patients or samples. I came across a similar question here. But as of 2024, has cBioPortal already implemented this functionality?

Francoise
