### ISSUE TITLE
Loading both GRCH37 & GRCH38 data

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7575]
Hi Team,

We would like to upload both GRCH37 & GRCH38 aligned RNA/DNA derived data into our local cbio instance.

Could you please share the steps or instructions to load the data.

**Comment by jjgao** [comment]
Hi @Mohammedhusen both GRCH37 & GRCH38 are supported, but our documentation seems lacking. For RNA, since no genomic coordination will be imported so the reference genome version does not matter. For DNA/mutations, we will try to add some instructions.

@inodb @leexgh since you were working on ghch38, I am wondering if you have the steps? It may be a good idea to create a page for the instructions on this.

**Comment by inodb** [comment]
@Mohammedhusen I believe to load 38 data one only needs to load the 38 seed database (https://github.com/cBioPortal/datahub/tree/master/seedDB_hg38) instead of the default one in this step: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#step-2-run-mysql-with-seed-database

CC @SRodenburg

**Comment by Mohammedhusen** [comment]
Hi @inodb ,

Thanks for sharing this document.
Recently we have upgraded to v3.3.7 and it has a database version of 2.12.4 and the seed database link you have shared has older version i.e 2.11.0, so is it possible to get this seed DB with the latest version?

And also to load the study with a specific genome version just mentioning reference_genome_id in the study meta file will work or should we follow some other steps?

**Comment by inodb** [comment]
Hi @Mohammedhusen - in step 4 the seed database will be updated to the latest version: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#step-4-migrate-database-to-latest-version. That should work without issues, but let us know if not

I believe it's correct that only setting reference_genome_id in the meta file is enough

If you notice any issues, please let us know. Thanks!

**Comment by inodb** [comment]
@Mohammedhusen closing this for now. Feel free to re-open if you run into an issue with the proposed solution. I've created a new ticket to create a new page for grch38 support specifically: https://github.com/cBioPortal/cbioportal/issues/7641
