### ISSUE TITLE
Demonstrate that we can log into a dummy google account using webdriver.io

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7591]
- [ ] Create dummy google account
- [ ] Write webdriver test that opens the portal, clicks login button and proceeds through login steps

**Comment by onursumer** [comment]
@alisman @inodb I was able to find the setting to persist the login information with a chrome options argument `--user-data-dir`, and updated cBioPortal/cbioportal-frontend#3265 to support that feature.

So, here is an example environment setup to run e2e tests on an authenticated portal:

```
export CBIOPORTAL_URL="https://genie.cbioportal.org"
export FRONTEND_TEST_DO_NOT_LOAD_EXTERNAL_FRONTEND="true"
export CBIOPORTAL_BOT_PASSWORD="yourpasswordgoeshere"
export SESSION_DATA_DIRECTORY="path/to/chrome-session-data-dir"
``` 

In order this setup to work we need to make sure that we run the `login` test before running any other test.

**Comment by onursumer** [comment]
Authentication may get blocked by Google due to security reasons if the tests are run from a dynamic IP range (which is the case for circleci). 

As a workaround, we need to do authentication from a fixed IP. One way to do is to setup up a full e2e environment on a separate machine. Alternatively, we can setup a proxy or VPN on circleci as described here: https://support.circleci.com/hc/en-us/articles/115014372807-IP-Address-ranges-for-safelisting-Do-you-have-static-IP-addresses-available-
