### ISSUE TITLE
migration fails with Can't drop foreign key `genetic_alteration_ibfk_2`; check that it exists

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#7697]
Hi, I'm trying to update from 1.4.1 to 3.4.2 (I know) and I got all the way to version schema 2.11 but it seems the migration script is trying to drop a foreign key that doesn't exist. Searching this repo (indeed even the whole of Github) finds the migration script as the only reference so perhaps it's not supposed to be there

**Comment by jjgao** [comment]
This is strange. @sheridancbio any insights?

**Comment by sheridancbio** [comment]
Yes - this is an inherent problem we have. mysql has built in rules for generating names for the foreign key constraints. It is possible to supply names for the keys when they are constructed, but (I think depending on which version of mysql you are running) it may or may not honor your requested constraint name. We have not been attempting to specify the constraint name in our migration scripts. The rules for name generation also depends on the presence of other constraints for the involved tables and the order in which they are created.

the "ibfk_2" part of the name above was auto-generated on one of our systems, but on the user's system some other pattern is probably present when the migration gets to migration step 2.11

The fix for the user would be to examine the database with a statement such as "show create table genetic_alteration" On our system, the output looks like this:
| genetic_alteration | CREATE TABLE `genetic_alteration` (
  `GENETIC_PROFILE_ID` int(11) NOT NULL,
  `GENETIC_ENTITY_ID` int(11) NOT NULL,
  `VALUES` longtext NOT NULL,
  PRIMARY KEY (`GENETIC_PROFILE_ID`,`GENETIC_ENTITY_ID`),
  KEY `genetic_alteration_ibfk_2` (`GENETIC_ENTITY_ID`),
  CONSTRAINT `genetic_alteration_fk_1` FOREIGN KEY (`GENETIC_PROFILE_ID`) REFERENCES `genetic_profile` (`GENETIC_PROFILE_ID`) ON DELETE CASCADE,
  CONSTRAINT `genetic_alteration_ibfk_2` FOREIGN KEY (`GENETIC_ENTITY_ID`) REFERENCES `genetic_entity` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |

**Comment by sheridancbio** [comment]
You can see here that we have one foreign key constraint called genetic_alteration_fk_1  .. and on foreign key constraint called genetic_alteration_ibfk_2. The user's system will probably have something different. The user could alter their migration.sql file to have the correct (matching) foreign key constraint name based on their situation for the next migration step (where the foreign key is deleted by name). Then the migration should continue properly.

also, this kind of problem should urge us to create a unit test where a database with an early database schema is migrated to the most recent database schema ... to make sure that the migration script functions correctly over the migration history. It could be that there is an error in the migration script which "worked" for the person who wrote that migration step, but only because of the history of local manual changes to their database. An abstract unit test on a clean (seed) installation of the mysql database may show that the migration.sql script actually is expected to fail at step 2.11. If so, we should make migration.sql work correctly for the fresh install of an early seed database.

**Comment by sheridancbio** [comment]
I looked a little closer at the migration.sql file. If the user is not sure which foreign key constraint name should be used, it should be whatever name is associate with the constraint to the table "genetic_entity"

On our (mskcc) tables, it *is* listed as genetic_alteration_ibfk_2 above, but this is probably because of the history we have of testing / applying the migration scripts to our database tables. The user may have genetic_alteration_fk_2 instead (or something different). The basic thing that is happening here is that the foreign key is being re-created with the DELETE CASCADE option set. It is interesting that on migration step 2.0.0, a new genetic alteration table is created and on line 245 the constraint is created explicitly with name "genetic_alteration_fk2" (an exception to what I said above). So this is probably a bug in the migration script and should be fixed (after testing) cc: @n1zea144
