### ISSUE TITLE
Depending on study selection, different mutation percentages are displayed

### ISSUE THREAD

**Issue by abveloso** [cBioPortal/cbioportal#7706]
Hello,
If I look into TP53 mutation in TCGA PanCancer Atlas studies for ovarian and uterine carcinosarcoma individually, both studies seem to have 91% of samples with mutation.
If I run the query for both studies together, the ovarian TP53 mutation rate goes down to a little over 60%.
Is this intended behavior?
Thanks,
Artur

![carcinosarcoma](https://user-images.githubusercontent.com/65561361/88078102-09c2c800-cb4a-11ea-9328-b9fb33b7d2a8.PNG)
![ovarian](https://user-images.githubusercontent.com/65561361/88078111-0c252200-cb4a-11ea-9853-46f4759d18d6.PNG)
![ovarian_and_carcinosarcoma](https://user-images.githubusercontent.com/65561361/88078115-0d564f00-cb4a-11ea-9b65-40666a611266.PNG)

**Comment by jjgao** [comment]
Hi @abveloso that was because when you query the individual studies, only the samples with mutations and CNA data were selected and when querying the two studies together, all samples were selected and some of the samples only have one type of data. Please change the case set to "Cases with both mutations and CNA data".

![image](https://user-images.githubusercontent.com/840895/88232544-0dd31080-cc44-11ea-9096-14eedc4c2a2d.png)

**Comment by jjgao** [comment]
@abveloso please feel free to contact cbioportal@googlegroups.com for prompt responses.
