### ISSUE TITLE
option to see study loaded with grch37 or grch38

### ISSUE THREAD

**Issue by Mohammedhusen** [cBioPortal/cbioportal#7710]
Dear Team,

Where we can see study loaded with grch37 or grch38 in the cbioportal interface?

Thanks.

**Comment by jjgao** [comment]
HI @Mohammedhusen we added some warning message when a user select study with different reference genome builds. Otherwise, I don't think we are display the info. @leexgh @inodb, please correct me if I am wrong.

FYI - we plan to improve the documentation for the support of grch38. https://github.com/cBioPortal/cbioportal/issues/7641

@Mohammedhusen for questions, would you please contact us at cbioportal@googlegroups.com instead of github? Thanks.
