### ISSUE TITLE
Compare from the table component in study view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7831]
Currently, one can compare groups from pie charts and bar charts, but not the tables. It would be useful to enable that too. One complication is that there may be previously selected rows already. For comparison, maybe we could just compare for the newly selected rows? For example for the one below, `Compare` will compare samples with APC mutations vs samples with PIK3CA mutations.

![image](https://user-images.githubusercontent.com/840895/91196510-3aa59800-e6c8-11ea-8110-b9076e0f6eba.png)

Treatments:
https://genie-private.cbioportal.org/study/summary?id=nsclc_genie_bpc

**Comment by alisman** [comment]
@adamabeshouse, from (@schultzn): 
One suggestion: When creating the group names, can you put the Pre / Post before the drug name instead of after? With long drug names, the pre / post often gets cut off in the table headers and graph legend on the comparison tab.
It could be "Pre-DRUG", e.g. "Pre-Erlotinib Hydrochloride"

**Comment by jjgao** [comment]
I reopened this for two followups: 

- [ ] support Compare feature in mutation/cna/fusions table
- [ ] add Compare button next to Select button

**Comment by adamabeshouse** [comment]
Finishing in https://github.com/cBioPortal/cbioportal/issues/7991
