### ISSUE TITLE
AppConfig.baseUrl not available when running `yarn start`

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#7893]
# Problem

I am testing the transition from Study View to Group Comparison while serving the frontend with node dev server using `yarn start`.  Here the routing is broken. Instead of going to:

```
http://localhost:3000/comparison?sessionId=5f68bd2ae4b05df9245d3a43
```

it goes to:

```
http://localhost:3000/study/comparison?sessionId=5f68bd2ae4b05df9245d3a43
```

(note the extra `/study` part of the route)

I traced it back to a problem in _getComparisonUrl_ --> _buildCBioPortalUrl_ where `AppConfig.baseUrl` does not seem to be defined. The return value of _getComparisonUrl_ is _http:/comparison?sessionId=5f68bd2ae4b05df9245d3a43_.

# Question

We need this transition to work for local-e2e tests. Can `AppConfig` be correctly initialized when running `yarn start`?

**Comment by alisman** [comment]
So, AppConfig is meant to be defined at runtime, not build time.  That way the same code artifacts can work anywhere as long as correct configuration is passed to them at runtime (on load of page).   

The problem here was that the paths were relative.  Adding a slash fixes the issue in my testing, both locally and also in portals that live in subdirectories, e.g. mskcc.cbioprotal.org/beta.
