### ISSUE TITLE
Should we turn on treatment functionality in study view on all portals?

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7928]

**Comment by inodb** [comment]
Let's test all the studies mentioned here: https://github.com/cBioPortal/datahub/issues/1262

**Comment by alisman** [comment]
@inodb test the treatment functionality?   (that ticket mentions the DECEASED data point but not treatment).

**Comment by alisman** [comment]
@Luke-Sikina can you take on the checking?

**Comment by Luke-Sikina** [comment]
lgg_ucsf_2014
  - Both charts display properly, but there is still a data issue where sample `P26_Pri_B` is associated with patient `P24` instead of `P26`. Until this is fixed, filtering won't work perfectly

 **gbm_columbia_2019** - no sample level data
- This is happening because there is no clinical_event_data with a `KEY` of `SAMPLE_ID` for this study.
- Separate checks for patient and sample treatments?
 
**thyroid_mskcc_2016** - no data
- The following query returns 0 rows, so no treatment charts are displayed:
```
SELECT
	clinical_event.PATIENT_ID
FROM
	clinical_event
	INNER JOIN clinical_event_data ON clinical_event.CLINICAL_EVENT_ID = clinical_event_data.CLINICAL_EVENT_ID
	INNER JOIN patient ON clinical_event.PATIENT_ID = patient.INTERNAL_ID
	INNER JOIN sample ON patient.INTERNAL_ID = sample.PATIENT_ID
	INNER JOIN cancer_study ON patient.CANCER_STUDY_ID = cancer_study.CANCER_STUDY_ID
WHERE
	sample.STABLE_ID = "thyroid_mskcc_2016"
	AND clinical_event_data.KEY = "AGENT"
```
 **mel_tsam_liang_2017** - no data
- The following query returns 0 rows, so no treatment charts are displayed:
```
SELECT
	clinical_event.PATIENT_ID
FROM
	clinical_event
	INNER JOIN clinical_event_data ON clinical_event.CLINICAL_EVENT_ID = clinical_event_data.CLINICAL_EVENT_ID
	INNER JOIN patient ON clinical_event.PATIENT_ID = patient.INTERNAL_ID
	INNER JOIN sample ON patient.INTERNAL_ID = sample.PATIENT_ID
	INNER JOIN cancer_study ON patient.CANCER_STUDY_ID = cancer_study.CANCER_STUDY_ID
WHERE
	sample.STABLE_ID = "mel_tsam_liang_2017"
	AND clinical_event_data.KEY = "AGENT"
```
 **sclc_cancercell_gardner_2017** - works
