### ISSUE TITLE
fusion feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8048]
Some thoughts from my first run through with the new SV data:

1) Are we planning to release this as-is before we finish the new SV tab? If so, then we will temporarily lose some functionality - currently the Mutations tab can be used to browse fusions, but now there's no place to do that.

2) We should remove the Fusion filter from the Mutations tab:
![image](https://user-images.githubusercontent.com/10508276/98727602-2b98c280-2366-11eb-9306-574a76031032.png)

3) This might be a data issue, but I would expect that this is actually gene1=ERG & gene2=TMPRSS2, but the reporting now makes it seems like 2 distinct intragenic events:
![image](https://user-images.githubusercontent.com/10508276/98727187-8bdb3480-2365-11eb-909f-cd64ced6cb27.png)
http://beta.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0006837

Here is the current one:
![image](https://user-images.githubusercontent.com/840895/99005121-3c843800-250e-11eb-949a-ec69ce50f896.png)
https://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0006837

4) This also might be data-related, but the OncoPrint looks very different for the same query

prod:
![image](https://user-images.githubusercontent.com/10508276/98727842-9649fe00-2366-11eb-9086-bcd5a751f079.png)

beta:
![image](https://user-images.githubusercontent.com/10508276/98727864-9d710c00-2366-11eb-901a-511fdfd0f91c.png)

5) "Structural variant data" is cut off
![image](https://user-images.githubusercontent.com/10508276/98727747-6b5faa00-2366-11eb-8383-3b97ab3f8af5.png)

6) Plots axis label should be "Structural Variants" rather than "Fusions"
![image](https://user-images.githubusercontent.com/10508276/98728486-90a0e800-2367-11eb-8c00-cd5dc7098084.png)

7) Results View/Comparison/SV has two Data Sets available for MSK-IMPACT (Fusions and mskimpact2017 SV data). Is there a difference? Do we expect studies to have multiple SV profiles? Or is this just an artifact of figuring out how to migrate SV out of mutations?

8) Downloads tab table should say "Structural Variants" not "Structural"
![image](https://user-images.githubusercontent.com/10508276/98729188-8a5f3b80-2368-11eb-9e86-082c67a5c195.png)

9) This might be related to 3&4, but there's something weird going on. I used study view to filter to samples with both TMPRSS2 and ERG SV (175 samples in MSK-IMPACT), then queried the same genes, and this is the OncoPrint I get:
![image](https://user-images.githubusercontent.com/10508276/98730287-102fb680-236a-11eb-9faf-ec4fa99af80f.png)
Why isn't TMPRSS2 marked purple in every sample?

**Comment by jjgao** [comment]
Thanks, @tmazor!

Discussed with @kalletlak - will fix them!

> Some thoughts from my first run through with the new SV data:
> 
> 1. Are we planning to release this as-is before we finish the new SV tab? If so, then we will temporarily lose some functionality - currently the Mutations tab can be used to browse fusions, but now there's no place to do that.

Potential solution: adding back the fusions into the Mutations tab. 

We will have a separate round of development and product review for releasing the SV/Fusions.

Let's remove the fusions once we release the SVs/Fusions tab (TODO: create an issue for this)

> 2. We should remove the Fusion filter from the Mutations tab:

We will do that later since we are adding them back.

Let's remove the Fusion filter once we release the SVs/Fusions tab (TODO: create an issue for this)

> 3. This might be a data issue, but I would expect that this is actually gene1=ERG & gene2=TMPRSS2, but the reporting now makes it seems like 2 distinct intragenic events:

Solution: determine gene1 & gene2 from protein change.

> 4. This also might be data-related, but the OncoPrint looks very different for the same query

Solution: depending on whether genes are included in the query, we will duplicate the fusion events per query gene. (this should be applied to both current fusions in mutation table and new structure_variant table)

> 5. "Structural variant data" is cut off

Will fix -easy!

> 6. Plots axis label should be "Structural Variants" rather than "Fusions"

We are displaying the the profile name. We should fix the meta data.

> 7. Results View/Comparison/SV has two Data Sets available for MSK-IMPACT (Fusions and mskimpact2017 SV data). Is there a difference? Do we expect studies to have multiple SV profiles? Or is this just an artifact of figuring out how to migrate SV out of mutations?

Solution: we will only show Fusions profile when available for the moment, ie. hiding SV profile. 

When there is only SV profile, we will still show it so that once we move the data, it will automatically show up. Clean up TO-DO: We should remove the logic about showing fusions over SV once we fully switch to SVs. 

> 8. Downloads tab table should say "Structural Variants" not "Structural"

Will fix - easy!

> 9. This might be related to 3&4, but there's something weird going on. I used study view to filter to samples with both TMPRSS2 and ERG SV (175 samples in MSK-IMPACT), then queried the same genes, and this is the OncoPrint I get:
>    Why isn't TMPRSS2 marked purple in every sample?

Related to 3&4 - same solution.
