### ISSUE TITLE
Signal transcript dropdown nr of mutations

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8062]
The number of mutations in the dropdown menu does not seem to match the ones displayed
<img width="1427" alt="Screen Shot 2020-11-16 at 8 18 59 AM" src="https://user-images.githubusercontent.com/1334004/99257125-8312b480-27e4-11eb-847b-699c89c4f110.png">
<img width="278" alt="Screen Shot 2020-11-16 at 8 20 22 AM" src="https://user-images.githubusercontent.com/1334004/99257186-9c1b6580-27e4-11eb-8549-7f8fb91bf9fc.png">

**Comment by onursumer** [comment]
- The table appears to be empty because of a pagination bug (which is fixed by cBioPortal/cbioportal-frontend#3505)
- The reason for an empty lollipop plot seems to be annotation related. We don't have protein change values for this transcript. Not sure if this annotation problem is easy to fix:

![NF1_transcript_witn_no_protein_change](https://user-images.githubusercontent.com/3604198/99385912-a3537980-289f-11eb-8ee2-3ebaa7216ee0.png)

**Comment by inodb** [comment]
Should be ok I think that the lollipop is empty if there are no protein change annotations. Closing for now. Thanks for fixing!
