### ISSUE TITLE
pathways in patient view feedback

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8078]
1) RB1 mutation is present and listed in tooltip, but there's no OncoPrint shown and RB1 isn't listed in the table on the right
![image](https://user-images.githubusercontent.com/10508276/99580865-fd426500-29ad-11eb-940f-d659c20f5acb.png)
https://deploy-preview-3458--cbioportalfrontend.netlify.app/patient/pathways?caseId=P01&studyId=lgg_ucsf_2014

2) Can we add a legend to define the colors in the OncoPrints?

3) \# Genes Matched column in the table should display integers rather than decimals

**Comment by jjgao** [comment]
4. Searching a gene is not working in the pathway list table

**Comment by ugurdogrusoz** [comment]
1. RB1 here is of type *family*. We display alteration data inside the node only when they are *genes*. @msalihaltun Please display tooltips only when the node is of type gene for consistency please.

2. @tmazor We already incorporate the legend under Help dialog:
![Screenshot 2020-11-24 105213](https://user-images.githubusercontent.com/3874988/100064204-4594d380-2e43-11eb-94cf-5ed8dbcedf32.png)

3. @onursumer @msalihaltun We should display # genes matched as integer as suggested. Make sure this is only done for the Patient view though since otherwise we have a score which can be non-integer (e.g. 66.67 percent).

4. @jjgao Search is for the *pathway name*. I wonder if you wanted to search the entire table and didn't find a match. @onursumer Is it easy to search for the entire table (other columns)? Maybe we should change this implementation/behavior?

**Comment by onursumer** [comment]
@ugurdogrusoz @jjgao @tmazor 1, 2, and 4 should be fixed now. Not sure if we need to do anything about 2.

Also, seems like this one is crashing: https://deploy-preview-3458--cbioportalfrontend.netlify.app/patient/pathways?sampleId=TCGA-13-1489-01&studyId=ov_tcga_pub. Probably related to Oncoprint data.

**Comment by ugurdogrusoz** [comment]
I confirm 1, 2, and 4 fixed. I think 3 is already there. So 5 (the new crash) is the only one left. @onursumer let us know if this is on our side.

**Comment by tmazor** [comment]
1. It would be great if we could display alterations within a family also - I realize that may get more complicated, but it would present a more complete picture of the data.
2. The legend looks a bit fuzzy - is that an image? If so, could it be higher quality? But more importantly, it looks like that same legend appears no matter what the data is - is that so? (I tried to test with more samples but kept hitting the crashing issue Onur mentioned). The one example I could come up with was this case: https://deploy-preview-3458--cbioportalfrontend.netlify.app/patient/pathways?caseId=P18&studyId=lgg_ucsf_2014 With RTK-Ras pathway, you can see a light grey mutation in ERBB4, but that's not represented in the legend. The legend needs to match the data that's shown.
3. When discussing this with @schultzn , we talked about changing this column to a binary call rather than the number of genes. I still think that's a good idea - @schultzn do you agree?
4. Looks good
5. I'm also having crashing issues:
https://deploy-preview-3458--cbioportalfrontend.netlify.app/patient?studyId=lgggbm_tcga_pub&caseId=TCGA-74-6584
![image](https://user-images.githubusercontent.com/10508276/100935557-3efb0180-34be-11eb-89a6-6c6383ec8dd2.png)

**Comment by ugurdogrusoz** [comment]
1. What if the family name and the gene names in that family do not match  or map as one-to-many (RAS family vs. KRAS, HRAS, etc.)? Besides, this would require a significant change in PathwayMapper as we currently do not display alteration frequencies in any views for families. So I suggest we leave this as is.

2. Thanks for noticing this. We didn't realize the legend for the Oncoprint was being produced dynamically and took a screenshot from a random Oncoprint; that's why we're missing certain types. We should either collect all possible alterations into a single image or display this legend dynamically like it's done in the Oncoprint. Can this be done dynamically in this view's help dialog @onursumer? Btw, the image is being displayed larger than the scale it was taken at resulting in this fuzziness, could be easily fixed. @msalihaltun will work with @onursumer on this.

3. I suggest we leave any changes here for later as well unless it's trivial. Such requirements should be communicated early on before implementation.

4. Done 

5. @onursumer will investigate this.

In general, we'd like to put this round behind and start planning the next round of changes. In the next round we will do some code cleanup and refactoring. And it'd be great to see a list of requirements from you so they can be taken into account during the planning of the re-architecturing effort.

**Comment by onursumer** [comment]
2. @ugurdogrusoz @msalihaltun It should be possible to dynamically generate a legend, but we need to investigate if we can easily reuse the code that generates the legend for Oncoprint. It's probably easier at this point to collect all possible alterations and draw them as an SVG component rather than an image within PathwayMapper codebase.

3. If we really want this, a quick workaround could be to convert numbers to boolean values. Something like `if # Genes matched > 0 display true; else display false` may work.

**Comment by onursumer** [comment]
@ugurdogrusoz @tmazor I was able to fix the crash issue. Looks like with the recent changes in master, some cBioPortal endpoints somehow got slower. For certain queries now it takes longer to load the pathways tab.

**Comment by inodb** [comment]
@onursumer good find Onur - do you know which endpoints are slower? There are some changes to the APIs in v3.5.0 as well as the mysql schema

**Comment by onursumer** [comment]
@inodb For example for [this one](https://deploy-preview-3458--cbioportalfrontend.netlify.app/patient/pathways?caseId=00-010&studyId=prad_fhcrc), the endpoint https://www.cbioportal.org/proxy/oncokb/annotate/copyNumberAlterations takes about 1-2 minutes to complete. But, this one is actually an OncoKB endpoint. Not sure if this is because of the latest changes in master or a problem with OncoKB service.

**Comment by tmazor** [comment]
1. Sure, I'm fine with leaving this as-is for now - I would just suggest that it's a worthwhile improvement to work on in the future.
2. A dynamic legend would be my preference, but if that's too difficult then a comprehensive SVG legend is fine.
3. If @onursumer 's suggestion is easy to implement, I think that's exactly what we need. Call the column "Pathway altered" and then it can be true if the gene count is >0 and false otherwise.
5. Hooray for no more crashing!
6. Absolutely, happy to contribute some thoughts earlier on in the process.

**Comment by msalihaltun** [comment]
@tmazor @onursumer we can generate an oncoprint legend as follows. 
![Screenshot from 2020-12-10 17-00-35](https://user-images.githubusercontent.com/26147738/101782873-9b879d80-3b0a-11eb-8c91-fecb96543fa7.png)

Can you please check if this legend is comprehensive, and whether or not there are mistakes in it?

**Comment by tmazor** [comment]
Are all of those actually alteration types that could appear in this plot? I suspect mRNA and Protein are not shown here and therefore shouldn't be in the legend. Copy number alterations don't get driver-vs-VUS annotations in OncoPrint. Also can Gains and Shallow Deletions appear here? I suspect those also cannot appear and so shouldn't be in the legend.

**Comment by onursumer** [comment]
@tmazor good point! Currently we only show mutation, fusion, and copy number alteration. I don't think we have mRNA, Protein, driver-vs-VUS, Gain, or Shallow Deletion.

**Comment by ugurdogrusoz** [comment]
Why don't you tell us (by marking on the legend?) exactly what needs to go please?

**Comment by tmazor** [comment]
@onursumer From what I've seen, it looks like mutation driver-vs-VUS is being used - can you confirm? For example the colors for PIK3CA vs FGFR2 here: https://deploy-preview-3458--cbioportalfrontend.netlify.app/patient/pathways?studyId=lgggbm_tcga_pub&caseId=TCGA-02-0033

@ugurdogrusoz: Assuming @onursumer confirms my assumptions above, here are my edits to the legend:
![image](https://user-images.githubusercontent.com/10508276/101957229-0c908900-3bcf-11eb-8061-b45ba2d5871d.png)

**Comment by onursumer** [comment]
@tmazor do you think all the issues listed here has been fixed now with the latest update?

**Comment by tmazor** [comment]
@onursumer @ugurdogrusoz looks good to me!

I did have one additional thought (which does not need to block deployment) which is that we don't have any information on this page about how driver vs VUS is defined. I assume it's the default settings of OncoKB & cancer hotspots?

**Comment by onursumer** [comment]
@tmazor Good point. I am not entirely sure but it should be the same as the results view default settings for Oncoprint. I just made the Oncoprint data generator functions compatible with the patient view data. I don't really know the details beyond that.

**Comment by tmazor** [comment]
@onursumer maybe we can just add that text to the help menu? Under the legend, it can say:
"Putative driver and unknown significance annotations are based on data from OncoKB and CancerHotspots.org."

Ideally users should be able to control those settings like they can in results view, but that's obviously a whole other set of work.
