### ISSUE TITLE
Group comparison ignores selected groups

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#8103]
Trying to select two cancer types in cancer type table, then start a comparison.

![image](https://user-images.githubusercontent.com/11892704/101387399-6110cd00-388c-11eb-83a2-3de37da3924a.png)

**Comment by adamabeshouse** [comment]
@schultzn For various reasons this is actually difficult to fix. The comparison group page loads with the correct groups but it's harder to flash this warning because of which part of the application knows what. Is it alright to just drop the error message? I think that people will put it together when they get to a page and see the top 20 groups.

**Comment by schultzn** [comment]
When I ran this last week, it actually showed 20 groups in the comparison (did not include the link or screenshot unfortunately). When I try this query now, comparing low grade to high grade serous ovarian cancer, I get the same warning message, but the group comparison then only shows one group, not the expected two. Link and screenshot below.

https://www.cbioportal.org/comparison?sessionId=5fda9e55e4b0242bd5d32bf8

![image](https://user-images.githubusercontent.com/11892704/102420610-86aa7e80-3fd0-11eb-8f7a-13f54acfdc2f.png)

**Comment by adamabeshouse** [comment]
Hmm, that is weird

**Comment by jjgao** [comment]
I tried it but couldn't reproduce. @adamabeshouse were you able to reproduce the error Niki reported in the original post?

**Comment by adamabeshouse** [comment]
@jjgao I reproduced the second one but couldn't reproduce the first one
