### ISSUE TITLE
breadcrumb not showing up in rc branch

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#817]
It looks like breadcrumb is not showing up any more in the RC branch. The style of some buttons are also messed up.

@pieterlukasse or @aderidder: could you please help on this?

**Comment by aderidder** [comment]
Hi @jjgao,
I think most of the problems are being caused by bootstrap.min.css now being included in the study-view (cs_include_standard.jsp and dcplots.jsp). This has affected the Query By Gene pop-ups.
Also there have been some changes to study-view.css; one of them is the removal of the .hidden class, which the breadcrumbs were using. 
Still have to look into the buttons. However, I'm on holidays next week...

**Comment by jjgao** [comment]
@aderidder thanks for looking to this. @zhx828 is also on vacation. Please comment if you find anything else.

**Comment by zhx828** [comment]
@aderidder Bootstrap has hidden class by default. I changed the hidden class name to study-view-hidden in study-view.css You could use this class name.

**Comment by pieterlukasse** [comment]
@jjgao : I will check this now

**Comment by pieterlukasse** [comment]
@jjgao : I made a PR #837 for the style. 
I did not yet change the style of any buttons yet, maybe you can indicate which buttons specifically? I say that "query this study" button spacing looks strange. Is this what you mean or are there other things?  Thanks.
