### ISSUE TITLE
Validator: enable 3 modes of validation

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#822]
The validator script should have the following 3 modes:

- [x] \(1) Basic checks mode: validator only checks the basic things in the files, like format, presence of required fields, valid sample ids. Basically all standalone checks that do not require external data.
- [x] \(2) All checks mode, with external data in static files: validator does all checks done in 1 plus extra checks to validate the used gene symbols, the specified clinical attributes and the given cancer type (if given). For these checks, it expects gene, clinical attributes and cancer types data to be available in a set of predefined local files. An extra script should also be added to cbioportal to easily generate these files to be shared with other users.
- [x] \(3) All checks mode, with external data coming from cbioportal server: same as 2, but external data is retrieved via the /api/* webservices from the local cbioportal server. **This is the way the validator currently works**

**Comment by fedde-s** [comment]
@pieterlukasse @priti88 @ecerami In commit thehyve/cbioportal@8c67f3f141dba43ec22e8cb57a1c3bd762fbecb2 I merged in the `--no_portal_checks` flag to make the validation script skip any tests requiring data from the portal, i.e. 'mode 1'. These commits are included in pull request #798 which is under review by @priti88.

**Comment by priti88** [comment]
@fedde-s : Mode 1 looks great except for one comment:
1) Mutation file throws error for missing columns: Variant_Type, Protein_position, SWISSPROT
These does not seem to be required columns and user might not have them.

**Comment by fedde-s** [comment]
@priti88 These columns were established to be required by cBioPortal in an email conversation with Ben and Onur, please see and comment on issue #806

**Comment by priti88** [comment]
@ecerami Any thoughts?

**Comment by fedde-s** [comment]
@priti88 @ecerami as of commit thehyve/cbioportal@14d2a104e02e1b3c838bd5c8f93738397b57a0dd, the validation script supports reading files from a local directory of JSON files instead of calling the web API. The script to generate this directory in one go is not yet available, but for now you should be able to test it by logging in to your cBioPortal installation, and using the same browser to open `<URL to your portal>/api/cancertypes`, `<URL to your portal>/api/clinicalattributes/patients`, `<URL to your portal>/api/clinicalattributes/samples`, `<URL to your portal>/api/genes` and `<URL to your portal>/api/genesaliases`, and saving the text files to a directory with the filename extension `.json`. Replace the last slash in the name of the clinical attribute APIs by an underscore, as shown in the example on https://github.com/thehyve/cbioportal/tree/14d2a104e02e1b3c838bd5c8f93738397b57a0dd/core/src/test/scripts/test_data/api_json_unit_tests
