### ISSUE TITLE
Validator Issue : Clinical Headers

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#832]
All Headers Required for every clinical attribute.
Throw a warning if Display name, Description, attribute type does not match with the database.

**Comment by pieterlukasse** [comment]
@priti88 : good idea. Just to elaborate on it a bit more: this is what the code should do:
- [ ] existing clinical attributes should **not** be overwritten by the loader
- [ ] the warning will be something like: WARNING: Display name of attribute <attribute_name> does not match the name in the DB. The name in DB is leading, therefore the name you have given (<name given>) will be ignored and the DB name will be used instead.

**Comment by fedde-s** [comment]
Since thehyve/cbioportal@626495d8b652a0caf569dd9ad40679520607fe0e, this scenario generates the warning “`<field>` definition for attribute '`<attribute>`' does not match the portal, and will be loaded as '`<portal definition>`', after which it is validated accordingly. I.e., if the portal says the attribute is a number, non-numeric values yield errors.

**Comment by fedde-s** [comment]
@aderidder, I believe you tested whether the importer does indeed work like this?

**Comment by aderidder** [comment]
yes, existing clinical attributes are not overwritten by the loader

**Comment by pieterlukasse** [comment]
the following commit was probably also crucial for this: https://github.com/cBioPortal/cbioportal/commit/118ad21

**Comment by pieterlukasse** [comment]
solution merged
