### ISSUE TITLE
Investigate genie-private downtime

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8464]
- [x] investigate potential cause of bin calculation (can't be only cause tho)
- [x] Investigate other causes

The downtime on GENIE private portal for the v10.2 cohort seems to have been related to the new bin calculations. Reverting back to v3.6.7 seems to have solved the issue. Need to investigate further if this is really the cause of the downtime, but at this stage it seems like the most likely candidate

we also want to try / consider reverting #7597 .. for genie 10.3 release performance rescue (this is fusion/SV migration)

CC @onursumer @alisman 

Associated PR: https://github.com/cBioPortal/cbioportal/pull/8432

**Comment by inodb** [comment]
@kalletlak maybe can investigate this with e.g. @sheridancbio or @averyniceday

**Comment by sheridancbio** [comment]
The problem is reported related to the genie-private portal. Opening the home page of the genie private portal was not overly slow (although definitely not fast). Opening the study view of the study "Cohort v10.3-consortium" processed the download of data for the various graphs for 6 minutes. At the end of 6 minutes, the Mutated Genes table and Structural Variant Genes tables were rendered. However the following graphs / tables failed to render and ended with a message "Error when loading data" :
"Mutation Count vs Fraction of Genome Altered"
"Fraction Genome Altered"
"Age at Which Sequencing was Reported"
"Interval in days from DOB to DOD"
"Sequence Year"
"CNA Genes"

**Comment by sheridancbio** [comment]
In comparison, the public genie portal loaded the largest study (Cohort v9.0-public) with 112,935 samples loaded the study view completely and successfully in about 2 minutes.
the Cohort v10.3-consortium contains 120,809 samples.

In the footer of the main page, both portal report v3.6.12
The /api/info endpoint of both portals report backend version "portalVersion": "3.6.12-dirty-SNAPSHOT"

**Comment by sheridancbio** [comment]
Investigation has us convinced that the redis caching is not working for genie-private. The redis-persistence-cache helm deployment was probed and showed only these caches defined at the top level:
127.0.0.1:6379[4]> keys *
1) "genie-archive-portalGeneralRepositoryCache"
2) "public-portalGeneralRepositoryCache"
3) "genie-public-portalGeneralRepositoryCache"
4) "public-portalStaticRepositoryCacheOne"

So it appears that public-portal may be running correctly, having both the General and Static caches present. But oddly, the genie-archive-portal has only the General cache. And then the genie-public-portal has only the General cache. We are confused about what happened to the second cache for these two portals ... but the genie-private portal is showing no caches at all. Looking into the contents of the public-portal caches it looked plausible that this was an actual cache for a running portal.

**Comment by sheridancbio** [comment]
we confirmed that the public-portal cache is non functional right now : a query made to the gene api endpoint was not entered into the cache public-portalStaticRepositoryCacheOne. So it appears the whole redis server is non-functional.

**Comment by sheridancbio** [comment]
we tried deleting the cache keys and restarting portals .. this did not lead to a reconnection with redis caching for the portals. Switching the database index number also failed to allow caching with a newly deployed portal. So we believe an entirely new helm deployment of reds is needed.

**Comment by inodb** [comment]
let's figure out what to do with this ticket, since it seems like we've investigated the original description enough.

**Comment by sheridancbio** [comment]
involvement of the backend pipeline team in this issue extended into a discovery that the redis persistence caching was no longer functioning, and identification of a coding problem in the cbioportal code base which prevented redis caching from functioning correctly when a docker image was constructed (as it automatically is) packaging the portal.properties.EXAMPLE file as the portal.properties.

The problem was that the setting for persistence.cache_type, if present in portal.properties during build, would be injected into the web.xml as a fixed setting via the maven filtering mechanism, preventing adjustment with -D java property setting during docker image startup. This was temporarily remedied by building images from a cbioportal branch `genie-cache-patch` which removed the setting of the property in portal.properties.EXAMPLE and also relocated repository functions for gene-panel-data from the generalRepositoryCache into staticRepositoryCacheOne (generally reserved for use to hold gene information).

It is not known whether relocating these persistence level functions into the static cache will lead to increased residency in the cache, because redis caching does not specify reserved heap/disk limits on a per-cache basis (as with Ehcache).

At this point, the redis cache of the backend had be restored to normal function and other teams began to look into code improvements in the persistence layer for gene-panel-data calls, and also using precomputed responses as a web request level alternative source from outside the backend server.

The backend pipeline team has been looking into other redis stability issues in the msk-portal, and is not actively engaged in this issue currently, but may return to it when the path forward is clarified.
