### ISSUE TITLE
filtering VUS with struct var in oncoprint issues

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8473]
This query: https://bit.ly/3cCFsKk

OncoPrint looks like this:
![image](https://user-images.githubusercontent.com/10508276/113038577-ae2eec80-9164-11eb-8505-1e1441b8c0c8.png)

Then I filter to hide VUS:
![image](https://user-images.githubusercontent.com/10508276/113038610-b4bd6400-9164-11eb-855a-f46f70c812d9.png)

And I get this:
![image](https://user-images.githubusercontent.com/10508276/113038634-bab34500-9164-11eb-8826-9f3ab5a00f88.png)

There are a few things here:
1) The text in the blue box says '3 mutations of unknown significance...' --> this needs to also include structural variant. Or maybe be made more general and just say 'alterations' ? I can't remember how this text changes when CNA are also filtered out.
2) The text in the dropdown menu also needs to include structural variants
3) The filtering is weird. It looks like ALK-EML4 fusions were filtered out for ALK but not EML4. The tooltips suggest why that's happening:

Tooltip for ALK:
![image](https://user-images.githubusercontent.com/10508276/113039197-652b6800-9165-11eb-8638-cb5c4dfb8b7e.png)

Tooltip for same patient EML4:
![image](https://user-images.githubusercontent.com/10508276/113039218-6bb9df80-9165-11eb-8d3b-579aef12f644.png)

The EML4 tooltip correctly calls it an ALK-EML4 SV that is in OncoKB, but the ALK tooltip says ALK-ALK

If I go to the patient page, I see one EML4-ALK SV:
![image](https://user-images.githubusercontent.com/10508276/113039706-f8fd3400-9165-11eb-9973-0b9658a39fc8.png)

I don't know how this is all stored, so I'm not sure if this is a data issue or not, but something is going wrong here.

**Comment by kalletlak** [comment]
Fixed in https://github.com/cBioPortal/cbioportal-frontend/pull/3358
New tooltip
![Screen Shot 2021-04-01 at 2 20 31 PM](https://user-images.githubusercontent.com/12956870/113361907-0e678f00-931b-11eb-88a8-f5fc61b760eb.png)


> There are a few things here:
> 
> 1. The text in the blue box says '3 mutations of unknown significance...' --> this needs to also include structural variant. Or maybe be made more general and just say 'alterations' ? I can't remember how this text changes when CNA are also filtered out.

Done. Message would still be the same as none of the SV's are filtered out. If they are filtered then it would be indicated in the message. Example: `3 mutations and copy number alteration of unknown significance...`
> 2. The text in the dropdown menu also needs to include structural variants

Updated
<img width="246" alt="Screen Shot 2021-04-01 at 6 53 46 PM" src="https://user-images.githubusercontent.com/12956870/113362126-9cdc1080-931b-11eb-8788-63500fc0ecf0.png">

> 3. The filtering is weird. It looks like ALK-EML4 fusions were filtered out for ALK but not EML4. The tooltips suggest why that's happening:

Fixed
