### ISSUE TITLE
Study View Clinical Data tab React Table issues

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/cbioportal#850]
There are still some issues with #695:

- [x] patient and sample IDs are not clickable (how do you get to patient view?)
- [x] column widths are set to a hardcoded number (we could be smart about it and calculate something - age doesn't have to be full width)
- [x] column widths can't be changed
- [x] it's impossible to copy contents of the cell if they overflow
- [x] why is the ordering of the columns random?

**Comment by zhx828** [comment]
@j-hudecek  I'm adding the auto width for the library. But for the bigger dataset, I would suggest to predefined the column width, otherwise it's going to be very slow. (I tested the 10000 samples + 400 attributes, the table will never be generated)
The way I used to check the cell/header content length is:
```
var ruler = $('#ruler');
ruler.text(label);
ruler.css('font-size', _fontSize);
ruler.css('font-weight', _fontWeight);
labelWidth = ruler.outerWidth();
```
If we could find better way to do so, please let me know.

**Comment by j-hudecek** [comment]
Perhaps we could do use something hacky like "add 10px for each character" and only look at the first 30 rows. That shouldn't be a performance problem.
I think the easiest way how to make it usable is to allow changing of the column width by the user.

**Comment by zhx828** [comment]
@j-hudecek I have that. The library will support autoColumnWidth: true/false + columnMaxWidth: (width) in the table configuration parameters. You can also specify your columnWidth as well. If columnWidth has been specified, the autoColumn will be disabled.

For large dataset (100000 cells ), I has simply used string length * 12

**Comment by pieterlukasse** [comment]
@zhx828 I removed the last two items from the list here, since they are not related to the clinical data tab, but to the main Study view tab:

- [ ] Issue: if you sort the table and then click on a gene to select it, the sorting is reset. (moved to #1350)
- [ ] Issue: we're trying to make cbioportal 508 compliant. The checkboxes are not compliant due to them not having a label. One easy solution is to give them the title attribute, which suffices for 508  (moved to #1351)
