### ISSUE TITLE
mutations tab germline mutation rate selection box does not work as expected

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8607]
Try e.g. selecting germline mutations in EGFR here:

https://bit.ly/3byO0RD

<img width="832" alt="Screen Shot 2021-05-17 at 7 56 40 PM" src="https://user-images.githubusercontent.com/1334004/118570470-3a639600-b74a-11eb-87ef-a4cc4245e2e6.png">

Even though the germline mutation rate > 0 you don't see any mutations in the lollipop plot. If you however search for germline in the mutations table you do see the mutations show up in the lollipop plot

**Comment by onursumer** [comment]
@inodb Actually somatic filter doesn't work as expected either. This is because mutation status data is all caps for this study (`SOMATIC` and `GERMLINE` instead of `Somatic` and `Germline`). Therefore the default mutation status filter function doesn't work. The table search function, on the other hand, is case insensitive so it is still functional.

We can fix this by ignoring the case within the default mutation status filter as well but ideally data should be normalized.
