### ISSUE TITLE
Call samples endpoint earlier (if possible)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#8615]
I think we should be able to call samples endpoint earlier in load process.  I.e. it appears we are deferring/awaiting unecessarily.   This is a bottleneck.  The request two above is sample_lists call, but i don't think we should need that to call samples because the sample_list_id is a parameter in URL.
![image](https://user-images.githubusercontent.com/186521/118861977-1cfa0d80-b8ab-11eb-803c-42d2b66587aa.png)

**Comment by alisman** [comment]
@adamabeshouse make sure to consider different scenarios.  like custom sample lists, etc.

**Comment by adamabeshouse** [comment]
@alisman whats the test url you're using? in certain queries this is unavoidable because the sample list specified in the url is actually a sample list *category*, e.g. profiled for muts, profiled for cna, and then we fetch the sample lists for all the queried studies in order to find the relevant sample lists.
