### ISSUE TITLE
Cancer Type Summary for MSK-IMPACT looks incorrect

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#868]
When MSH2 gene is queried for MSK-IMPACT, the cancer type summary graph looks:
![screen shot 2016-02-25 at 4 19 56 pm](https://cloud.githubusercontent.com/assets/12007862/13334844/fab61f68-dbdb-11e5-88fb-ec1877c94896.png)

**The top most tumor type is penile cancer whereas study summary says colorectal is most affected**

![screen shot 2016-02-25 at 4 20 32 pm](https://cloud.githubusercontent.com/assets/12007862/13334854/0b9f1460-dbdc-11e5-8f91-aab1dd1c7f2b.png)

**Comment by jjgao** [comment]
It's because there is one out of 8 (12.5%) penile cancer patients with MSH2 mutation. Note that the two frequencies in the table in study view and in the Cancer Type Summary are different: the denominator in study view is the number of selected samples; that in the Cancer Type Summary is the number of samples of the tumor type.

**Comment by ritikakundra** [comment]
Thanks!
