### ISSUE TITLE
Make releases available to maven

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#873]
It would be good to have the releases (now recorded at https://github.com/cBioPortal/cbioportal/releases) and their respective artifacts available as a "repository" for maven. This simplifies building new external Java projects that include cBioPortal as a dependency. 

Ideally we let `travis` do this.

**Comment by pieterlukasse** [comment]
Shared by @jjgao :  https://malalanayake.wordpress.com/2014/03/10/create-simple-maven-repository-on-github/

Maybe this could work if we let travis push up the artifacts to github?

**Comment by pieterlukasse** [comment]
http://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci
and
https://docs.travis-ci.com/user/deployment/releases/
and use use `maven-scm-plugin` ? Or is `maven-scm-plugin` maybe not necessary after all?

**Comment by pieterlukasse** [comment]
@aderidder can help test it as he would like to build another project using cBioPortal as dependency.

**Comment by inodb** [comment]
@pieterlukasse / @aderidder  Is this still something you want to do? Just looked at it today. Excuse the delay

You can actually already use cBioPortal as a dependency if you build it separately first since the artifacts are stored in `~/.m2/org.mskcc/something` (as far as I understand). See for instance @morungos solution: https://github.com/pughlab/cbioportal-octane-overlay

Now if you want to resolve the dependency automatically, instead of building it yourself, we could maybe use jitpack: https://jitpack.io/. Would require some trivial changes to make the building work (use i.e. `portal.properties.EXAMPLE` by default).

**Comment by inodb** [comment]
Ok actually solved this using jitpack, further discussion on #1798

**Comment by pieterlukasse** [comment]
Hi @inodb , the original purpose was to have .jar files available for download, so that people working on preparing the datasets would not need to go through the steps of building cbioportal just to use some of the helper classes that are part of the scripts package. See #810

But having the build artifacts available for download will also simplify other steps, such as installation. 

The jitpack idea might solve this. Where can I find the artifacts?

**Comment by pieterlukasse** [comment]
Ah, found it: https://jitpack.io/com/github/inodb/cbioportal/scripts/v1.3.0-test-jitpack/scripts-v1.3.0-test-jitpack.jar

Nice! 👍

**Comment by pieterlukasse** [comment]
@inodb your solution solves the problem! We can close this issue once we merge your PR 👍
