### ISSUE TITLE
Oncoprint does not show amplifications when querying multiple genes

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8817]
Not sure exactly under what conditions amplifications don't show up, but basically there are no CCNE1 amplifications in this query with multiple genes:

https://cbioportal.mskcc.org/results/oncoprint?plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=610c557be4b015b63e9f8eb5

Even though the discrete copy number api does return ccne1 amplifications in the response

It works fine when querying CCNE1 by itself:

https://cbioportal.mskcc.org/results/oncoprint?plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=610c5567e4b015b63e9f8eb4

And also if you remove SETD2 and AKT2 from the first query:

https://cbioportal.mskcc.org/results/oncoprint?plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=610c5f5de4b015b63e9f8ec6

**Comment by adamabeshouse** [comment]
I believe what we're running into here is that the queried data is just too huge and something is going wrong in receiving it. I'm guessing that adding those two genes just tips it over the threshold where it fails. Notice that it's not just CCNE1 that loses its CNA's, several of those genes have CNA.

I think the problem is something we did for performance optimization via caching. We have this strategy now where we preload all the data for a profile, and then filter for the data relating to the queried samples. The goal of that is to be able to cache that data and save backend time. It works except when the study is massive like mskimpact. The query where CNAs appear has 1.6 million molecular data objects, I'm guessing that adding those extra two genes just pushes it past the limit.

![image](https://user-images.githubusercontent.com/636232/128436178-30d59db0-8a72-4383-a13b-64f9fb805d5f.png)

@alisman
