### ISSUE TITLE
query session not working

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8920]
report by [a user](https://groups.google.com/g/cbioportal/c/_0xyNqwy_WQ/m/h8PFgpOmAQAJ)

http://www.cbioportal.org/results?plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=6149d140e6ebe01a6ee32224

**Comment by alisman** [comment]
@dippindots can you take a look at why structural variants service is failing?  seems like maybe because of empty sampleMolecular identifiers, but why?  not that this query has a custom list of samples.  maybe none of them belong to a study with structural variant data?  then maybe we don't submit this unless there are samples?

![image](https://user-images.githubusercontent.com/186521/145603335-9899f7e6-9d1a-49f5-88e4-2b68f96d3fb5.png)

**Comment by dippindots** [comment]
@alisman Sure, I will take a look today
