### ISSUE TITLE
study view crashes when I apply this particular filter

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#8969]
I was browsing for clinical attributes, so I loaded study view with many TCGA studies. Study view loads just fine. Then I added a chart for BRCA1 Germline Mutation. Then I tried to apply a filter based on BRCA1 Germline Mutation (values 0 or 1, excluding NA), at which point the page crashes. Screenshot of the error in console is below.

https://www.cbioportal.org/study/summary?id=laml_tcga%2Claml_tcga_pub%2Cacc_tcga%2Csarc_tcga_pub%2Cbrca_tcga_pub2015%2Cbrca_tcga%2Cbrca_tcga_pub%2Ccesc_tcga%2Cchol_tcga%2Ccoadread_tcga%2Ccoadread_tcga_pub%2Cesca_tcga%2Cstes_tcga_pub%2Chnsc_tcga%2Chnsc_tcga_pub%2Ckich_tcga_pub%2Ckich_tcga%2Ckirc_tcga%2Ckirc_tcga_pub%2Ckirp_tcga%2Clihc_tcga%2Cluad_tcga%2Cluad_tcga_pub%2Clusc_tcga%2Clusc_tcga_pub%2Cdlbc_tcga%2Cskcm_tcga_pub_2015%2Cmeso_tcga%2Cov_tcga%2Cov_tcga_pub%2Cnsclc_tcga_broad_2016%2Cpaad_tcga%2Cthca_tcga_pub%2Cpcpg_tcga_pub%2Cprad_cpcg_2017%2Cprad_tcga_pub%2Cprad_tcga%2Cmixed_msk_tcga_2021%2Csarc_tcga%2Cskcm_tcga%2Cstad_tcga%2Cstad_tcga_pub%2Ctgct_tcga%2Cthym_tcga%2Cthca_tcga%2Cucs_tcga%2Cucec_tcga%2Cucec_tcga_pub%2Cuvm_tcga

![image](https://user-images.githubusercontent.com/10508276/137034100-4bfcbfe8-3aed-473c-9b38-f1dfd174b342.png)

FWIW, that clinical attribute is from prad_tcga_pub, and when open just that study and apply the filter, it works fine -- so it's something about having multiple studies that seems to be the issue.

**Comment by adamabeshouse** [comment]
@tmazor just getting to this - how do you add a BRCA1 Germline chart?? I'm not familiar with that functionality

**Comment by onursumer** [comment]
@adamabeshouse you can just use the `Charts` dropdown :)

<img width="579" alt="charts_dropdown" src="https://user-images.githubusercontent.com/3604198/140163325-6a9f33f5-db7d-4bbd-929b-03740ac2c8f4.png">

**Comment by tmazor** [comment]
@adamabeshouse it's just a clinical attribute for one of the studies in that query, so just go to 'add charts'

**Comment by tmazor** [comment]
whoops @onursumer beat me to it :)

**Comment by adamabeshouse** [comment]
oh it's a clinical chart :) thanks!

**Comment by adamabeshouse** [comment]
so the problem here is this line:

https://github.com/cBioPortal/cbioportal-frontend/blob/24350613312d41a212681b96af7e8debb40519bd/src/pages/studyView/StudyViewPageStore.ts#L5016

We're determining which generic assay tabs to show in the add chart dropdown based on which profiles have filtered samples in them. So when we filter 0 1 on BRCA1 Germline, it ends up filtering out all samples that are part of the generic assay profile. This leads to an undefined where we don't expect an undefined to be, which causes the crash.

So to fix this, we need to decide how we want to handle this feature. Do we still want to filter out add chart tabs based on the current filter state?
