### ISSUE TITLE
missing co-expression results for miRNAs and phosphoproteins

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#8988]
e.g. we cannot reproduce anymore. https://www.youtube.com/watch?v=YUxVv6pkxD4&t=2226s

Is it possible that the recent performance improvements has dropped all "non-genes" by accident?

@Luke-Sikina

**Comment by adamabeshouse** [comment]
how urgent is this? I may have bitten off more than I can chew with this one

**Comment by onursumer** [comment]
Seems like the problem is that `geneticEntityId` values are negative for all entities in this query:

https://www.cbioportal.org/api/molecular-profiles/co-expressions/fetch?molecularProfileIdA=gbm_tcga_pub_mrna&molecularProfileIdB=gbm_tcga_pub_mirna&threshold=0

We should further investigate and fix the issue in the backend.

**Comment by onursumer** [comment]
The reason that we don't have valid mapping for miRNAs in the frontend is that we switched using `ReferenceGenomeGene` instead of `Gene` at some point. `ReferenceGenomeGene` data does not have any information for miRNAs whereas `Gene` data has.

cBioPortal/cbioportal-frontend#4039 uses the `Gene` data as a workaround for this problem. This solution is probably not the best because it increases the initial tab load time.
