### ISSUE TITLE
Structural Variant Genes Table does not show up for archer

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9011]
https://cbioportal.mskcc.org/study/summary?id=mskarcher
<img width="394" alt="Screen Shot 2021-10-28 at 11 48 20 AM" src="https://user-images.githubusercontent.com/1334004/139290950-f4a75f07-5770-49a5-a3df-4df1c6950582.png">

There is a SQL error:

```
### The error may exist in URL [jar:file:/target/tomcat.8888/webapps/expanded/WEB-INF/lib/persistence-mybatis-0-unknown-version-SNAPSHOT.jar!/org/cbioportal/persistence/mybatis/AlterationCountsMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT              ENTREZ_GENE_ID AS entrezGeneId,             HUGO_GENE_SYMBOL AS hugoGeneSymbol,             COUNT(*) AS totalCount,             COUNT(DISTINCT(CASE_ID)) AS numberOfAlteredCases         FROM         (                        ) as JoinedTable                    GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL;
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as JoinedTable

        GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL' at line 9
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as JoinedTable

        GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL' at line 9
```

**Comment by n1zea144** [comment]
Tracked this issue to a [PR](https://github.com/cBioPortal/cbioportal/commit/57ba0da5688f65edea94f1f575c7f3f000db06a4#diff-08afdb4f4c71fd6c039131cf859f92f82ac10693a96833599243e83106cb908e) made in July to fix dropped SV's from the table in on the StudyView(??):

![image](https://user-images.githubusercontent.com/366003/139487773-1d9f8237-bf91-40b1-86a3-b9b2a6c76bd0.png)

In the Archer cohort, there is no STRUCTURAL_VARIANTS key so the list of sample ids is clobbered (which causes the SQL exception).

Before code is run groupedIdentifiersByProfileType has a valid value for "MUTATION_EXTENDED" key:

![image](https://user-images.githubusercontent.com/366003/139488190-2ac30099-1aed-477b-9d31-32e768878087.png)

but after code is run, it is null:

![image](https://user-images.githubusercontent.com/366003/139488264-5657b6d3-5a4c-46da-b83f-917f14e6de60.png)

I checked if this code is required by the mskimpact study, but the code is never invoked because the datatype for mutations profile is "MAF":

![image](https://user-images.githubusercontent.com/366003/139488405-2384a44a-24d0-4ee7-b188-9212c415fc2d.png)

I'm not sure why this code was introduced.  At least, we should update this code to check that groupedIdentifiersByProfileType contains a STRUCTURAL_VARIANTS key/value before we use it to set the value of the MUTATION_EXTENDED key....but I wonder why its there.  @ao508 can you shed light on this?

**Comment by ao508** [comment]
@n1zea144 

Digging into this.. 

Some related changes I noticed that were made after my PR in July:

PR #8841 by @kalletlak and specifically this chunk [here](https://github.com/cBioPortal/cbioportal/commit/43cae4f07b94597f7aa1b387787b9656c422eba4#diff-fbc96886e4d49a762998bd7e4f177373ef17bbb7442bdbdb02cc8fc35de5954eR221) in `GenePanelServiceImpl`   - the logic at L225 should use `molecularProfileUtil. isStructuralVariantMolecularProfile` or at least the same logic as it because it's missing the special mskarcher case

I'm not sure if that's _ALL_ that would have caused the SV table to break for mskarcher. I will wrap up my investigation Monday morning.
