### ISSUE TITLE
Pathways tab doesn't work in Safari

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9093]
http://www.cbioportal.org/patient/pathways?studyId=metastatic_solid_tumors_mich_2017&caseId=ES_5001

**Comment by alisman** [comment]
@onursumer lets determine if this is on our end or pathways code

**Comment by onursumer** [comment]
A quick debug in Safari developer console shows that the problem is originated from this import statement: https://github.com/cBioPortal/cbioportal-frontend/blob/7d9adcc403e23c90872a26642fffdc5606e53d35/src/pages/resultsView/pathwayMapper/ResultsViewPathwayMapper.tsx#L77-L82  

```JavaScript
import(/* webpackChunkName: "pathway-mapper" */ 'pathway-mapper').then(
    (module: any) => {
        this.PathwayMapperComponent = (module as any)
            .default as PathwayMapper;
    }
);
```

For some reason Safari may not be happy with this workaround.

**Comment by onursumer** [comment]
Looks like the actual problem is related to iVis-at-Bilkent/cytoscape.js-context-menus#55. We should fix it on the pathway mapper side. The issue is triggered by https://github.com/iVis-at-Bilkent/pathway-mapper/blob/88fd04112567fcfb072c337f277d21ae3ca8f61b/packages/pathway-mapper/src/managers/EditorActionsManager.tsx#L101.

@Rgtemze suggests a workaround like this until there is a proper fix for iVis-at-Bilkent/cytoscape.js-context-menus#55:
```JavaScript
if (!isCBioPortal) {
    this.edgeEditing = this.cy.edgeEditing(edgeEditingOptions);
}
```

**Comment by alisman** [comment]
Nice find.  Lets fix.
