### ISSUE TITLE
OncoKB Proxy SSL Handshake Exception

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#9117]
There are few users have been experiencing the issue(https://groups.google.com/g/cbioportal/c/PqPe_A_62Mk/m/A2DwiT-7AQAJ) in the local deployment through docker. The following error was given.

`cbioportal-container | SEVERE: Servlet.service() for servlet [proxy] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://public.api.oncokb.org/api/v1/utils/cancerGeneList": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] with root cause`

**Comment by inodb** [comment]
I think this is the same user: https://groups.google.com/g/cbioportal/c/fT0VwhLYcRA.

Which other users have this particular issue? I seem to only be able to this other one: https://groups.google.com/g/cbioportal/c/1kBn0NWCfsk/m/P41_g0iyBwAJ, but it looks like the cause is different

I wasn't able to reproduce it on my end unfortunately. I guess one option might be to not use the proxy whenever they are using the public api?
