### ISSUE TITLE
log4j endangered ?

### ISSUE THREAD

**Issue by cablesky** [cBioPortal/cbioportal#9118]
Is cBioportal affected by log4j?

**Comment by messersc** [comment]
Hi,

cbioportal was using log4j v1.2 (or rather 1.3), which was not affected by the exploit reported on Friday in the news.
However, because the old version also has some weaknesses, the current main branch has an update to log4j v2.15, which should be fixed.

The current release does not have the fix yet, though.

@inodb because you replied to my ticket regarding log4j:

1) Who can quickly update log4j to v2.16? See https://lists.apache.org/thread/d6v4r6nosxysyq9rvnr779336yf0woz4

2) There should be a new release which includes the fix. Who do we need to talk to?

Best,
Clemens

**Comment by cablesky** [comment]
Also the cbioportal-docker-copose project? There is the version 3.7.9?

**Comment by inodb** [comment]
Hi @cablesky and @messersc - we are still working on this fix: https://github.com/cBioPortal/cbioportal/issues/9114. We had a temp fix but turns out we need to upgrade to 2.16. We'll try to get this out soon

**Comment by jjgao** [comment]
closing this - please track #9114.
