### ISSUE TITLE
histogram issue when selecting == or > bar

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9173]
From @tmazor: If I select the >14 bar, the histogram highlights both the 14 & >14 bars
![image](https://user-images.githubusercontent.com/10508276/146806040-af52997c-be05-4027-86e1-0e6275bacb8b.png)
I think the filter that gets applied is correct (header is right and when I browsed Clinical Data tab, all counts were 15+), but the histogram is misleading.
I don't see this happening with other histograms, so I suspect this is again related to the fact that each bar here is a single value.

**Comment by onursumer** [comment]
When we select both `14` and `>14` the bar chart display is correct but the header is misleading this time. It still shows `>14` but it should be `>=14`.

So, this is a frontend issue where we incorrectly interpret and render the applied filters. We need to fix both `BarChart.tsx` and `UserSelections.tsx` components in order to display the selected filters properly. It's probably a better idea to create a separate issue for the user selections component though.

**Comment by inodb** [comment]
follow up in https://github.com/cBioPortal/cbioportal/issues/9266
