### ISSUE TITLE
Document abbreviations

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#9223]
... asked by [a user](https://groups.google.com/g/cbioportal/c/OYmYExEZvKQ/m/U71lgfvJBgAJ).

Maybe we can add to FAQ?

- CNA - copy number alteration
- VUS - variant of unknown significance
- TBM - tumor mutational burden
- KM - Kaplan-Meier
- AMP - amplification
- HOMDEL - deep del
- MSI
- OQL
- ...

**Comment by tmazor** [comment]
I added a few more and will work on adding this to FAQ next week.

Related question @jjgao  - it struck me this week that we use HOMDEL in the CNA Genes table in study view.  Should we change that to DEEPDEL? I know the work to replace HOMDEL with DEEPDEL in OQL got much more complicated, so maybe this would be similarly complex, but given that we generally use 'deep' rather than 'homozygous', it might be clearer if we can make that change.

**Comment by jjgao** [comment]
@tmazor yes, I discussed with @Luke-Sikina . We think it's better to fix the frontend first.

**Comment by tmazor** [comment]
Great - I made a PR to add an FAQ question with abbreviations, and I'll make a separate ticket to change HOMDEL to DEEPDEL in study view
