### ISSUE TITLE
Oncogenic archer fusion is not counted in the SV/Fusion Driver category 

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/cbioportal#9309]
https://cbioportal.mskcc.org/results/mutations?cancer_study_list=mskimpact&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna&case_set_id=mskimpact_Bladder_Cancer&gene_list=FGFR2%2520FGFR3&geneset_list=%20&tab_index=tab_visualize&Action=Submit&mutations_gene=FGFR

![Screen Shot 2022-02-15 at 12 55 52 PM](https://user-images.githubusercontent.com/5400599/154120729-d25dcd7b-33a1-4982-9cbe-46fae52aeaac.png)

@onursumer let me know if you want me to take a look

**Comment by onursumer** [comment]
This is a data processing issue in the frontend. 

The function [generateAnnotateStructuralVariantQueryFromGenes](https://github.com/cBioPortal/cbioportal-frontend/blob/1f2d00a60ba6c28aeeddab3e8c84340b6245f2bc/packages/cbioportal-utils/src/oncokb/OncoKbUtils.ts#L251) relies on ids with `undefined` values due to the lack of `site2EntrezGeneId` for some SV data. This causes generation of duplicate ids. For example `2261_undefined` and `2263_undefined`.

Since we get unique query variants by id we lose the actual oncogenicity information for the example fusions above and conclude that they are not oncogenic. See https://github.com/cBioPortal/cbioportal-frontend/blob/18417bb334367bb765b816c38ba0faf69a5ca9c5/src/shared/lib/StoreUtils.ts#L878.

A potential fix is to find a better way to generate ids for SVs in the function [generateQueryStructuralVariantId](https://github.com/cBioPortal/cbioportal-frontend/blob/1f2d00a60ba6c28aeeddab3e8c84340b6245f2bc/packages/cbioportal-utils/src/oncokb/OncoKbUtils.ts#L79).

**Comment by onursumer** [comment]
For example we have 13 SVs with the same id `2261_undefined`:

<img width="764" alt="SV_2261_undefined" src="https://user-images.githubusercontent.com/3604198/156419230-c994c08b-49f9-4e84-beb2-88eb5309a883.png">
