### ISSUE TITLE
Consolidate search paths for portal.properties (and log4j.properties)

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#938]
- [x] 1. Remove references to $PORTAL_HOME in pom.xml files
- [x] 2. Change orders of search path in all spring context to $PORTAL_HOME/... and then classpath:....
- [x] 3. Check GlobalProperties.java, but it should be checking in this order too
- [x] 4. Turn off resource property filtering for all spring config files

Note - need to consider affect this has on db versioning code - we may have to filter one or more java classes with a db version - via maven/resources-plugin.

**Comment by morungos** [comment]
Just to comment that probably the syntax might be: 

```
            <property name="locations">
              <list>
                <value>file://#{systemEnvironment['PORTAL_HOME']}/portal.properties</value>
               ....
              </list>
            </property>
```

As I know the syntax used to use $PORTAL_HOME directly in Spring files as is currently the case (cf https://github.com/cBioPortal/cbioportal/blob/72acaf5e0a8719dd763750f8d2b8418bcb991bc4/web/src/main/resources/applicationContext-web.xml), because then there's a risk they get templated by Maven to a build-time location which defeats the purpose of using environment variables.

**Comment by n1zea144** [comment]
I think the reference to systemEnvironment is not need because of the following:
PropertyPlaceholderConfigurer.searchSystemEnvironment setting to true.   In any event, including in this issue - turn off all "filtering" of Spring configs so that templating happens at runtime.  Note, some of the complexity introduced here was a result of providing user configurable settings before the code was open source and all we could provide was binaries.  Now that we are open source, we have an opportunity to clean things up.

I am afraid some of this cleanup make cause exceptions in some environments.

**Comment by morungos** [comment]
Okay, that's great!! I'm going to have to work to sync some of my weirder deployment issues back into pull requests.

**Comment by morungos** [comment]
Whoo @zheins -- this is looking good :-)

**Comment by morungos** [comment]
Note the comment from the closed ticket. Sometimes Spring configures from `file:///${PORTAL_HOME}/src/main/resources/portal.properties` and sometimes from `file:///${PORTAL_HOME}/portal.properties`. We're also using duplicate `propertyPlaceholderConfigurer` beans in different files. All of these issues remain to be addressed, and this is still a significant obstacle for us.

**Comment by n1zea144** [comment]
This is a mistake.  @zheins can you look at this?

We only want to reference /src/main/resources/portal.properties at build time and via relative path, not $PORTAL_HOME. 

Can you provide example of duplicate propertyPlaceholderConfigurer?  Shouldn't there be one per context?

**Comment by morungos** [comment]
The `propertyPlaceholderConfigurer` is a bean with an id, and yes: one per context, but not one per file. When you have multiple beans with the same id in different files (-business, -security, -web), it's an override: http://stackoverflow.com/questions/5849192/springs-overriding-bean. There's more or less one each. 

Having said that: I think I've just realized why. It's because we're not using "real" injection in some cases. We're creating a new context from one file, pulling the bean from that. That's bad, because not only is probably creating additional DB connections etc., it's risking differences between the two. We should totally stop instantiating new contexts to get settings, and use the static injection factory. 

However, because sometimes the XML files are assembled, and sometimes they're used standalone, that's probably why there are multiple configurers.

**Comment by morungos** [comment]
For example of this, see `SpringUtil`. This should not to the `initDataSource`, instead doing something like:

```
	<!-- Put the bean into the SpringUtil static field for access -->
	<b:bean class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
	    <b:property name="staticMethod"><b:value>org.mskcc.cbio.portal.util.SpringUtil.setAccessControl</b:value></b:property>
	    <b:property name="arguments">
	        <b:list>
	            <b:ref bean="accessControl"/>
	        </b:list>
	   </b:property>
	</b:bean>
```

**Comment by morungos** [comment]
I found a way to handle the log4j stuff too. I've dropped the:

```
    <context-param>
      <param-name>log4jConfigLocation</param-name>
      <param-value>file://${PORTAL_HOME}/src/main/resources/log4j.properties</param-value>
    </context-param> 
```

from the `web.xml` (where the prooperty/environment is templated) and replaced with Spring:

```
    <bean id="log4jConfigurer"
          class="org.springframework.beans.factory.config.MethodInvokingFactoryBean" >
		<property name="targetClass"><value>org.springframework.util.Log4jConfigurer</value></property>
		<property name="targetMethod"><value>initLogging</value></property>
		<property name="arguments">
			<list>
				<value>file:///${PORTAL_HOME}/log4j.properties</value>
			</list>
		</property>
    </bean>
```

Because this Spring, the PORTAL_HOME can be tweaked at runtime.

**Comment by morungos** [comment]
I'll add a new issue for the `SpringUtil` issue and make a PR for that now.

**Comment by morungos** [comment]
Oh my goodness -- this is how the database is set up for the scripts. Backwards, of course. The Spring context is instantiated and then used to inject into the various settings. Which is why we need something like this, instantiation on demand.

**Comment by n1zea144** [comment]
One issue is that we've slowly introduced Spring into parts of the codebase, but there is still a lot of code that is not spring managed.  For example, that initDataSource method is called by various classes in the scripts package into order to import data.  This situation is part of the refactoring I'd like to do during re-architecture.

In our case, we don't have a context which is constructed by multiple contexts, so doesn't each file require a propertyPlaceholderConfigurer (this could be a candidate bean to move into a shared xml)?

**Comment by morungos** [comment]
@n1zea144 Yes, this is what I'd forgotten, because we start the scripts differently. What we do is build a Spring context file from the staging folder, which specifies which scripts to run, and which order, more or less as an array of classes and command line arguments. It then calls the `main()` methods using reflection. This means we have started Spring and created a context before calling `initDataSource()`. This also allows us to run all the commands using the same connection, and therefore transactionally. 

Needless to say, I prefer this model, but I doubt if I'll win you all over immediately. 

The core issue is: a directly exposed `main()`, as you say, will need to manually initialize Spring. Personally, I'd endorse not directly exposing `main()` and expecting each script to do the right thing.

**Comment by n1zea144** [comment]
@morungos What you described is exactly what we are doing internally at MSK in our internal import pipeline (but we don't dynamically generate a context file).  The squirrelly code you are seeing is to support the command line tool available to the public during data import while simultaneously supporting the connection pooling provided by the web container for the web site....you don't have to win me over, I've already drunk the kool aid.

At this risk of sounding like a broken record, what you're pointing out are fundamental issues in the code base I'd like to address during the re-architecture effort.  Any chance you can come to NYC on April 11 for the day?  If not, I'm trying to coordinate a conf call prior.  You're input would be greatly appreciated....I don't feel as lonely down in the weeds anymore.

**Comment by morungos** [comment]
@n1zea144 I've put it to the boss :-) 

I've also make an initial PR on the transactional import wrapper we use here, backported to the current framework. It is probably useful already, and small enough for you to see how it works. There's even a small test. It's at: https://github.com/cBioPortal/cbioportal/pull/985

**Comment by n1zea144** [comment]
I'll take a look.  First I'd like to respond to your thoughts on the OIDC PR.

**Comment by morungos** [comment]
@n1zea144 And yes, I spoke to Trevor yesterday. He's okay with it, so I'm planning to make the NYC day on the 11th. I'm working away next couple of days, so I'll plan and book on Monday. So we can talk more then, and maybe work through some of the details.

**Comment by sambrightman** [comment]
Perhaps related to path cleanup: Docker currently fails to find `log4j.properties` in `core/src/main/resources`, with the `CMD` copying it to `src/main/resources` instead.
