### ISSUE TITLE
Log4j logging is broken

### ISSUE THREAD

**Issue by ruslan-forostianov** [cBioPortal/cbioportal#9451]
Hi guys,

It seems like log4j logging is broken.
The log4j.properties file is ignored. Any changes to it won't have any effect on the log.

The logging worked fine before [this commit](https://github.com/cBioPortal/cbioportal/commit/d0d0b1f3a75671952ee29913257b26b3453ea235).

The commit has an impact on version 3.7.21 and onwards.

**Comment by Luke-Sikina** [comment]
Thanks for bringing this to our attention. We have a fix for this here: https://github.com/cBioPortal/cbioportal/pull/9454
It might take a day or so to get this merged due to some frontend artifact issues we're having with older portal versions, but feel free to cherry pick the commit in that PR if you need to get logging back urgently.

**Comment by Luke-Sikina** [comment]
This is now fixed in the docker image `cbioportal/cbioportal:release-3.7.latest`.

**Comment by ruslan-forostianov** [comment]
@Luke-Sikina Thank you!

**Comment by ruslan-forostianov** [comment]
@Luke-Sikina I've tested the image. I can see that slf4 no-operation (NOP) logger issue is fixed indeed. Hence I see more logs. But `log4j.properties` file still seems to be ignored. Any changes to it won't have any effect on the log output. Any idea how to fix that?
