### ISSUE TITLE
How to annotate mutations as pathogenic or VUS and then visualize it?

### ISSUE THREAD

**Issue by arpanda** [cBioPortal/cbioportal#9498]
HI, 
In a local cBioPortal instance,  I am trying visualize annotate mutations (pathogenic or VUS) based on our annotations. I am not sure which field to use. In the data import documentation, I found `cbp_driver` and `cbp_driver_annotation` column of `Extended MAF format` may enable that. 

Here is how it looks for me.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/21196859/166080581-749211bc-27e8-4816-b238-dce4c8990ba5.png">

Any suggestion to fix it?

Arijit

**Comment by arpanda** [comment]
Currently, for some mutations its getting the annotations and for some its not. Not sure why ? any suggestion to correct it?

Here is the current view. 

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/21196859/166962947-fe11447f-e563-43fe-a013-b7699629a633.png">

For mutation on TP53 gene, I set it as 'Putative_Driver' for the column `cbp_driver ` and 'Pathogenic' for  `cbp_driver_annotation `.  It would also solve our issue, if somehow, I can access `cbp_driver ` column. But that column is not showing in columns dropdown list.

**Comment by jjgao** [comment]
Hi @arpanda, it was because three-letter codes instead of 1-letter code was used for amino acids in Protein Change column. If you switch to 1-letter code, the Annotation column should be populated correctly. I also noticed there are a lot of "MUTATED" in the column. You might want to consider reannotating your MAFs: https://docs.cbioportal.org/file-formats/#minimal-maf-format

**Comment by jjgao** [comment]
Please feel free to contact our support group cbioportal@googlegroups.com for additional questions.
