### ISSUE TITLE
Investigate why lollipop plot has degraded performance

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9530]

**Comment by onursumer** [comment]
The problem is the very poor performance of https://github.com/cBioPortal/cbioportal-frontend/blob/8c6ec6cab1551dfbdef211c8480f352442f9a363/packages/cbioportal-utils/src/hotspot/CancerHotspotsUtils.ts#L38

There is partial fix for the initial load of the page: cBioPortal/cbioportal-frontend#4253. However, the page becomes very unresponsive as soon as the Hotspots track is enabled.

**Comment by onursumer** [comment]
Seems like `concat` function really slows things down. Using a combination of `map` and `flatten` works a lot better.
