### ISSUE TITLE
pathwaymapper shows 101% altered

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9557]
![Screen Shot 2022-05-19 at 4 11 41 PM](https://user-images.githubusercontent.com/1334004/169396386-e04253d5-c010-42ca-95e5-52a81e94824b.png)
https://www.cbioportal.org/results/pathways?cancer_study_list=msk_impact_2017&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna&case_set_id=msk_impact_2017_cnaseq&gene_list=EGFR%2520ERBB2%2520PDGFRA%2520MET%2520KRAS%2520NRAS%2520HRAS%2520NF1%2520SPRY2%2520FOXO1%2520FOXO3%2520AKT1%2520AKT2%2520AKT3%2520PIK3R1%2520PIK3CA%2520PTEN&geneset_list=%20&tab_index=tab_visualize&Action=Submit

**Comment by YusufZiyaOzgul** [comment]
The problem is in PathwayMapper. In Pathway Mapper, the frequency(percentage) of genes whose `gene.altered` = 0 and `gene.sequenced` = 0 are assigned as -101 to prevent possible runtime errors related to operations with NaN.

`// a percentage. -101 is chosen because this percentage is impossible to get.
this.alterationData[PathwayMapper.CBIO_PROFILE_NAME][geneAltData.gene] = ((Object.is(perc, NaN) ? -101 : perc));`

There are two ways to solve this issue.
First one is not giving these genes as a properties of PathwayMapper.
If we do not send the gene(SOS1) which is not sequenced, we have the following pathway since it is not handled in Pathway Mapper.
![Screenshot from 2022-06-21 14-41-06](https://user-images.githubusercontent.com/48672785/174791005-c82f8c6a-3eda-447a-9230-e8bd4f960d02.png).
Second way is to solve this issue in PathwayMapper side.
Not sequenced genes can be shown as gray and there is percentage written on them. Gray is used to denote these genes are not sequenced.

**Comment by onursumer** [comment]
@inodb Now we are properly displaying `N/P` instead of `101` for not profiled genes. Thanks @YusufZiyaOzgul! We still need to publish a new version of PathwayMapper with this fix included and then open a PR to point the new version.

![Pathways_SOS1_NP](https://user-images.githubusercontent.com/3604198/175610444-d1b72845-3ec1-4705-8bd8-fb68c890fe09.png)

**Comment by inodb** [comment]
@onursumer that looks great! Thank you!!
