### ISSUE TITLE
Data in METABRIC BRCA

### ISSUE THREAD

**Issue by ibabedal** [cBioPortal/cbioportal#9820]
Hello Team,

I am not sure if this is the right place to ask, but for the data of the METABRIC BRCA, there used to be a file containing the gene expression in the older version of the data, but currently, it is not there.

Can you please help us to check and confirm whether it should be there or if it is removed?

Regards,

**Comment by jjgao** [comment]
Hi, expression data does exist in the [metabric study](https://github.com/cBioPortal/datahub/tree/master/public/brca_metabric): 
[data_mrna_agilent_microarray.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/data_mrna_agilent_microarray.txt)

**Comment by rocanja** [comment]
The **gene expression file with the log2 intensities** (data_mrna_agilent_microarray.txt) is still available in the data download section of cBioPortal. Go to [cBioPortal Data Sets](https://www.cbioportal.org/datasets), search for 'metabric' and download the zip folder - it will be one of the files in the download and there will also be the files with the zscored expression data (plus the meta data). In the online portal / query section, only the zscored expression data (mRNA expression z-scores relative to all samples (log microarray)) seems to be accessible at the moment (Dec-2022). Please note that the metabric data is based on an Illumina microarray and not Agilent and thus, the filename is misleading ... there is a ticket for this issue here #1729

**Comment by DarioS** [comment]
It is missing in the portal, though.
![image](https://github.com/user-attachments/assets/0c956415-dff7-4709-b170-42cd87baf74a)
