### ISSUE TITLE
Group Comparison Pathway Mapper followup issues

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal#9937]
Reported by @Sjoerd-van-Hagen:

- [x] 1. With more than 2 groups you may get overlapping boxes
- [x] 2. What may be counterintuitive is that when selecting different subsets of the groups the selected pathway can change (based on the ranking). Maybe the selected pathway needs to be sticky when the user (de)selects a group
- [x] 3. Colors can be problematic for people, highly altered genes get a red background color for the group and then it is harder to see the color of the border that indicated which group it is
- [x] 4. A mouseover would be useful to show the label of the group. Now a user needs to match the color in the pathway with the color of the group at the top. Pathway view fills up the window, which is nice because there is a lot of stuff that needs to fit in but then you do not see the groups anymore. Having a mouse over would prevent having to scroll up and down

We can probably fix these as a followup PR to cBioPortal/cbioportal-frontend#4372

**Comment by ugurdogrusoz** [comment]
1. The user may choose to re-layout manually or automatically
2. Let's maintain the user choices (including any options) when grouping changes
3. Perhaps we could use a black and white color spectrum here (assuming group colors are not black or white)?
4. Let's implement a tooltip where the group names and corresponding values are shown as text in the associated group color

**Comment by Sjoerd-van-Hagen** [comment]
That would be great @ugurdogrusoz !

**Comment by onursumer** [comment]
Feedback from @Sjoerd-van-Hagen:

- [ ] This is great! I think it is more user friendly with the selected pathway not changing. The tooltip alleviates the problem of the overlap that occurs when multiple groups are selected but it would be even better if we could avoid the overlap altogether but that may be beyond the scope of  your work.
- [ ] What is a bit odd is that the readability in the tooltip is less than the actual numbers in the boxes. Normally a tooltip would be more readable than the element on which it sits.
- [ ] I think the little 'mini map' in the bottom right corner should cover the whole pathway so that you can see where you are? In that case it is not working as it should because it does not show everything.
- [ ] It does not show the right location either. Not sure if that is an issue of the library or the way we use it though.

![pathwaymapper-mini-map](https://user-images.githubusercontent.com/3604198/217065774-78fb5f83-9a90-4f39-8d6c-d4484c8d0294.png)

**Comment by ugurdogrusoz** [comment]
3. I understand using a gray scale color coding is not desired, so we leave it as is.
4. ...
5. The only thing that can be done to avoid the overlap is automatically applying an incremental layout as the number of groups change but then the user might not be happy with this since it will result in possible drastic changes in the layout. I recommend that we keep it as is and let the user apply incremental layout manually if they like.
6. If I understand correctly, here you're referring to the fact that if zoomed in the font size used in tooltips might be smaller than the actual font size used inside the nodes. This is simply because automatically making the font size bigger than the font size for the current zoom level is difficult (if not impossible). So long as the font size of the tooltips (which are fixed) are reasonably readable, we should be fine. If you like we can increase the fixed font size used in tooltips a little bit.
7. This is a bug in the overview window (mini map) extension, which we don't maintain (and don't have the resources to fix at the moment).

**Comment by Sjoerd-van-Hagen** [comment]
@ugurdogrusoz Fair points!

5. So the user has to click the perform layout button? That would work indeed but I am not sure if users know where to find the option.

6. Let's make the font size in the tool tips a little larger. Can we also make the letters black and have the color in a little box before the letters. I think the readability problem is mainly because of some of the colors being used. A bolder font may also help and is probably easier to implement.

7. @onursumer can we report the issue with the mini map extension to whoever is maintaining it?

**Comment by onursumer** [comment]
@Sjoerd-van-Hagen @ugurdogrusoz Before reporting anything to `cytoscape.js` team I think we should first try upgrading the cytoscape dependencies on our side. Seems like PathwayMapper is still using the cytoscape v3.8.2 which is 4 years old. Upgrading to the latest version may fix the mini map issue, but on the other hand it may break the custom features we introduced.

**Comment by ugurdogrusoz** [comment]
5. Yes, the layout button is one of the 4 tools in the toolbar (the one before "i" for help).
6. OK, let's do it this way
7. Upgrading the mini map and/or the Cytoscape.js version would be too risky. To be honest, the kind of pathways we have in cBio are rather small anyway, mini map is completely useless. I suggest we remove it from the cBio edition.

**Comment by Sjoerd-van-Hagen** [comment]
I think I agree that the minimap can, and probably should be, removed but I would like @cBioPortal/product to confirm.

**Comment by ugurdogrusoz** [comment]
> I think I agree that the minimap can, and probably should be, removed but I would like @cBioPortal/product to confirm.

What do you think @inodb @jjgao @schultzn ?

**Comment by inodb** [comment]
@ugurdogrusoz yeah makes sense to remove the minimap. If we ever add bigger pathways we can reintroduce it

**Comment by ugurdogrusoz** [comment]
Looks like we have addressed all the issues here. One last minor improvement with the tooltips is let's increase the font size (including the colored squares for group colors) a little bit and put more space (additional blank space) between these squares and the group name.

![image](https://user-images.githubusercontent.com/3874988/219290398-3da82cd5-2759-48fe-a8c3-8c0d86627619.png)

**Comment by ugurdogrusoz** [comment]
We should be ready for a release now. @onursumer Could you please provide one last build for testing? Then coordinate with @YusufZiyaOzgul for a PM release (these changes need to be pushed to both master and unstable branches of PM repo).

**Comment by onursumer** [comment]
@ugurdogrusoz I have updated the PR. It can be tested at https://deploy-preview-4480--cbioportalfrontend.netlify.app/comparison/pathways?sessionId=5cf89323e4b0ab413787436c&featureFlags=group_comparison_pathways

**Comment by ugurdogrusoz** [comment]
All looks good to me if you guys OK this, let's start merging related PRs and releasing PathwayMapper.

**Comment by onursumer** [comment]
@ugurdogrusoz @YusufZiyaOzgul We still need to address the code review for cBioPortal/cbioportal-frontend#4480. We also need to update screenshot tests related to PathwayMapper since we removed the mini map.

@YusufZiyaOzgul These shouldn't prevent us from merging and releasing the code on the PathwayMapper side though. Can you open 2 separate PRs from your fork to PathwayMapper `master` and `stable` branches? Once everything looks good we can merge and release the new version of PathwayMapper.
