### ISSUE TITLE
Optimize rendering of the study view KM charts

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#9988]
https://cbioportal.mskcc.org/study/summary?id=mskimpact

The two KM charts wildly tax the resources of the browser for large samples.   Scripting time, measured in profiler, is cut by 60% when we remove them.  And peak memory footprint is reduced from 600MB to 300MB. 

Rendering points and allowing interactivity is probably not important for this view.  Perhaps we can sample and remove tooltips?

**Comment by alisman** [comment]
@dippindots product team agreed to getting rid of the censoring crosses and then doing binning.   The way binning should work is that we put events into bins by some configurable number of days.  We can apply this optimization only when there are more than say, 10k samples.

**Comment by dippindots** [comment]
@alisman @inodb @jjgao 
Comments from standup meeting:
- Remove censoring crosses for sure
- Rounding instead of binning, e.g. `100.3 months` and `100.9 months` fall into the same data point generated for `100 - 101 months`
- If we do rounding, modify the current tooltip to include new information: `# patients censored ` `# patients have event`
